"""
INFORMATIKA - 100 TA TO'LIQ MAVZU (har birida 5-10 test, to'g'ri javoblar har xil o'rinda)
"""
import os, django, sys
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'eduself.settings')
django.setup()
from core.models import Subject, SubjectCategory, Topic, Question, Answer

def get_or_create_informatics():
    cat, _ = SubjectCategory.objects.get_or_create(slug='aniq-fanlar', defaults={'name': 'Aniq fanlar', 'icon': 'bi-calculator', 'order': 2, 'is_active': True})
    subj, _ = Subject.objects.get_or_create(name='Informatika', defaults={'category': cat, 'description': 'Informatika fani - asoslardan murakkabgacha', 'icon': 'bi-laptop', 'order': 4, 'is_active': True})
    return subj

def add_topics(subject, topics_data):
    for td in topics_data:
        topic, created = Topic.objects.get_or_create(subject=subject, name=td['n'], defaults={'time_limit': td['t'], 'passing_score': 60, 'order': td['o'], 'is_active': True})
        print(f"{'✅' if created else 'ℹ️'} §{td['o']}: {td['n']} ({len(td['q'])} test)")
        for i, qd in enumerate(td['q']):
            q, qc = Question.objects.get_or_create(topic=topic, text=qd['t'], defaults={'points': 10, 'order': i + 1})
            if qc:
                for ad in qd['a']:
                    Answer.objects.create(question=q, text=ad['t'], is_correct=ad['c'])

# 100 TA TO'LIQ MAVZU
T = [
    {'n': 'Informatika faniga kirish', 't': 25, 'o': 1, 'q': [
        {'t': 'Informatika fani nimani o\'rganadi?', 'a': [{'t': 'Faqat kompyuterni', 'c': False}, {'t': 'Axborot va uni qayta ishlashni', 'c': True}, {'t': 'Faqat internetni', 'c': False}, {'t': 'Faqat dasturlashni', 'c': False}]},
        {'t': 'Axborot nima?', 'a': [{'t': 'Faqat raqamlar', 'c': False}, {'t': 'Faqat matn', 'c': False}, {'t': 'Ma\'lumot, xabar, bilim', 'c': True}, {'t': 'Faqat rasm', 'c': False}]},
        {'t': 'Informatika qayerda qo\'llaniladi?', 'a': [{'t': 'Faqat maktabda', 'c': False}, {'t': 'Barcha sohalarda', 'c': True}, {'t': 'Faqat ofisda', 'c': False}, {'t': 'Hech qayerda', 'c': False}]},
        {'t': 'Kompyuter nima?', 'a': [{'t': 'Faqat o\'yin o\'ynaydigan qurilma', 'c': False}, {'t': 'Faqat hisoblash mashinasi', 'c': False}, {'t': 'Axborotni qayta ishlovchi elektron qurilma', 'c': True}, {'t': 'Faqat matn yozish uchun', 'c': False}]},
        {'t': 'Informatikaning asosiy yo\'nalishlari?', 'a': [{'t': 'Faqat dasturlash', 'c': False}, {'t': 'Dasturlash, tarmoqlar, ma\'lumotlar bazasi, sun\'iy intellekt', 'c': True}, {'t': 'Faqat o\'yinlar', 'c': False}, {'t': 'Hech qanday yo\'nalish yo\'q', 'c': False}]},
        {'t': 'Axborot texnologiyalari nima?', 'a': [{'t': 'Faqat kompyuter', 'c': False}, {'t': 'Axborotni qayta ishlash usullari va vositalari', 'c': True}, {'t': 'Faqat internet', 'c': False}, {'t': 'Faqat telefon', 'c': False}]},
        {'t': 'Raqamli texnologiyalar hayotimizda qanday rol o\'ynaydi?', 'a': [{'t': 'Hech qanday rol yo\'q', 'c': False}, {'t': 'Faqat o\'yin-kulgi uchun', 'c': False}, {'t': 'Ta\'lim, ish, aloqa, tibbiyot va boshqa sohalarda muhim', 'c': True}, {'t': 'Faqat ishda', 'c': False}]},
    ]},
    {'n': 'Kompyuter tarixi', 't': 25, 'o': 2, 'q': [
        {'t': 'Birinchi mexanik hisoblash mashinasini kim yaratgan?', 'a': [{'t': 'Bill Geyts', 'c': False}, {'t': 'Bleyz Paskal', 'c': True}, {'t': 'Stiv Jobs', 'c': False}, {'t': 'Mark Tsukerberg', 'c': False}]},
        {'t': 'Birinchi elektron kompyuter?', 'a': [{'t': 'IBM PC', 'c': False}, {'t': 'ENIAC', 'c': True}, {'t': 'Macintosh', 'c': False}, {'t': 'iPhone', 'c': False}]},
        {'t': 'Kompyuter avlodlari nechta?', 'a': [{'t': '3 ta', 'c': False}, {'t': '5 ta', 'c': True}, {'t': '10 ta', 'c': False}, {'t': '2 ta', 'c': False}]},
        {'t': 'Birinchi avlod kompyuterlarda nima ishlatilgan?', 'a': [{'t': 'Tranzistorlar', 'c': False}, {'t': 'Elektron lampalar', 'c': True}, {'t': 'Mikrochiplar', 'c': False}, {'t': 'Kvant protsessorlari', 'c': False}]},
        {'t': 'Shaxsiy kompyuter (PC) qachon paydo bo\'lgan?', 'a': [{'t': '1950 yilda', 'c': False}, {'t': '1970-1980 yillarda', 'c': True}, {'t': '2000 yilda', 'c': False}, {'t': '1900 yilda', 'c': False}]},
        {'t': 'IBM PC qachon chiqarilgan?', 'a': [{'t': '1990 yilda', 'c': False}, {'t': '1981 yilda', 'c': True}, {'t': '2000 yilda', 'c': False}, {'t': '1970 yilda', 'c': False}]},
        {'t': 'Ada Lavleys kim edi?', 'a': [{'t': 'Birinchi dasturchi (ayol)', 'c': True}, {'t': 'Kompyuter ixtirochisi', 'c': False}, {'t': 'Internet yaratuvchisi', 'c': False}, {'t': 'Telefon ixtirochisi', 'c': False}]},
        {'t': 'Alan Tyuring nima bilan mashhur?', 'a': [{'t': 'Faqat matematika', 'c': False}, {'t': 'Kompyuter fanlari asoschilaridan, Enigma shifrini buzgan', 'c': True}, {'t': 'Faqat fizika', 'c': False}, {'t': 'Faqat kimyo', 'c': False}]},
    ]},
    {'n': 'Kompyuter tuzilishi', 't': 25, 'o': 3, 'q': [
        {'t': 'Kompyuterning asosiy qismlari?', 'a': [{'t': 'Faqat monitor', 'c': False}, {'t': 'Protsessor, xotira, kiritish/chiqarish qurilmalari', 'c': True}, {'t': 'Faqat klaviatura', 'c': False}, {'t': 'Faqat sichqoncha', 'c': False}]},
        {'t': 'Protsessor (CPU) nima?', 'a': [{'t': 'Xotira qurilmasi', 'c': False}, {'t': 'Kompyuterning miyasi, hisoblash qiladi', 'c': True}, {'t': 'Kiritish qurilmasi', 'c': False}, {'t': 'Chiqarish qurilmasi', 'c': False}]},
        {'t': 'Operativ xotira (RAM) nima?', 'a': [{'t': 'Doimiy xotira', 'c': False}, {'t': 'Vaqtinchalik ma\'lumot saqlash joyi', 'c': True}, {'t': 'Protsessor', 'c': False}, {'t': 'Monitor', 'c': False}]},
        {'t': 'Qattiq disk (HDD) nima?', 'a': [{'t': 'Vaqtinchalik xotira', 'c': False}, {'t': 'Doimiy ma\'lumot saqlash qurilmasi', 'c': True}, {'t': 'Protsessor', 'c': False}, {'t': 'Kiritish qurilmasi', 'c': False}]},
        {'t': 'SSD nima?', 'a': [{'t': 'Eski xotira turi', 'c': False}, {'t': 'Tez ishlash xotirasi (Solid State Drive)', 'c': True}, {'t': 'Protsessor turi', 'c': False}, {'t': 'Monitor turi', 'c': False}]},
        {'t': 'Kiritish qurilmalari qaysilar?', 'a': [{'t': 'Faqat monitor', 'c': False}, {'t': 'Klaviatura, sichqoncha, mikrofon, kamera', 'c': True}, {'t': 'Faqat printer', 'c': False}, {'t': 'Faqat dinamik', 'c': False}]},
        {'t': 'Chiqarish qurilmalari qaysilar?', 'a': [{'t': 'Faqat klaviatura', 'c': False}, {'t': 'Monitor, printer, dinamik', 'c': True}, {'t': 'Faqat sichqoncha', 'c': False}, {'t': 'Faqat mikrofon', 'c': False}]},
        {'t': 'Materik plata (motherboard) nima?', 'a': [{'t': 'Faqat protsessor', 'c': False}, {'t': 'Barcha qismlarni birlashtiruvchi asosiy plata', 'c': True}, {'t': 'Faqat xotira', 'c': False}, {'t': 'Faqat qattiq disk', 'c': False}]},
    ]},
    {'n': 'Operatsion tizimlar', 't': 25, 'o': 4, 'q': [
        {'t': 'Operatsion tizim nima?', 'a': [{'t': 'Faqat o\'yin', 'c': False}, {'t': 'Kompyuter resurslarini boshqaruvchi dastur', 'c': True}, {'t': 'Faqat matn muharriri', 'c': False}, {'t': 'Faqat brauzer', 'c': False}]},
        {'t': 'Mashhur operatsion tizimlar?', 'a': [{'t': 'Faqat Windows', 'c': False}, {'t': 'Windows, Linux, macOS, Android, iOS', 'c': True}, {'t': 'Faqat Linux', 'c': False}, {'t': 'Hech qanday tizim yo\'q', 'c': False}]},
        {'t': 'Windows operatsion tizimini kim yaratgan?', 'a': [{'t': 'Apple', 'c': False}, {'t': 'Microsoft kompaniyasi', 'c': True}, {'t': 'Google', 'c': False}, {'t': 'IBM', 'c': False}]},
        {'t': 'Linux operatsion tizimi qanday?', 'a': [{'t': 'Faqat pullik', 'c': False}, {'t': 'Ochiq kodli, bepul', 'c': True}, {'t': 'Faqat telefon uchun', 'c': False}, {'t': 'Ishlamaydi', 'c': False}]},
        {'t': 'macOS qaysi kompaniya mahsuloti?', 'a': [{'t': 'Microsoft', 'c': False}, {'t': 'Apple', 'c': True}, {'t': 'Google', 'c': False}, {'t': 'Samsung', 'c': False}]},
        {'t': 'Android operatsion tizimi qayerda ishlatiladi?', 'a': [{'t': 'Faqat kompyuterlarda', 'c': False}, {'t': 'Smartfonlar va planshetlarda', 'c': True}, {'t': 'Faqat serverlarda', 'c': False}, {'t': 'Hech qayerda', 'c': False}]},
        {'t': 'Operatsion tizimning asosiy vazifalari?', 'a': [{'t': 'Faqat o\'yin o\'ynash', 'c': False}, {'t': 'Resurslarni boshqarish, dasturlarni ishga tushirish', 'c': True}, {'t': 'Faqat internetga kirish', 'c': False}, {'t': 'Hech qanday vazifa yo\'q', 'c': False}]},
    ]},
    {'n': 'Fayl va papkalar', 't': 25, 'o': 5, 'q': [
        {'t': 'Fayl nima?', 'a': [{'t': 'Faqat papka', 'c': False}, {'t': 'Ma\'lumotlar to\'plami', 'c': True}, {'t': 'Faqat dastur', 'c': False}, {'t': 'Faqat rasm', 'c': False}]},
        {'t': 'Papka (katalog) nima?', 'a': [{'t': 'Faqat fayl', 'c': False}, {'t': 'Fayllarni saqlash joyi', 'c': True}, {'t': 'Faqat dastur', 'c': False}, {'t': 'Faqat rasm', 'c': False}]},
        {'t': 'Fayl kengaytmasi nima?', 'a': [{'t': 'Fayl nomi', 'c': False}, {'t': 'Fayl turini ko\'rsatuvchi qo\'shimcha (.txt, .jpg, .exe)', 'c': True}, {'t': 'Fayl hajmi', 'c': False}, {'t': 'Fayl sanasi', 'c': False}]},
        {'t': '.txt fayl nima?', 'a': [{'t': 'Rasm fayli', 'c': False}, {'t': 'Matnli fayl', 'c': True}, {'t': 'Video fayl', 'c': False}, {'t': 'Dastur fayli', 'c': False}]},
        {'t': '.jpg yoki .png fayl nima?', 'a': [{'t': 'Matnli fayl', 'c': False}, {'t': 'Rasm fayli', 'c': True}, {'t': 'Video fayl', 'c': False}, {'t': 'Audio fayl', 'c': False}]},
        {'t': '.exe fayl nima?', 'a': [{'t': 'Matnli fayl', 'c': False}, {'t': 'Dastur fayli (Windows)', 'c': True}, {'t': 'Rasm fayli', 'c': False}, {'t': 'Video fayl', 'c': False}]},
        {'t': 'Fayl hajmi qanday o\'lchanadi?', 'a': [{'t': 'Metr, kilometr', 'c': False}, {'t': 'Bayt, kilobayt, megabayt, gigabayt', 'c': True}, {'t': 'Gramm, kilogramm', 'c': False}, {'t': 'Sekund, minut', 'c': False}]},
        {'t': '1 kilobayt necha bayt?', 'a': [{'t': '100 bayt', 'c': False}, {'t': '1024 bayt', 'c': True}, {'t': '10 bayt', 'c': False}, {'t': '1000000 bayt', 'c': False}]},
    ]},
    {'n': 'Matn muharrirlari', 't': 25, 'o': 6, 'q': [
        {'t': 'Matn muharriri nima?', 'a': [{'t': 'Faqat rasm chizish dasturi', 'c': False}, {'t': 'Matn yozish va tahrirlash dasturi', 'c': True}, {'t': 'Faqat video tahrirlash dasturi', 'c': False}, {'t': 'Faqat o\'yin', 'c': False}]},
        {'t': 'Microsoft Word nima?', 'a': [{'t': 'Elektron jadval', 'c': False}, {'t': 'Matn muharriri', 'c': True}, {'t': 'Taqdimot dasturi', 'c': False}, {'t': 'Brauzer', 'c': False}]},
        {'t': 'Notepad nima?', 'a': [{'t': 'Murakkab grafik muharriri', 'c': False}, {'t': 'Oddiy matn muharriri', 'c': True}, {'t': 'Video muharriri', 'c': False}, {'t': 'O\'yin', 'c': False}]},
        {'t': 'Matn formatlash nima?', 'a': [{'t': 'Matnni o\'chirish', 'c': False}, {'t': 'Matnni bezash (shrift, rang, o\'lcham)', 'c': True}, {'t': 'Matnni saqlash', 'c': False}, {'t': 'Matnni chop etish', 'c': False}]},
        {'t': 'Shrift nima?', 'a': [{'t': 'Matn rangi', 'c': False}, {'t': 'Matn ko\'rinishi (Times New Roman, Arial)', 'c': True}, {'t': 'Matn hajmi', 'c': False}, {'t': 'Matn tili', 'c': False}]},
        {'t': 'Ctrl+C klavish birikmasining vazifasi?', 'a': [{'t': 'Qo\'yish (paste)', 'c': False}, {'t': 'Nusxa olish (copy)', 'c': True}, {'t': 'Kesish (cut)', 'c': False}, {'t': 'Saqlash (save)', 'c': False}]},
        {'t': 'Ctrl+V klavish birikmasining vazifasi?', 'a': [{'t': 'Nusxa olish (copy)', 'c': False}, {'t': 'Qo\'yish (paste)', 'c': True}, {'t': 'Kesish (cut)', 'c': False}, {'t': 'Saqlash (save)', 'c': False}]},
        {'t': 'Ctrl+S klavish birikmasining vazifasi?', 'a': [{'t': 'Nusxa olish', 'c': False}, {'t': 'Saqlash (save)', 'c': True}, {'t': 'Qo\'yish', 'c': False}, {'t': 'Kesish', 'c': False}]},
    ]},
    {'n': 'Elektron jadvallar', 't': 25, 'o': 7, 'q': [
        {'t': 'Elektron jadval nima?', 'a': [{'t': 'Faqat matn yozish dasturi', 'c': False}, {'t': 'Hisob-kitob va ma\'lumotlarni jadval ko\'rinishida qayta ishlash dasturi', 'c': True}, {'t': 'Faqat rasm chizish dasturi', 'c': False}, {'t': 'Faqat o\'yin', 'c': False}]},
        {'t': 'Microsoft Excel nima?', 'a': [{'t': 'Matn muharriri', 'c': False}, {'t': 'Elektron jadval dasturi', 'c': True}, {'t': 'Taqdimot dasturi', 'c': False}, {'t': 'Brauzer', 'c': False}]},
        {'t': 'Elektron jadvaldagi katak nima?', 'a': [{'t': 'Faqat qator', 'c': False}, {'t': 'Qator va ustun kesishgan joy', 'c': True}, {'t': 'Faqat ustun', 'c': False}, {'t': 'Faqat raqam', 'c': False}]},
        {'t': 'Katak manzili qanday ko\'rinishda?', 'a': [{'t': 'Faqat raqam', 'c': False}, {'t': 'Ustun harfi + qator raqami (A1, B2)', 'c': True}, {'t': 'Faqat harf', 'c': False}, {'t': 'Faqat belgi', 'c': False}]},
        {'t': 'Formula nima?', 'a': [{'t': 'Faqat matn', 'c': False}, {'t': 'Hisob-kitob uchun ifoda (=A1+B1)', 'c': True}, {'t': 'Faqat raqam', 'c': False}, {'t': 'Faqat rasm', 'c': False}]},
        {'t': 'SUM funksiyasi nima qiladi?', 'a': [{'t': 'Ko\'paytiradi', 'c': False}, {'t': 'Yig\'indi hisoblab beradi', 'c': True}, {'t': 'Bo\'ladi', 'c': False}, {'t': 'Ayiradi', 'c': False}]},
        {'t': 'AVERAGE funksiyasi nima qiladi?', 'a': [{'t': 'Maksimumni topadi', 'c': False}, {'t': 'O\'rtacha qiymatni hisoblab beradi', 'c': True}, {'t': 'Minimumni topadi', 'c': False}, {'t': 'Yig\'indini hisoblab beradi', 'c': False}]},
        {'t': 'Diagramma nima?', 'a': [{'t': 'Faqat jadval', 'c': False}, {'t': 'Ma\'lumotlarni grafik ko\'rinishda tasvirlash', 'c': True}, {'t': 'Faqat matn', 'c': False}, {'t': 'Faqat rasm', 'c': False}]},
    ]},
    {'n': 'Taqdimot dasturlari', 't': 25, 'o': 8, 'q': [
        {'t': 'Taqdimot dasturi nima?', 'a': [{'t': 'Faqat matn yozish dasturi', 'c': False}, {'t': 'Slaydlar yaratish va ko\'rsatish dasturi', 'c': True}, {'t': 'Faqat hisob-kitob dasturi', 'c': False}, {'t': 'Faqat o\'yin', 'c': False}]},
        {'t': 'Microsoft PowerPoint nima?', 'a': [{'t': 'Matn muharriri', 'c': False}, {'t': 'Taqdimot dasturi', 'c': True}, {'t': 'Elektron jadval', 'c': False}, {'t': 'Brauzer', 'c': False}]},
        {'t': 'Slayd nima?', 'a': [{'t': 'Faqat rasm', 'c': False}, {'t': 'Taqdimotning bitta sahifasi', 'c': True}, {'t': 'Faqat matn', 'c': False}, {'t': 'Faqat video', 'c': False}]},
        {'t': 'Taqdimotda nima bo\'lishi mumkin?', 'a': [{'t': 'Faqat matn', 'c': False}, {'t': 'Matn, rasm, video, audio, animatsiya', 'c': True}, {'t': 'Faqat rasm', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'Animatsiya nima?', 'a': [{'t': 'Faqat rasm', 'c': False}, {'t': 'Ob\'ektlarning harakati', 'c': True}, {'t': 'Faqat matn', 'c': False}, {'t': 'Faqat video', 'c': False}]},
        {'t': 'Taqdimot qayerda ishlatiladi?', 'a': [{'t': 'Faqat maktabda', 'c': False}, {'t': 'Dars, ma\'ruza, taqdimot, konferensiya', 'c': True}, {'t': 'Faqat ofisda', 'c': False}, {'t': 'Hech qayerda', 'c': False}]},
    ]},
    {'n': 'Grafik muharrirlar', 't': 25, 'o': 9, 'q': [
        {'t': 'Grafik muharriri nima?', 'a': [{'t': 'Faqat matn yozish dasturi', 'c': False}, {'t': 'Rasm chizish va tahrirlash dasturi', 'c': True}, {'t': 'Faqat hisob-kitob dasturi', 'c': False}, {'t': 'Faqat o\'yin', 'c': False}]},
        {'t': 'Paint dasturi nima?', 'a': [{'t': 'Matn muharriri', 'c': False}, {'t': 'Oddiy grafik muharriri', 'c': True}, {'t': 'Elektron jadval', 'c': False}, {'t': 'Brauzer', 'c': False}]},
        {'t': 'Adobe Photoshop nima?', 'a': [{'t': 'Oddiy matn muharriri', 'c': False}, {'t': 'Professional grafik muharriri', 'c': True}, {'t': 'Elektron jadval', 'c': False}, {'t': 'O\'yin', 'c': False}]},
        {'t': 'Rastrli grafika nima?', 'a': [{'t': 'Vektorli rasm', 'c': False}, {'t': 'Piksellardan tashkil topgan rasm', 'c': True}, {'t': 'Faqat matn', 'c': False}, {'t': 'Faqat video', 'c': False}]},
        {'t': 'Vektorli grafika nima?', 'a': [{'t': 'Piksellardan tashkil topgan rasm', 'c': False}, {'t': 'Matematik formulalar asosida chizilgan rasm', 'c': True}, {'t': 'Faqat matn', 'c': False}, {'t': 'Faqat video', 'c': False}]},
        {'t': 'Piksel nima?', 'a': [{'t': 'Rasm hajmi', 'c': False}, {'t': 'Rasmning eng kichik nuqtasi', 'c': True}, {'t': 'Rasm rangi', 'c': False}, {'t': 'Rasm nomi', 'c': False}]},
        {'t': 'Rastrli grafikaning kamchiligi?', 'a': [{'t': 'Juda kichik hajm', 'c': False}, {'t': 'Kattalashtirsa sifati pasayadi', 'c': True}, {'t': 'Hech qanday kamchilik yo\'q', 'c': False}, {'t': 'Juda tez ishlaydi', 'c': False}]},
    ]},
    {'n': 'Internet va World Wide Web', 't': 25, 'o': 10, 'q': [
        {'t': 'Internet nima?', 'a': [{'t': 'Faqat bitta kompyuter', 'c': False}, {'t': 'Butun dunyo bo\'ylab kompyuterlar tarmog\'i', 'c': True}, {'t': 'Faqat telefon', 'c': False}, {'t': 'Faqat televizor', 'c': False}]},
        {'t': 'WWW (World Wide Web) nima?', 'a': [{'t': 'Faqat elektron pochta', 'c': False}, {'t': 'Internetdagi veb-sahifalar tizimi', 'c': True}, {'t': 'Faqat o\'yin', 'c': False}, {'t': 'Faqat dastur', 'c': False}]},
        {'t': 'Veb-sahifa nima?', 'a': [{'t': 'Faqat kompyuterdagi fayl', 'c': False}, {'t': 'Internetdagi hujjat', 'c': True}, {'t': 'Faqat rasm', 'c': False}, {'t': 'Faqat video', 'c': False}]},
        {'t': 'Veb-sayt nima?', 'a': [{'t': 'Faqat bitta sahifa', 'c': False}, {'t': 'Bir nechta veb-sahifalar to\'plami', 'c': True}, {'t': 'Faqat rasm', 'c': False}, {'t': 'Faqat video', 'c': False}]},
        {'t': 'URL nima?', 'a': [{'t': 'Faqat domen nomi', 'c': False}, {'t': 'Veb-sahifa manzili (https://example.com)', 'c': True}, {'t': 'Faqat IP manzil', 'c': False}, {'t': 'Faqat fayl nomi', 'c': False}]},
        {'t': 'Brauzer nima?', 'a': [{'t': 'Faqat matn muharriri', 'c': False}, {'t': 'Veb-sahifalarni ko\'rish dasturi', 'c': True}, {'t': 'Faqat elektron jadval', 'c': False}, {'t': 'Faqat o\'yin', 'c': False}]},
        {'t': 'Mashhur brauzerlar?', 'a': [{'t': 'Faqat Word', 'c': False}, {'t': 'Chrome, Firefox, Safari, Edge', 'c': True}, {'t': 'Faqat Excel', 'c': False}, {'t': 'Hech qanday brauzer yo\'q', 'c': False}]},
        {'t': 'HTTP nima?', 'a': [{'t': 'Dasturlash tili', 'c': False}, {'t': 'Veb-sahifalar uzatish protokoli', 'c': True}, {'t': 'Operatsion tizim', 'c': False}, {'t': 'Grafik muharriri', 'c': False}]},
    ]},
    {'n': 'Elektron pochta', 't': 25, 'o': 11, 'q': [
        {'t': 'Elektron pochta (email) nima?', 'a': [{'t': 'Faqat oddiy pochta', 'c': False}, {'t': 'Internet orqali xabar yuborish xizmati', 'c': True}, {'t': 'Faqat telefon', 'c': False}, {'t': 'Faqat SMS', 'c': False}]},
        {'t': 'Email manzili qanday ko\'rinishda?', 'a': [{'t': 'Faqat user', 'c': False}, {'t': 'user@example.com', 'c': True}, {'t': 'Faqat example.com', 'c': False}, {'t': 'Faqat @', 'c': False}]},
        {'t': 'Mashhur email xizmatlari?', 'a': [{'t': 'Faqat Facebook', 'c': False}, {'t': 'Gmail, Yahoo, Outlook, Mail.ru', 'c': True}, {'t': 'Faqat Instagram', 'c': False}, {'t': 'Hech qanday xizmat yo\'q', 'c': False}]},
        {'t': 'Email yuborishda nima kerak?', 'a': [{'t': 'Faqat manzil', 'c': False}, {'t': 'Qabul qiluvchi manzili, mavzu, xabar matni', 'c': True}, {'t': 'Faqat matn', 'c': False}, {'t': 'Hech narsa kerak emas', 'c': False}]},
        {'t': 'Email ga fayl biriktirish mumkinmi?', 'a': [{'t': 'Yo\'q, mumkin emas', 'c': False}, {'t': 'Ha, attachment orqali', 'c': True}, {'t': 'Faqat rasm', 'c': False}, {'t': 'Faqat matn', 'c': False}]},
        {'t': 'CC nima degani?', 'a': [{'t': 'Faqat o\'chirish', 'c': False}, {'t': 'Carbon Copy - nusxa yuborish', 'c': True}, {'t': 'Faqat saqlash', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
    ]},
    {'n': 'Qidiruv tizimlari', 't': 20, 'o': 12, 'q': [
        {'t': 'Qidiruv tizimi nima?', 'a': [{'t': 'Faqat brauzer', 'c': False}, {'t': 'Internetda ma\'lumot qidirish xizmati', 'c': True}, {'t': 'Faqat email', 'c': False}, {'t': 'Faqat o\'yin', 'c': False}]},
        {'t': 'Eng mashhur qidiruv tizimi?', 'a': [{'t': 'Word', 'c': False}, {'t': 'Google', 'c': True}, {'t': 'Excel', 'c': False}, {'t': 'Paint', 'c': False}]},
        {'t': 'Boshqa qidiruv tizimlari?', 'a': [{'t': 'Faqat Google', 'c': False}, {'t': 'Bing, Yahoo, Yandex, DuckDuckGo', 'c': True}, {'t': 'Hech qanday tizim yo\'q', 'c': False}, {'t': 'Faqat Facebook', 'c': False}]},
        {'t': 'Qidiruv so\'rovini qanday yozish kerak?', 'a': [{'t': 'Faqat bitta harf', 'c': False}, {'t': 'Kalit so\'zlarni yozish', 'c': True}, {'t': 'Faqat raqam', 'c': False}, {'t': 'Hech narsa yozmaslik', 'c': False}]},
        {'t': 'Qo\'shtirnoq ("") nima uchun ishlatiladi?', 'a': [{'t': 'Faqat bezash uchun', 'c': False}, {'t': 'Aniq iborani qidirish uchun', 'c': True}, {'t': 'Hech narsa uchun', 'c': False}, {'t': 'Xato ko\'rsatish uchun', 'c': False}]},
    ]},
    {'n': 'Ijtimoiy tarmoqlar', 't': 20, 'o': 13, 'q': [
        {'t': 'Ijtimoiy tarmoq nima?', 'a': [{'t': 'Faqat email', 'c': False}, {'t': 'Odamlar muloqot qiladigan veb-sayt', 'c': True}, {'t': 'Faqat qidiruv tizimi', 'c': False}, {'t': 'Faqat o\'yin', 'c': False}]},
        {'t': 'Mashhur ijtimoiy tarmoqlar?', 'a': [{'t': 'Faqat Google', 'c': False}, {'t': 'Facebook, Instagram, Twitter, TikTok, Telegram', 'c': True}, {'t': 'Faqat Word', 'c': False}, {'t': 'Hech qanday tarmoq yo\'q', 'c': False}]},
        {'t': 'Ijtimoiy tarmoqlarda nima qilish mumkin?', 'a': [{'t': 'Faqat o\'qish', 'c': False}, {'t': 'Xabar yuborish, rasm/video ulashish, do\'stlar topish', 'c': True}, {'t': 'Hech narsa qilish mumkin emas', 'c': False}, {'t': 'Faqat yuklab olish', 'c': False}]},
        {'t': 'Profil nima?', 'a': [{'t': 'Faqat rasm', 'c': False}, {'t': 'Foydalanuvchi sahifasi', 'c': True}, {'t': 'Faqat matn', 'c': False}, {'t': 'Faqat video', 'c': False}]},
        {'t': 'Ijtimoiy tarmoqlarda xavfsizlik qoidalari?', 'a': [{'t': 'Hamma narsani ulashish', 'c': False}, {'t': 'Shaxsiy ma\'lumotlarni oshkor qilmaslik, notanish odamlarga ishonmaslik', 'c': True}, {'t': 'Parolni barchaga aytish', 'c': False}, {'t': 'Hech qanday qoida yo\'q', 'c': False}]},
    ]},
    {'n': 'Axborot xavfsizligi', 't': 25, 'o': 14, 'q': [
        {'t': 'Axborot xavfsizligi nima?', 'a': [{'t': 'Faqat kompyuterni o\'chirish', 'c': False}, {'t': 'Ma\'lumotlarni himoya qilish', 'c': True}, {'t': 'Faqat internetni o\'chirish', 'c': False}, {'t': 'Hech narsa qilmaslik', 'c': False}]},
        {'t': 'Parol nima?', 'a': [{'t': 'Faqat ism', 'c': False}, {'t': 'Maxfiy kalit so\'z', 'c': True}, {'t': 'Faqat raqam', 'c': False}, {'t': 'Faqat harf', 'c': False}]},
        {'t': 'Kuchli parol qanday bo\'lishi kerak?', 'a': [{'t': 'Faqat 123', 'c': False}, {'t': 'Uzun, harflar, raqamlar, belgilar aralash', 'c': True}, {'t': 'Faqat ism', 'c': False}, {'t': 'Faqat bitta harf', 'c': False}]},
        {'t': 'Virus nima?', 'a': [{'t': 'Foydali dastur', 'c': False}, {'t': 'Zararli dastur', 'c': True}, {'t': 'Faqat o\'yin', 'c': False}, {'t': 'Faqat fayl', 'c': False}]},
        {'t': 'Antivirus nima?', 'a': [{'t': 'Virus yaratuvchi dastur', 'c': False}, {'t': 'Viruslardan himoya qiluvchi dastur', 'c': True}, {'t': 'Faqat o\'yin', 'c': False}, {'t': 'Faqat brauzer', 'c': False}]},
        {'t': 'Spam nima?', 'a': [{'t': 'Foydali xabarlar', 'c': False}, {'t': 'Keraksiz xabarlar', 'c': True}, {'t': 'Faqat rasm', 'c': False}, {'t': 'Faqat video', 'c': False}]},
        {'t': 'Phishing nima?', 'a': [{'t': 'Foydali xizmat', 'c': False}, {'t': 'Shaxsiy ma\'lumotlarni o\'g\'irlash urinishi', 'c': True}, {'t': 'Faqat o\'yin', 'c': False}, {'t': 'Faqat email', 'c': False}]},
        {'t': 'Ikki faktorli autentifikatsiya nima?', 'a': [{'t': 'Faqat parol', 'c': False}, {'t': 'Parol + qo\'shimcha tasdiqlash (SMS, ilova)', 'c': True}, {'t': 'Faqat ism', 'c': False}, {'t': 'Hech qanday himoya yo\'q', 'c': False}]},
    ]},
    {'n': 'Kompyuter tarmoqlari', 't': 25, 'o': 15, 'q': [
        {'t': 'Kompyuter tarmog\'i nima?', 'a': [{'t': 'Faqat bitta kompyuter', 'c': False}, {'t': 'Bir nechta kompyuterlarning birlashmasi', 'c': True}, {'t': 'Faqat internet', 'c': False}, {'t': 'Faqat telefon', 'c': False}]},
        {'t': 'LAN nima?', 'a': [{'t': 'Global tarmoq', 'c': False}, {'t': 'Lokal tarmoq (Local Area Network)', 'c': True}, {'t': 'Faqat internet', 'c': False}, {'t': 'Faqat telefon tarmog\'i', 'c': False}]},
        {'t': 'WAN nima?', 'a': [{'t': 'Lokal tarmoq', 'c': False}, {'t': 'Keng hudud tarmog\'i (Wide Area Network)', 'c': True}, {'t': 'Faqat bitta xona', 'c': False}, {'t': 'Faqat bitta bino', 'c': False}]},
        {'t': 'IP manzil nima?', 'a': [{'t': 'Faqat veb-sayt manzili', 'c': False}, {'t': 'Tarmoqdagi kompyuter manzili', 'c': True}, {'t': 'Faqat email manzili', 'c': False}, {'t': 'Faqat telefon raqami', 'c': False}]},
        {'t': 'Router nima?', 'a': [{'t': 'Faqat kompyuter', 'c': False}, {'t': 'Tarmoqlarni birlashtiruvchi qurilma', 'c': True}, {'t': 'Faqat telefon', 'c': False}, {'t': 'Faqat printer', 'c': False}]},
        {'t': 'Wi-Fi nima?', 'a': [{'t': 'Simli tarmoq', 'c': False}, {'t': 'Simsiz tarmoq texnologiyasi', 'c': True}, {'t': 'Faqat internet', 'c': False}, {'t': 'Faqat telefon', 'c': False}]},
    ]},
    {'n': 'Dasturlash asoslari', 't': 25, 'o': 16, 'q': [
        {'t': 'Dasturlash nima?', 'a': [{'t': 'Faqat o\'yin o\'ynash', 'c': False}, {'t': 'Kompyuter uchun ko\'rsatmalar yozish', 'c': True}, {'t': 'Faqat internetda sayr qilish', 'c': False}, {'t': 'Hech narsa qilmaslik', 'c': False}]},
        {'t': 'Dasturlash tili nima?', 'a': [{'t': 'Oddiy til', 'c': False}, {'t': 'Kompyuter bilan muloqot qilish tili', 'c': True}, {'t': 'Faqat ingliz tili', 'c': False}, {'t': 'Faqat rus tili', 'c': False}]},
        {'t': 'Mashhur dasturlash tillari?', 'a': [{'t': 'Faqat bitta til', 'c': False}, {'t': 'Python, Java, C++, JavaScript, C#', 'c': True}, {'t': 'Faqat ingliz tili', 'c': False}, {'t': 'Hech qanday til yo\'q', 'c': False}]},
        {'t': 'Algoritm nima?', 'a': [{'t': 'Faqat dastur', 'c': False}, {'t': 'Masalani yechish bosqichlari', 'c': True}, {'t': 'Faqat kod', 'c': False}, {'t': 'Faqat fayl', 'c': False}]},
        {'t': 'O\'zgaruvchi (variable) nima?', 'a': [{'t': 'Faqat raqam', 'c': False}, {'t': 'Ma\'lumot saqlaydigan joy', 'c': True}, {'t': 'Faqat matn', 'c': False}, {'t': 'Faqat dastur', 'c': False}]},
        {'t': 'Shart operatori nima?', 'a': [{'t': 'Faqat takrorlash', 'c': False}, {'t': 'Shartga qarab turli harakatlar (if-else)', 'c': True}, {'t': 'Faqat hisoblash', 'c': False}, {'t': 'Faqat chiqarish', 'c': False}]},
        {'t': 'Sikl (loop) nima?', 'a': [{'t': 'Faqat bitta marta bajarish', 'c': False}, {'t': 'Harakatlarni takrorlash', 'c': True}, {'t': 'Faqat shart', 'c': False}, {'t': 'Faqat o\'zgaruvchi', 'c': False}]},
    ]},
    {'n': 'Python dasturlash tili', 't': 20, 'o': 17, 'q': [
        {'t': 'Python nima?', 'a': [{'t': 'Hayvon', 'c': False}, {'t': 'Dasturlash tili', 'c': True}, {'t': 'Operatsion tizim', 'c': False}, {'t': 'Brauzer', 'c': False}]},
        {'t': 'Python nima uchun mashhur?', 'a': [{'t': 'Faqat qiyin', 'c': False}, {'t': 'Oson o\'rganish, ko\'p qo\'llaniladi', 'c': True}, {'t': 'Hech kim ishlatmaydi', 'c': False}, {'t': 'Faqat eski', 'c': False}]},
        {'t': 'print() funksiyasi nima qiladi?', 'a': [{'t': 'Faqat hisoblaydi', 'c': False}, {'t': 'Ekranga chiqaradi', 'c': True}, {'t': 'Faqat saqlaydi', 'c': False}, {'t': 'Faqat o\'chiradi', 'c': False}]},
        {'t': 'input() funksiyasi nima qiladi?', 'a': [{'t': 'Faqat chiqaradi', 'c': False}, {'t': 'Foydalanuvchidan ma\'lumot oladi', 'c': True}, {'t': 'Faqat hisoblaydi', 'c': False}, {'t': 'Faqat o\'chiradi', 'c': False}]},
        {'t': 'Python qayerda ishlatiladi?', 'a': [{'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Veb, sun\'iy intellekt, ma\'lumotlar tahlili', 'c': True}, {'t': 'Hech qayerda', 'c': False}, {'t': 'Faqat maktabda', 'c': False}]},
    ]},
    {'n': 'Ma\'lumotlar turlari', 't': 20, 'o': 18, 'q': [
        {'t': 'Integer (int) nima?', 'a': [{'t': 'Matn', 'c': False}, {'t': 'Butun son', 'c': True}, {'t': 'Haqiqiy son', 'c': False}, {'t': 'Mantiqiy qiymat', 'c': False}]},
        {'t': 'Float nima?', 'a': [{'t': 'Butun son', 'c': False}, {'t': 'Haqiqiy son (kasr)', 'c': True}, {'t': 'Matn', 'c': False}, {'t': 'Mantiqiy qiymat', 'c': False}]},
        {'t': 'String (str) nima?', 'a': [{'t': 'Son', 'c': False}, {'t': 'Matn', 'c': True}, {'t': 'Mantiqiy qiymat', 'c': False}, {'t': 'Ro\'yxat', 'c': False}]},
        {'t': 'Boolean nima?', 'a': [{'t': 'Son', 'c': False}, {'t': 'Mantiqiy qiymat (True/False)', 'c': True}, {'t': 'Matn', 'c': False}, {'t': 'Ro\'yxat', 'c': False}]},
        {'t': 'List (ro\'yxat) nima?', 'a': [{'t': 'Faqat bitta qiymat', 'c': False}, {'t': 'Ko\'p qiymatlar to\'plami', 'c': True}, {'t': 'Faqat son', 'c': False}, {'t': 'Faqat matn', 'c': False}]},
    ]},
    {'n': 'Amallar va operatorlar', 't': 20, 'o': 19, 'q': [
        {'t': '+ operatori nima qiladi?', 'a': [{'t': 'Ayiradi', 'c': False}, {'t': 'Qo\'shadi', 'c': True}, {'t': 'Ko\'paytiradi', 'c': False}, {'t': 'Bo\'ladi', 'c': False}]},
        {'t': '- operatori nima qiladi?', 'a': [{'t': 'Qo\'shadi', 'c': False}, {'t': 'Ayiradi', 'c': True}, {'t': 'Ko\'paytiradi', 'c': False}, {'t': 'Bo\'ladi', 'c': False}]},
        {'t': '* operatori nima qiladi?', 'a': [{'t': 'Qo\'shadi', 'c': False}, {'t': 'Ko\'paytiradi', 'c': True}, {'t': 'Ayiradi', 'c': False}, {'t': 'Bo\'ladi', 'c': False}]},
        {'t': '/ operatori nima qiladi?', 'a': [{'t': 'Qo\'shadi', 'c': False}, {'t': 'Bo\'ladi', 'c': True}, {'t': 'Ko\'paytiradi', 'c': False}, {'t': 'Ayiradi', 'c': False}]},
        {'t': '== operatori nima qiladi?', 'a': [{'t': 'Qiymat beradi', 'c': False}, {'t': 'Tengligini tekshiradi', 'c': True}, {'t': 'Qo\'shadi', 'c': False}, {'t': 'Ayiradi', 'c': False}]},
    ]},
    {'n': 'Shartli operatorlar', 't': 20, 'o': 20, 'q': [
        {'t': 'if operatori nima qiladi?', 'a': [{'t': 'Faqat takrorlaydi', 'c': False}, {'t': 'Shartni tekshiradi', 'c': True}, {'t': 'Faqat hisoblaydi', 'c': False}, {'t': 'Faqat chiqaradi', 'c': False}]},
        {'t': 'else operatori nima qiladi?', 'a': [{'t': 'Faqat takrorlaydi', 'c': False}, {'t': 'Shart bajarilmasa ishga tushadi', 'c': True}, {'t': 'Faqat hisoblaydi', 'c': False}, {'t': 'Faqat chiqaradi', 'c': False}]},
        {'t': 'elif operatori nima?', 'a': [{'t': 'Faqat if', 'c': False}, {'t': 'Qo\'shimcha shart (else if)', 'c': True}, {'t': 'Faqat else', 'c': False}, {'t': 'Faqat sikl', 'c': False}]},
        {'t': 'if x > 5: nima degani?', 'a': [{'t': 'x 5 ga teng', 'c': False}, {'t': 'x 5 dan katta bo\'lsa', 'c': True}, {'t': 'x 5 dan kichik', 'c': False}, {'t': 'x 5 ga teng emas', 'c': False}]},
        {'t': 'Shartli operator qanday yoziladi?', 'a': [{'t': 'Faqat if', 'c': False}, {'t': 'if shart: kod', 'c': True}, {'t': 'Faqat else', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
    ]},
    {'n': 'Sikllar (Loops)', 't': 20, 'o': 21, 'q': [
        {'t': 'for sikli nima qiladi?', 'a': [{'t': 'Faqat bitta marta', 'c': False}, {'t': 'Belgilangan marta takrorlaydi', 'c': True}, {'t': 'Hech qachon takrorlamaydi', 'c': False}, {'t': 'Faqat shart tekshiradi', 'c': False}]},
        {'t': 'while sikli nima qiladi?', 'a': [{'t': 'Faqat bitta marta', 'c': False}, {'t': 'Shart to\'g\'ri bo\'lguncha takrorlaydi', 'c': True}, {'t': 'Hech qachon takrorlamaydi', 'c': False}, {'t': 'Faqat belgilangan marta', 'c': False}]},
        {'t': 'range() funksiyasi nima qiladi?', 'a': [{'t': 'Faqat chiqaradi', 'c': False}, {'t': 'Sonlar ketma-ketligini yaratadi', 'c': True}, {'t': 'Faqat hisoblaydi', 'c': False}, {'t': 'Faqat saqlaydi', 'c': False}]},
        {'t': 'break operatori nima qiladi?', 'a': [{'t': 'Faqat davom ettiradi', 'c': False}, {'t': 'Siklni to\'xtatadi', 'c': True}, {'t': 'Faqat o\'tkazib yuboradi', 'c': False}, {'t': 'Hech narsa qilmaydi', 'c': False}]},
        {'t': 'continue operatori nima qiladi?', 'a': [{'t': 'Siklni to\'xtatadi', 'c': False}, {'t': 'Keyingi iteratsiyaga o\'tadi', 'c': True}, {'t': 'Hech narsa qilmaydi', 'c': False}, {'t': 'Faqat chiqaradi', 'c': False}]},
    ]},
    {'n': 'Funksiyalar', 't': 20, 'o': 22, 'q': [
        {'t': 'Funksiya nima?', 'a': [{'t': 'Faqat o\'zgaruvchi', 'c': False}, {'t': 'Qayta ishlatish mumkin bo\'lgan kod bloki', 'c': True}, {'t': 'Faqat sikl', 'c': False}, {'t': 'Faqat shart', 'c': False}]},
        {'t': 'def kalit so\'zi nima uchun?', 'a': [{'t': 'O\'zgaruvchi yaratish', 'c': False}, {'t': 'Funksiya yaratish', 'c': True}, {'t': 'Sikl yaratish', 'c': False}, {'t': 'Shart yaratish', 'c': False}]},
        {'t': 'return operatori nima qiladi?', 'a': [{'t': 'Faqat chiqaradi', 'c': False}, {'t': 'Qiymat qaytaradi', 'c': True}, {'t': 'Faqat saqlaydi', 'c': False}, {'t': 'Faqat o\'chiradi', 'c': False}]},
        {'t': 'Parametr nima?', 'a': [{'t': 'Faqat o\'zgaruvchi', 'c': False}, {'t': 'Funksiyaga beriladigan qiymat', 'c': True}, {'t': 'Faqat natija', 'c': False}, {'t': 'Faqat sikl', 'c': False}]},
        {'t': 'Funksiyani qanday chaqirish mumkin?', 'a': [{'t': 'Faqat def', 'c': False}, {'t': 'funksiya_nomi()', 'c': True}, {'t': 'Faqat return', 'c': False}, {'t': 'Chaqirib bo\'lmaydi', 'c': False}]},
    ]},
    {'n': 'Ro\'yxatlar (Lists)', 't': 20, 'o': 23, 'q': [
        {'t': 'Ro\'yxat qanday yaratiladi?', 'a': [{'t': 'Faqat ()', 'c': False}, {'t': '[]', 'c': True}, {'t': 'Faqat {}', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Ro\'yxat elementiga qanday murojaat qilish mumkin?', 'a': [{'t': 'Faqat nomi bilan', 'c': False}, {'t': 'Indeks orqali list[0]', 'c': True}, {'t': 'Faqat print bilan', 'c': False}, {'t': 'Murojaat qilib bo\'lmaydi', 'c': False}]},
        {'t': 'append() metodi nima qiladi?', 'a': [{'t': 'O\'chiradi', 'c': False}, {'t': 'Oxiriga element qo\'shadi', 'c': True}, {'t': 'Boshiga qo\'shadi', 'c': False}, {'t': 'Hech narsa qilmaydi', 'c': False}]},
        {'t': 'len() funksiyasi nima qiladi?', 'a': [{'t': 'Element qo\'shadi', 'c': False}, {'t': 'Uzunligini qaytaradi', 'c': True}, {'t': 'Element o\'chiradi', 'c': False}, {'t': 'Hech narsa qilmaydi', 'c': False}]},
        {'t': 'Ro\'yxatni qanday tartiblash mumkin?', 'a': [{'t': 'Faqat qo\'lda', 'c': False}, {'t': 'sort() metodi bilan', 'c': True}, {'t': 'Tartiblab bo\'lmaydi', 'c': False}, {'t': 'Faqat yangi yaratish', 'c': False}]},
    ]},
    {'n': 'Lug\'atlar (Dictionaries)', 't': 20, 'o': 24, 'q': [
        {'t': 'Lug\'at qanday yaratiladi?', 'a': [{'t': 'Faqat []', 'c': False}, {'t': '{}', 'c': True}, {'t': 'Faqat ()', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Lug\'at nima?', 'a': [{'t': 'Faqat ro\'yxat', 'c': False}, {'t': 'Kalit-qiymat juftliklari', 'c': True}, {'t': 'Faqat sonlar', 'c': False}, {'t': 'Faqat matnlar', 'c': False}]},
        {'t': 'Lug\'at elementiga qanday murojaat qilish mumkin?', 'a': [{'t': 'Faqat indeks', 'c': False}, {'t': 'Kalit orqali dict[key]', 'c': True}, {'t': 'Faqat nomi', 'c': False}, {'t': 'Murojaat qilib bo\'lmaydi', 'c': False}]},
        {'t': 'keys() metodi nima qaytaradi?', 'a': [{'t': 'Faqat qiymatlar', 'c': False}, {'t': 'Barcha kalitlar', 'c': True}, {'t': 'Faqat birinchi element', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'values() metodi nima qaytaradi?', 'a': [{'t': 'Faqat kalitlar', 'c': False}, {'t': 'Barcha qiymatlar', 'c': True}, {'t': 'Faqat birinchi element', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
    ]},
    {'n': 'Fayllar bilan ishlash', 't': 20, 'o': 25, 'q': [
        {'t': 'Faylni qanday ochish mumkin?', 'a': [{'t': 'Faqat print', 'c': False}, {'t': 'open() funksiyasi', 'c': True}, {'t': 'Faqat input', 'c': False}, {'t': 'Ochib bo\'lmaydi', 'c': False}]},
        {'t': '"r" rejimi nima?', 'a': [{'t': 'Yozish', 'c': False}, {'t': 'O\'qish (read)', 'c': True}, {'t': 'Qo\'shish', 'c': False}, {'t': 'O\'chirish', 'c': False}]},
        {'t': '"w" rejimi nima?', 'a': [{'t': 'O\'qish', 'c': False}, {'t': 'Yozish (write)', 'c': True}, {'t': 'Qo\'shish', 'c': False}, {'t': 'O\'chirish', 'c': False}]},
        {'t': '"a" rejimi nima?', 'a': [{'t': 'O\'qish', 'c': False}, {'t': 'Oxiriga qo\'shish (append)', 'c': True}, {'t': 'Yozish', 'c': False}, {'t': 'O\'chirish', 'c': False}]},
        {'t': 'read() metodi nima qiladi?', 'a': [{'t': 'Faylga yozadi', 'c': False}, {'t': 'Faylni o\'qiydi', 'c': True}, {'t': 'Faylni o\'chiradi', 'c': False}, {'t': 'Hech narsa qilmaydi', 'c': False}]},
    ]},
    {'n': 'Xatolar va istisnolar', 't': 20, 'o': 26, 'q': [
        {'t': 'Sintaksis xatosi nima?', 'a': [{'t': 'Mantiqiy xato', 'c': False}, {'t': 'Kod yozishda xato', 'c': True}, {'t': 'Ish vaqtidagi xato', 'c': False}, {'t': 'Hech qanday xato emas', 'c': False}]},
        {'t': 'Runtime xatosi nima?', 'a': [{'t': 'Sintaksis xatosi', 'c': False}, {'t': 'Dastur ishlayotganda yuzaga keladigan xato', 'c': True}, {'t': 'Mantiqiy xato', 'c': False}, {'t': 'Hech qanday xato emas', 'c': False}]},
        {'t': 'try-except nima uchun?', 'a': [{'t': 'Faqat chiqarish', 'c': False}, {'t': 'Xatolarni ushlash', 'c': True}, {'t': 'Faqat hisoblash', 'c': False}, {'t': 'Hech narsa uchun', 'c': False}]},
        {'t': 'ZeroDivisionError qachon yuzaga keladi?', 'a': [{'t': 'Qo\'shishda', 'c': False}, {'t': 'Nolga bo\'lishda', 'c': True}, {'t': 'Ko\'paytirishda', 'c': False}, {'t': 'Ayirishda', 'c': False}]},
        {'t': 'ValueError qachon yuzaga keladi?', 'a': [{'t': 'Faqat bo\'lishda', 'c': False}, {'t': 'Noto\'g\'ri qiymat turida', 'c': True}, {'t': 'Faqat qo\'shishda', 'c': False}, {'t': 'Hech qachon', 'c': False}]},
    ]},
    {'n': 'Modullar va kutubxonalar', 't': 20, 'o': 27, 'q': [
        {'t': 'Modul nima?', 'a': [{'t': 'Faqat o\'zgaruvchi', 'c': False}, {'t': 'Python fayli (kod to\'plami)', 'c': True}, {'t': 'Faqat funksiya', 'c': False}, {'t': 'Faqat klass', 'c': False}]},
        {'t': 'import kalit so\'zi nima qiladi?', 'a': [{'t': 'Faqat chiqaradi', 'c': False}, {'t': 'Modulni yuklaydi', 'c': True}, {'t': 'Faqat saqlaydi', 'c': False}, {'t': 'Hech narsa qilmaydi', 'c': False}]},
        {'t': 'math moduli nima uchun?', 'a': [{'t': 'Faqat matn', 'c': False}, {'t': 'Matematik funksiyalar', 'c': True}, {'t': 'Faqat vaqt', 'c': False}, {'t': 'Faqat tasodifiy sonlar', 'c': False}]},
        {'t': 'random moduli nima uchun?', 'a': [{'t': 'Faqat matematik', 'c': False}, {'t': 'Tasodifiy sonlar', 'c': True}, {'t': 'Faqat vaqt', 'c': False}, {'t': 'Faqat matn', 'c': False}]},
        {'t': 'datetime moduli nima uchun?', 'a': [{'t': 'Faqat matematik', 'c': False}, {'t': 'Sana va vaqt bilan ishlash', 'c': True}, {'t': 'Faqat tasodifiy', 'c': False}, {'t': 'Faqat matn', 'c': False}]},
    ]},
    {'n': 'Ob\'ektga yo\'naltirilgan dasturlash', 't': 20, 'o': 28, 'q': [
        {'t': 'OOP nima?', 'a': [{'t': 'Faqat funksiya', 'c': False}, {'t': 'Ob\'ektga yo\'naltirilgan dasturlash', 'c': True}, {'t': 'Faqat o\'zgaruvchi', 'c': False}, {'t': 'Faqat sikl', 'c': False}]},
        {'t': 'Klass nima?', 'a': [{'t': 'Faqat funksiya', 'c': False}, {'t': 'Ob\'ekt uchun shablon', 'c': True}, {'t': 'Faqat o\'zgaruvchi', 'c': False}, {'t': 'Faqat sikl', 'c': False}]},
        {'t': 'Ob\'ekt nima?', 'a': [{'t': 'Faqat klass', 'c': False}, {'t': 'Klassning namunasi', 'c': True}, {'t': 'Faqat funksiya', 'c': False}, {'t': 'Faqat o\'zgaruvchi', 'c': False}]},
        {'t': '__init__ metodi nima?', 'a': [{'t': 'Oddiy metod', 'c': False}, {'t': 'Konstruktor (ob\'ekt yaratish)', 'c': True}, {'t': 'Faqat chiqarish', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'self kalit so\'zi nima?', 'a': [{'t': 'Faqat o\'zgaruvchi', 'c': False}, {'t': 'Ob\'ektning o\'ziga murojaat', 'c': True}, {'t': 'Faqat funksiya', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
    ]},
    {'n': 'Meros olish (Inheritance)', 't': 20, 'o': 29, 'q': [
        {'t': 'Meros olish nima?', 'a': [{'t': 'Faqat yangi klass', 'c': False}, {'t': 'Boshqa klassdan xususiyatlarni olish', 'c': True}, {'t': 'Faqat funksiya', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'Parent klass nima?', 'a': [{'t': 'Faqat child', 'c': False}, {'t': 'Asosiy klass', 'c': True}, {'t': 'Faqat ob\'ekt', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'Child klass nima?', 'a': [{'t': 'Faqat parent', 'c': False}, {'t': 'Meros oluvchi klass', 'c': True}, {'t': 'Faqat ob\'ekt', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'super() funksiyasi nima qiladi?', 'a': [{'t': 'Faqat chiqaradi', 'c': False}, {'t': 'Parent klassga murojaat qiladi', 'c': True}, {'t': 'Faqat saqlaydi', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'Meros olishning afzalligi?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Kodni qayta ishlatish', 'c': True}, {'t': 'Faqat murakkablik', 'c': False}, {'t': 'Faqat sekinlik', 'c': False}]},
    ]},
    {'n': 'Ma\'lumotlar bazasi asoslari', 't': 20, 'o': 30, 'q': [
        {'t': 'Ma\'lumotlar bazasi nima?', 'a': [{'t': 'Faqat fayl', 'c': False}, {'t': 'Tuzilgan ma\'lumotlar to\'plami', 'c': True}, {'t': 'Faqat dastur', 'c': False}, {'t': 'Faqat papka', 'c': False}]},
        {'t': 'SQL nima?', 'a': [{'t': 'Dasturlash tili', 'c': False}, {'t': 'Ma\'lumotlar bazasi so\'rovlar tili', 'c': True}, {'t': 'Operatsion tizim', 'c': False}, {'t': 'Brauzer', 'c': False}]},
        {'t': 'Jadval (table) nima?', 'a': [{'t': 'Faqat fayl', 'c': False}, {'t': 'Ma\'lumotlar to\'plami', 'c': True}, {'t': 'Faqat dastur', 'c': False}, {'t': 'Faqat papka', 'c': False}]},
        {'t': 'SELECT operatori nima qiladi?', 'a': [{'t': 'O\'chiradi', 'c': False}, {'t': 'Ma\'lumotlarni tanlaydi', 'c': True}, {'t': 'Qo\'shadi', 'c': False}, {'t': 'Yangilaydi', 'c': False}]},
        {'t': 'INSERT operatori nima qiladi?', 'a': [{'t': 'O\'chiradi', 'c': False}, {'t': 'Yangi ma\'lumot qo\'shadi', 'c': True}, {'t': 'Tanlaydi', 'c': False}, {'t': 'Yangilaydi', 'c': False}]},
    ]},
    {'n': 'Veb-dasturlash asoslari', 't': 20, 'o': 31, 'q': [
        {'t': 'HTML nima?', 'a': [{'t': 'Dasturlash tili', 'c': False}, {'t': 'Veb-sahifa tuzilishi tili', 'c': True}, {'t': 'Ma\'lumotlar bazasi', 'c': False}, {'t': 'Operatsion tizim', 'c': False}]},
        {'t': 'CSS nima?', 'a': [{'t': 'Dasturlash tili', 'c': False}, {'t': 'Veb-sahifa dizayni tili', 'c': True}, {'t': 'Ma\'lumotlar bazasi', 'c': False}, {'t': 'Operatsion tizim', 'c': False}]},
        {'t': 'JavaScript nima?', 'a': [{'t': 'Faqat HTML', 'c': False}, {'t': 'Veb-sahifa dasturlash tili', 'c': True}, {'t': 'Faqat CSS', 'c': False}, {'t': 'Operatsion tizim', 'c': False}]},
        {'t': 'HTML teglar qanday yoziladi?', 'a': [{'t': 'Faqat []', 'c': False}, {'t': '<tag></tag>', 'c': True}, {'t': 'Faqat ()', 'c': False}, {'t': 'Faqat {}', 'c': False}]},
        {'t': 'CSS qanday ulanadi?', 'a': [{'t': 'Faqat HTML ichida', 'c': False}, {'t': '<link> tegi yoki <style> tegi', 'c': True}, {'t': 'Ulanmaydi', 'c': False}, {'t': 'Faqat JavaScript', 'c': False}]},
    ]},
    {'n': 'Sun\'iy intellekt asoslari', 't': 20, 'o': 32, 'q': [
        {'t': 'Sun\'iy intellekt (AI) nima?', 'a': [{'t': 'Faqat robot', 'c': False}, {'t': 'Kompyuterning fikrlash qobiliyati', 'c': True}, {'t': 'Faqat o\'yin', 'c': False}, {'t': 'Faqat dastur', 'c': False}]},
        {'t': 'Mashina o\'rganish (ML) nima?', 'a': [{'t': 'Faqat dasturlash', 'c': False}, {'t': 'Kompyuterning ma\'lumotlardan o\'rganishi', 'c': True}, {'t': 'Faqat o\'yin', 'c': False}, {'t': 'Faqat internet', 'c': False}]},
        {'t': 'Chuqur o\'rganish (Deep Learning) nima?', 'a': [{'t': 'Oddiy dasturlash', 'c': False}, {'t': 'Neyron tarmoqlar asosida o\'rganish', 'c': True}, {'t': 'Faqat o\'yin', 'c': False}, {'t': 'Faqat internet', 'c': False}]},
        {'t': 'AI qayerda qo\'llaniladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Ovoz tanish, rasm tanish, avtomobil, tibbiyot', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat telefonlarda', 'c': False}]},
        {'t': 'ChatGPT nima?', 'a': [{'t': 'Oddiy dastur', 'c': False}, {'t': 'AI chatbot', 'c': True}, {'t': 'Faqat o\'yin', 'c': False}, {'t': 'Faqat brauzer', 'c': False}]},
    ]},
    {'n': 'Kriptografiya asoslari', 't': 20, 'o': 33, 'q': [
        {'t': 'Kriptografiya nima?', 'a': [{'t': 'Faqat dasturlash', 'c': False}, {'t': 'Ma\'lumotlarni shifrlash fani', 'c': True}, {'t': 'Faqat tarmoq', 'c': False}, {'t': 'Faqat internet', 'c': False}]},
        {'t': 'Shifrlash nima?', 'a': [{'t': 'Ma\'lumotni ochish', 'c': False}, {'t': 'Ma\'lumotni yashirish', 'c': True}, {'t': 'Ma\'lumotni o\'chirish', 'c': False}, {'t': 'Ma\'lumotni nusxalash', 'c': False}]},
        {'t': 'Deshifrlash nima?', 'a': [{'t': 'Ma\'lumotni yashirish', 'c': False}, {'t': 'Shifrlangan ma\'lumotni ochish', 'c': True}, {'t': 'Ma\'lumotni o\'chirish', 'c': False}, {'t': 'Ma\'lumotni nusxalash', 'c': False}]},
        {'t': 'HTTPS nima?', 'a': [{'t': 'Oddiy HTTP', 'c': False}, {'t': 'Xavfsiz HTTP (shifrlangan)', 'c': True}, {'t': 'Faqat brauzer', 'c': False}, {'t': 'Faqat email', 'c': False}]},
        {'t': 'SSL/TLS nima?', 'a': [{'t': 'Dasturlash tili', 'c': False}, {'t': 'Xavfsiz aloqa protokoli', 'c': True}, {'t': 'Operatsion tizim', 'c': False}, {'t': 'Brauzer', 'c': False}]},
    ]},
    {'n': 'Bulutli texnologiyalar', 't': 20, 'o': 34, 'q': [
        {'t': 'Bulutli xizmat (Cloud) nima?', 'a': [{'t': 'Faqat internet', 'c': False}, {'t': 'Internetdagi resurslar va xizmatlar', 'c': True}, {'t': 'Faqat email', 'c': False}, {'t': 'Faqat brauzer', 'c': False}]},
        {'t': 'Bulutli xizmatning afzalliklari?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Har qayerdan kirish, xavfsizlik, tejamkorlik', 'c': True}, {'t': 'Faqat qimmat', 'c': False}, {'t': 'Faqat sekin', 'c': False}]},
        {'t': 'Mashhur bulutli xizmatlar?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Google Drive, Dropbox, iCloud, OneDrive', 'c': True}, {'t': 'Faqat email', 'c': False}, {'t': 'Faqat brauzer', 'c': False}]},
        {'t': 'SaaS nima?', 'a': [{'t': 'Faqat dastur', 'c': False}, {'t': 'Software as a Service (xizmat sifatida dastur)', 'c': True}, {'t': 'Faqat internet', 'c': False}, {'t': 'Faqat email', 'c': False}]},
        {'t': 'IaaS nima?', 'a': [{'t': 'Faqat dastur', 'c': False}, {'t': 'Infrastructure as a Service (infratuzilma xizmati)', 'c': True}, {'t': 'Faqat internet', 'c': False}, {'t': 'Faqat email', 'c': False}]},
    ]},
    {'n': 'Mobil ilovalar', 't': 20, 'o': 35, 'q': [
        {'t': 'Mobil ilova nima?', 'a': [{'t': 'Faqat veb-sayt', 'c': False}, {'t': 'Smartfon uchun dastur', 'c': True}, {'t': 'Faqat kompyuter dasturi', 'c': False}, {'t': 'Faqat o\'yin', 'c': False}]},
        {'t': 'Android ilovalar qanday yaratiladi?', 'a': [{'t': 'Faqat Python', 'c': False}, {'t': 'Java yoki Kotlin', 'c': True}, {'t': 'Faqat HTML', 'c': False}, {'t': 'Faqat CSS', 'c': False}]},
        {'t': 'iOS ilovalar qanday yaratiladi?', 'a': [{'t': 'Faqat Java', 'c': False}, {'t': 'Swift yoki Objective-C', 'c': True}, {'t': 'Faqat Python', 'c': False}, {'t': 'Faqat HTML', 'c': False}]},
        {'t': 'Cross-platform ilova nima?', 'a': [{'t': 'Faqat Android', 'c': False}, {'t': 'Bir kod - ko\'p platformada', 'c': True}, {'t': 'Faqat iOS', 'c': False}, {'t': 'Faqat veb', 'c': False}]},
        {'t': 'React Native nima?', 'a': [{'t': 'Faqat veb', 'c': False}, {'t': 'Cross-platform mobil dasturlash freymvorki', 'c': True}, {'t': 'Faqat Android', 'c': False}, {'t': 'Faqat iOS', 'c': False}]},
    ]},
    {'n': 'Git va versiya nazorati', 't': 20, 'o': 36, 'q': [
        {'t': 'Git nima?', 'a': [{'t': 'Dasturlash tili', 'c': False}, {'t': 'Versiya nazorat tizimi', 'c': True}, {'t': 'Operatsion tizim', 'c': False}, {'t': 'Brauzer', 'c': False}]},
        {'t': 'GitHub nima?', 'a': [{'t': 'Faqat Git', 'c': False}, {'t': 'Git repozitoriyalari uchun platforma', 'c': True}, {'t': 'Dasturlash tili', 'c': False}, {'t': 'Operatsion tizim', 'c': False}]},
        {'t': 'Commit nima?', 'a': [{'t': 'Faqat o\'chirish', 'c': False}, {'t': 'O\'zgarishlarni saqlash', 'c': True}, {'t': 'Faqat yuklab olish', 'c': False}, {'t': 'Faqat o\'qish', 'c': False}]},
        {'t': 'Push nima?', 'a': [{'t': 'Yuklab olish', 'c': False}, {'t': 'Serverga yuklash', 'c': True}, {'t': 'O\'chirish', 'c': False}, {'t': 'O\'qish', 'c': False}]},
        {'t': 'Pull nima?', 'a': [{'t': 'Yuklash', 'c': False}, {'t': 'Serverdan yuklab olish', 'c': True}, {'t': 'O\'chirish', 'c': False}, {'t': 'Saqlash', 'c': False}]},
    ]},
    {'n': 'API va veb-xizmatlar', 't': 20, 'o': 37, 'q': [
        {'t': 'API nima?', 'a': [{'t': 'Dasturlash tili', 'c': False}, {'t': 'Application Programming Interface', 'c': True}, {'t': 'Operatsion tizim', 'c': False}, {'t': 'Brauzer', 'c': False}]},
        {'t': 'REST API nima?', 'a': [{'t': 'Faqat dastur', 'c': False}, {'t': 'Veb-xizmatlar arxitekturasi', 'c': True}, {'t': 'Dasturlash tili', 'c': False}, {'t': 'Operatsion tizim', 'c': False}]},
        {'t': 'JSON nima?', 'a': [{'t': 'Dasturlash tili', 'c': False}, {'t': 'Ma\'lumot almashish formati', 'c': True}, {'t': 'Operatsion tizim', 'c': False}, {'t': 'Brauzer', 'c': False}]},
        {'t': 'GET so\'rovi nima qiladi?', 'a': [{'t': 'Ma\'lumot o\'chiradi', 'c': False}, {'t': 'Ma\'lumot oladi', 'c': True}, {'t': 'Ma\'lumot qo\'shadi', 'c': False}, {'t': 'Ma\'lumot yangilaydi', 'c': False}]},
        {'t': 'POST so\'rovi nima qiladi?', 'a': [{'t': 'Ma\'lumot oladi', 'c': False}, {'t': 'Ma\'lumot qo\'shadi', 'c': True}, {'t': 'Ma\'lumot o\'chiradi', 'c': False}, {'t': 'Ma\'lumot yangilaydi', 'c': False}]},
    ]},
    {'n': 'Algoritm murakkabligi', 't': 20, 'o': 38, 'q': [
        {'t': 'Big O notation nima?', 'a': [{'t': 'Dasturlash tili', 'c': False}, {'t': 'Algoritm murakkabligini o\'lchash', 'c': True}, {'t': 'Operatsion tizim', 'c': False}, {'t': 'Brauzer', 'c': False}]},
        {'t': 'O(1) nima degani?', 'a': [{'t': 'Chiziqli', 'c': False}, {'t': 'Doimiy vaqt', 'c': True}, {'t': 'Kvadratik', 'c': False}, {'t': 'Logarifmik', 'c': False}]},
        {'t': 'O(n) nima degani?', 'a': [{'t': 'Doimiy', 'c': False}, {'t': 'Chiziqli vaqt', 'c': True}, {'t': 'Kvadratik', 'c': False}, {'t': 'Logarifmik', 'c': False}]},
        {'t': 'O(n²) nima degani?', 'a': [{'t': 'Chiziqli', 'c': False}, {'t': 'Kvadratik vaqt', 'c': True}, {'t': 'Doimiy', 'c': False}, {'t': 'Logarifmik', 'c': False}]},
        {'t': 'Qaysi algoritm tezroq?', 'a': [{'t': 'O(n²)', 'c': False}, {'t': 'O(1)', 'c': True}, {'t': 'O(n)', 'c': False}, {'t': 'O(log n)', 'c': False}]},
    ]},
    {'n': 'Qidiruv algoritmlari', 't': 20, 'o': 39, 'q': [
        {'t': 'Chiziqli qidiruv nima?', 'a': [{'t': 'Faqat tartiblangan', 'c': False}, {'t': 'Ketma-ket tekshirish', 'c': True}, {'t': 'Faqat ikkilik', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Ikkilik qidiruv nima?', 'a': [{'t': 'Faqat tartibsiz', 'c': False}, {'t': 'Tartiblangan ro\'yxatda tez qidiruv', 'c': True}, {'t': 'Faqat chiziqli', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Ikkilik qidiruv shartlari?', 'a': [{'t': 'Tartibsiz ro\'yxat', 'c': False}, {'t': 'Tartiblangan ro\'yxat', 'c': True}, {'t': 'Hech qanday shart yo\'q', 'c': False}, {'t': 'Faqat kichik ro\'yxat', 'c': False}]},
        {'t': 'Qaysi qidiruv tezroq?', 'a': [{'t': 'Chiziqli', 'c': False}, {'t': 'Ikkilik (tartiblangan ro\'yxatda)', 'c': True}, {'t': 'Bir xil', 'c': False}, {'t': 'Hech biri', 'c': False}]},
        {'t': 'Chiziqli qidiruv murakkabligi?', 'a': [{'t': 'O(1)', 'c': False}, {'t': 'O(n)', 'c': True}, {'t': 'O(log n)', 'c': False}, {'t': 'O(n²)', 'c': False}]},
    ]},
    {'n': 'Saralash algoritmlari', 't': 20, 'o': 40, 'q': [
        {'t': 'Bubble sort nima?', 'a': [{'t': 'Tez algoritm', 'c': False}, {'t': 'Oddiy saralash algoritmi', 'c': True}, {'t': 'Murakkab algoritm', 'c': False}, {'t': 'Qidiruv algoritmi', 'c': False}]},
        {'t': 'Quick sort nima?', 'a': [{'t': 'Sekin algoritm', 'c': False}, {'t': 'Tez saralash algoritmi', 'c': True}, {'t': 'Qidiruv algoritmi', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Merge sort nima?', 'a': [{'t': 'Sekin algoritm', 'c': False}, {'t': 'Bo\'lib-birlashtirib saralash', 'c': True}, {'t': 'Qidiruv algoritmi', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Qaysi saralash eng oddiy?', 'a': [{'t': 'Quick sort', 'c': False}, {'t': 'Bubble sort', 'c': True}, {'t': 'Merge sort', 'c': False}, {'t': 'Heap sort', 'c': False}]},
        {'t': 'Qaysi saralash eng tez?', 'a': [{'t': 'Bubble sort', 'c': False}, {'t': 'Quick sort (o\'rtacha)', 'c': True}, {'t': 'Selection sort', 'c': False}, {'t': 'Insertion sort', 'c': False}]},
    ]},
    {'n': 'Ma\'lumot tuzilmalari: Stack', 't': 20, 'o': 41, 'q': [
        {'t': 'Stack nima?', 'a': [{'t': 'Faqat ro\'yxat', 'c': False}, {'t': 'LIFO (Last In First Out) tuzilma', 'c': True}, {'t': 'FIFO tuzilma', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'LIFO nima degani?', 'a': [{'t': 'Birinchi kirgan birinchi chiqadi', 'c': False}, {'t': 'Oxirgi kirgan birinchi chiqadi', 'c': True}, {'t': 'Tasodifiy chiqadi', 'c': False}, {'t': 'Hech qachon chiqmaydi', 'c': False}]},
        {'t': 'push() operatsiyasi nima qiladi?', 'a': [{'t': 'Element oladi', 'c': False}, {'t': 'Element qo\'shadi', 'c': True}, {'t': 'Element o\'chiradi', 'c': False}, {'t': 'Hech narsa qilmaydi', 'c': False}]},
        {'t': 'pop() operatsiyasi nima qiladi?', 'a': [{'t': 'Element qo\'shadi', 'c': False}, {'t': 'Yuqoridagi elementni oladi', 'c': True}, {'t': 'Hech narsa qilmaydi', 'c': False}, {'t': 'Faqat ko\'radi', 'c': False}]},
        {'t': 'Stack qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Funksiya chaqiruvlari, undo/redo', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat internetda', 'c': False}]},
    ]},
    {'n': 'Ma\'lumot tuzilmalari: Queue', 't': 20, 'o': 42, 'q': [
        {'t': 'Queue nima?', 'a': [{'t': 'LIFO tuzilma', 'c': False}, {'t': 'FIFO (First In First Out) tuzilma', 'c': True}, {'t': 'Faqat ro\'yxat', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'FIFO nima degani?', 'a': [{'t': 'Oxirgi kirgan birinchi chiqadi', 'c': False}, {'t': 'Birinchi kirgan birinchi chiqadi', 'c': True}, {'t': 'Tasodifiy chiqadi', 'c': False}, {'t': 'Hech qachon chiqmaydi', 'c': False}]},
        {'t': 'enqueue() operatsiyasi nima qiladi?', 'a': [{'t': 'Element oladi', 'c': False}, {'t': 'Oxiriga element qo\'shadi', 'c': True}, {'t': 'Element o\'chiradi', 'c': False}, {'t': 'Hech narsa qilmaydi', 'c': False}]},
        {'t': 'dequeue() operatsiyasi nima qiladi?', 'a': [{'t': 'Element qo\'shadi', 'c': False}, {'t': 'Birinchi elementni oladi', 'c': True}, {'t': 'Hech narsa qilmaydi', 'c': False}, {'t': 'Faqat ko\'radi', 'c': False}]},
        {'t': 'Queue qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Navbatlar, print queue, BFS algoritmi', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat internetda', 'c': False}]},
    ]},
    {'n': 'Linked List', 't': 20, 'o': 43, 'q': [
        {'t': 'Linked List nima?', 'a': [{'t': 'Oddiy ro\'yxat', 'c': False}, {'t': 'Bog\'langan tugunlar zanjiri', 'c': True}, {'t': 'Faqat array', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Node (tugun) nima?', 'a': [{'t': 'Faqat qiymat', 'c': False}, {'t': 'Ma\'lumot va keyingi tugunga havola', 'c': True}, {'t': 'Faqat havola', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'Linked List afzalligi?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Dinamik o\'lcham, oson qo\'shish/o\'chirish', 'c': True}, {'t': 'Faqat tez qidiruv', 'c': False}, {'t': 'Faqat kichik hajm', 'c': False}]},
        {'t': 'Linked List kamchiligi?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Sekin qidiruv, qo\'shimcha xotira', 'c': True}, {'t': 'Faqat katta hajm', 'c': False}, {'t': 'Faqat murakkab', 'c': False}]},
        {'t': 'Doubly Linked List nima?', 'a': [{'t': 'Faqat oldinga', 'c': False}, {'t': 'Ikki yo\'nalishli bog\'lanish', 'c': True}, {'t': 'Faqat orqaga', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
    ]},
    {'n': 'Tree ma\'lumot tuzilmasi', 't': 20, 'o': 44, 'q': [
        {'t': 'Tree nima?', 'a': [{'t': 'Chiziqli tuzilma', 'c': False}, {'t': 'Ierarxik tuzilma', 'c': True}, {'t': 'Faqat ro\'yxat', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Root nima?', 'a': [{'t': 'Oxirgi tugun', 'c': False}, {'t': 'Ildiz tugun', 'c': True}, {'t': 'O\'rta tugun', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Leaf nima?', 'a': [{'t': 'Ildiz tugun', 'c': False}, {'t': 'Oxirgi tugun (bolasi yo\'q)', 'c': True}, {'t': 'O\'rta tugun', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Binary Tree nima?', 'a': [{'t': 'Ko\'p bolali', 'c': False}, {'t': 'Har tugun maksimum 2 bolali', 'c': True}, {'t': 'Faqat 1 bolali', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Tree qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Fayl tizimi, DOM, ma\'lumotlar bazasi', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat internetda', 'c': False}]},
    ]},
    {'n': 'Graph ma\'lumot tuzilmasi', 't': 20, 'o': 45, 'q': [
        {'t': 'Graph nima?', 'a': [{'t': 'Faqat tree', 'c': False}, {'t': 'Tugunlar va qirralar to\'plami', 'c': True}, {'t': 'Faqat ro\'yxat', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Vertex (tugun) nima?', 'a': [{'t': 'Faqat qirra', 'c': False}, {'t': 'Graph nuqtasi', 'c': True}, {'t': 'Faqat yo\'l', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'Edge (qirra) nima?', 'a': [{'t': 'Faqat tugun', 'c': False}, {'t': 'Tugunlar orasidagi bog\'lanish', 'c': True}, {'t': 'Faqat yo\'l', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'Directed graph nima?', 'a': [{'t': 'Yo\'nalisiz', 'c': False}, {'t': 'Yo\'nalishli graph', 'c': True}, {'t': 'Faqat tree', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Graph qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Ijtimoiy tarmoqlar, xaritalar, tarmoqlar', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat matnda', 'c': False}]},
    ]},
    {'n': 'Rekursiya', 't': 20, 'o': 46, 'q': [
        {'t': 'Rekursiya nima?', 'a': [{'t': 'Faqat sikl', 'c': False}, {'t': 'Funksiyaning o\'zini chaqirishi', 'c': True}, {'t': 'Faqat iteratsiya', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Base case nima?', 'a': [{'t': 'Faqat rekursiya', 'c': False}, {'t': 'To\'xtash sharti', 'c': True}, {'t': 'Faqat davom ettirish', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Rekursiya afzalligi?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Oddiy kod, tabiiy yechim', 'c': True}, {'t': 'Faqat tez', 'c': False}, {'t': 'Faqat kam xotira', 'c': False}]},
        {'t': 'Rekursiya kamchiligi?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Ko\'p xotira, stack overflow xavfi', 'c': True}, {'t': 'Faqat murakkab', 'c': False}, {'t': 'Faqat sekin', 'c': False}]},
        {'t': 'Faktorial rekursiv hisoblash mumkinmi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha, n! = n * (n-1)!', 'c': True}, {'t': 'Faqat iterativ', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
    ]},
    {'n': 'Dynamic Programming', 't': 20, 'o': 47, 'q': [
        {'t': 'Dynamic Programming nima?', 'a': [{'t': 'Oddiy dasturlash', 'c': False}, {'t': 'Kichik masalalar yechimini saqlash', 'c': True}, {'t': 'Faqat rekursiya', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Memoization nima?', 'a': [{'t': 'Faqat hisoblash', 'c': False}, {'t': 'Natijalarni keshda saqlash', 'c': True}, {'t': 'Faqat o\'chirish', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'DP afzalligi?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Tezlik, takroriy hisoblashni oldini olish', 'c': True}, {'t': 'Faqat oddiylik', 'c': False}, {'t': 'Faqat kam xotira', 'c': False}]},
        {'t': 'Fibonacci DP bilan tezroqmi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha, O(n) vs O(2^n)', 'c': True}, {'t': 'Bir xil', 'c': False}, {'t': 'Sekinroq', 'c': False}]},
        {'t': 'DP qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Optimizatsiya masalalari, yo\'l topish', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat matnda', 'c': False}]},
    ]},
    {'n': 'Greedy algoritm', 't': 20, 'o': 48, 'q': [
        {'t': 'Greedy algoritm nima?', 'a': [{'t': 'Faqat rekursiya', 'c': False}, {'t': 'Har qadamda eng yaxshi tanlov', 'c': True}, {'t': 'Faqat DP', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Greedy algoritm doim optimal yechimmi?', 'a': [{'t': 'Ha, doim', 'c': False}, {'t': 'Yo\'q, ba\'zi masalalarda', 'c': True}, {'t': 'Hech qachon', 'c': False}, {'t': 'Faqat oddiy masalalarda', 'c': False}]},
        {'t': 'Greedy afzalligi?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Oddiy, tez', 'c': True}, {'t': 'Faqat murakkab', 'c': False}, {'t': 'Faqat sekin', 'c': False}]},
        {'t': 'Coin change masalasi greedy bilan yechilishi mumkinmi?', 'a': [{'t': 'Doim', 'c': False}, {'t': 'Ba\'zi hollarda (masalan, standart tangalar)', 'c': True}, {'t': 'Hech qachon', 'c': False}, {'t': 'Faqat kichik miqdorlarda', 'c': False}]},
        {'t': 'Greedy qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Huffman kodlash, Dijkstra algoritmi', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat matnda', 'c': False}]},
    ]},
    {'n': 'Backtracking', 't': 20, 'o': 49, 'q': [
        {'t': 'Backtracking nima?', 'a': [{'t': 'Faqat oldinga', 'c': False}, {'t': 'Barcha variantlarni sinab ko\'rish', 'c': True}, {'t': 'Faqat bitta yo\'l', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Backtracking qachon ishlatiladi?', 'a': [{'t': 'Hech qachon', 'c': False}, {'t': 'Barcha yechimlarni topish kerak bo\'lganda', 'c': True}, {'t': 'Faqat bitta yechim kerak', 'c': False}, {'t': 'Faqat oddiy masalalarda', 'c': False}]},
        {'t': 'N-Queens masalasi nima?', 'a': [{'t': 'Oddiy masala', 'c': False}, {'t': 'Shaxmat taxtasiga N ta malika qo\'yish', 'c': True}, {'t': 'Faqat matematik', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Sudoku backtracking bilan yechilishi mumkinmi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha', 'c': True}, {'t': 'Faqat oddiy sudoku', 'c': False}, {'t': 'Hech qachon', 'c': False}]},
        {'t': 'Backtracking murakkabligi?', 'a': [{'t': 'O(n)', 'c': False}, {'t': 'Eksponensial (juda sekin)', 'c': True}, {'t': 'O(log n)', 'c': False}, {'t': 'O(1)', 'c': False}]},
    ]},
    {'n': 'Divide and Conquer', 't': 20, 'o': 50, 'q': [
        {'t': 'Divide and Conquer nima?', 'a': [{'t': 'Faqat birlashtiris', 'c': False}, {'t': 'Bo\'lib, yech, birlashtiris', 'c': True}, {'t': 'Faqat bo\'lish', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Merge Sort qaysi strategiya?', 'a': [{'t': 'Greedy', 'c': False}, {'t': 'Divide and Conquer', 'c': True}, {'t': 'DP', 'c': False}, {'t': 'Backtracking', 'c': False}]},
        {'t': 'Quick Sort qaysi strategiya?', 'a': [{'t': 'Greedy', 'c': False}, {'t': 'Divide and Conquer', 'c': True}, {'t': 'DP', 'c': False}, {'t': 'Backtracking', 'c': False}]},
        {'t': 'Binary Search qaysi strategiya?', 'a': [{'t': 'Greedy', 'c': False}, {'t': 'Divide and Conquer', 'c': True}, {'t': 'DP', 'c': False}, {'t': 'Backtracking', 'c': False}]},
        {'t': 'Divide and Conquer afzalligi?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Samarali, parallel ishlash mumkin', 'c': True}, {'t': 'Faqat oddiy', 'c': False}, {'t': 'Faqat sekin', 'c': False}]},
    ]},
    {'n': 'Hash Table', 't': 20, 'o': 51, 'q': [
        {'t': 'Hash Table nima?', 'a': [{'t': 'Oddiy ro\'yxat', 'c': False}, {'t': 'Kalit-qiymat juftliklari (tez qidiruv)', 'c': True}, {'t': 'Faqat array', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Hash funksiyasi nima qiladi?', 'a': [{'t': 'Faqat saqlaydi', 'c': False}, {'t': 'Kalitni indeksga aylantiradi', 'c': True}, {'t': 'Faqat o\'chiradi', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'Collision nima?', 'a': [{'t': 'Hech qanday muammo yo\'q', 'c': False}, {'t': 'Ikki kalit bir indeksga tushishi', 'c': True}, {'t': 'Faqat xato', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'Hash Table qidiruv murakkabligi?', 'a': [{'t': 'O(n)', 'c': False}, {'t': 'O(1) o\'rtacha', 'c': True}, {'t': 'O(log n)', 'c': False}, {'t': 'O(n²)', 'c': False}]},
        {'t': 'Hash Table qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Lug\'atlar, kesh, ma\'lumotlar bazasi indekslari', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat matnda', 'c': False}]},
    ]},
    {'n': 'Heap ma\'lumot tuzilmasi', 't': 20, 'o': 52, 'q': [
        {'t': 'Heap nima?', 'a': [{'t': 'Oddiy ro\'yxat', 'c': False}, {'t': 'Maxsus binary tree', 'c': True}, {'t': 'Faqat array', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Max Heap nima?', 'a': [{'t': 'Eng kichik yuqorida', 'c': False}, {'t': 'Eng katta yuqorida', 'c': True}, {'t': 'Tartibsiz', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Min Heap nima?', 'a': [{'t': 'Eng katta yuqorida', 'c': False}, {'t': 'Eng kichik yuqorida', 'c': True}, {'t': 'Tartibsiz', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Heap qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Priority queue, Heap sort', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat matnda', 'c': False}]},
        {'t': 'Heap insert murakkabligi?', 'a': [{'t': 'O(1)', 'c': False}, {'t': 'O(log n)', 'c': True}, {'t': 'O(n)', 'c': False}, {'t': 'O(n²)', 'c': False}]},
    ]},
    {'n': 'Trie ma\'lumot tuzilmasi', 't': 20, 'o': 53, 'q': [
        {'t': 'Trie nima?', 'a': [{'t': 'Oddiy tree', 'c': False}, {'t': 'Prefix tree (so\'zlar uchun)', 'c': True}, {'t': 'Faqat binary tree', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Trie qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Autocomplete, spell checker, IP routing', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat raqamlarda', 'c': False}]},
        {'t': 'Trie afzalligi?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Tez prefix qidiruv', 'c': True}, {'t': 'Faqat kam xotira', 'c': False}, {'t': 'Faqat oddiy', 'c': False}]},
        {'t': 'Trie kamchiligi?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Ko\'p xotira talab qiladi', 'c': True}, {'t': 'Faqat sekin', 'c': False}, {'t': 'Faqat murakkab', 'c': False}]},
        {'t': 'Trie qidiruv murakkabligi?', 'a': [{'t': 'O(n²)', 'c': False}, {'t': 'O(m) - so\'z uzunligi', 'c': True}, {'t': 'O(log n)', 'c': False}, {'t': 'O(1)', 'c': False}]},
    ]},
    {'n': 'BFS algoritmi', 't': 20, 'o': 54, 'q': [
        {'t': 'BFS nima?', 'a': [{'t': 'Depth First Search', 'c': False}, {'t': 'Breadth First Search (kenglik bo\'yicha)', 'c': True}, {'t': 'Binary First Search', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'BFS qanday ishlaydi?', 'a': [{'t': 'Chuqurlikka boradi', 'c': False}, {'t': 'Qatlam-qatlam o\'rganadi', 'c': True}, {'t': 'Tasodifiy', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'BFS qaysi ma\'lumot tuzilmasidan foydalanadi?', 'a': [{'t': 'Stack', 'c': False}, {'t': 'Queue', 'c': True}, {'t': 'Array', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'BFS eng qisqa yo\'lni topadimi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha (vaznsiz graphda)', 'c': True}, {'t': 'Faqat ba\'zan', 'c': False}, {'t': 'Hech qachon', 'c': False}]},
        {'t': 'BFS murakkabligi?', 'a': [{'t': 'O(1)', 'c': False}, {'t': 'O(V + E) - tugunlar + qirralar', 'c': True}, {'t': 'O(log n)', 'c': False}, {'t': 'O(n²)', 'c': False}]},
    ]},
    {'n': 'DFS algoritmi', 't': 20, 'o': 55, 'q': [
        {'t': 'DFS nima?', 'a': [{'t': 'Breadth First Search', 'c': False}, {'t': 'Depth First Search (chuqurlik bo\'yicha)', 'c': True}, {'t': 'Data First Search', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'DFS qanday ishlaydi?', 'a': [{'t': 'Kenglikka boradi', 'c': False}, {'t': 'Chuqurlikka boradi', 'c': True}, {'t': 'Tasodifiy', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'DFS qaysi ma\'lumot tuzilmasidan foydalanadi?', 'a': [{'t': 'Queue', 'c': False}, {'t': 'Stack (yoki rekursiya)', 'c': True}, {'t': 'Array', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'DFS qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Topologik saralash, sikl topish, labirint', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat matnda', 'c': False}]},
        {'t': 'DFS murakkabligi?', 'a': [{'t': 'O(1)', 'c': False}, {'t': 'O(V + E)', 'c': True}, {'t': 'O(log n)', 'c': False}, {'t': 'O(n³)', 'c': False}]},
    ]},
    {'n': 'Dijkstra algoritmi', 't': 20, 'o': 56, 'q': [
        {'t': 'Dijkstra algoritmi nima?', 'a': [{'t': 'Saralash algoritmi', 'c': False}, {'t': 'Eng qisqa yo\'l algoritmi', 'c': True}, {'t': 'Qidiruv algoritmi', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Dijkstra qanday graphda ishlaydi?', 'a': [{'t': 'Faqat vaznsiz', 'c': False}, {'t': 'Musbat vaznli graphda', 'c': True}, {'t': 'Manfiy vaznli', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Dijkstra qaysi ma\'lumot tuzilmasidan foydalanadi?', 'a': [{'t': 'Stack', 'c': False}, {'t': 'Priority Queue', 'c': True}, {'t': 'Oddiy Queue', 'c': False}, {'t': 'Array', 'c': False}]},
        {'t': 'Dijkstra murakkabligi?', 'a': [{'t': 'O(n)', 'c': False}, {'t': 'O((V+E) log V)', 'c': True}, {'t': 'O(1)', 'c': False}, {'t': 'O(n³)', 'c': False}]},
        {'t': 'Dijkstra qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'GPS navigatsiya, tarmoq routing', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat matnda', 'c': False}]},
    ]},
    {'n': 'A* algoritmi', 't': 20, 'o': 57, 'q': [
        {'t': 'A* algoritmi nima?', 'a': [{'t': 'Oddiy qidiruv', 'c': False}, {'t': 'Heuristik yo\'l topish algoritmi', 'c': True}, {'t': 'Saralash algoritmi', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'A* Dijkstradan farqi?', 'a': [{'t': 'Hech qanday farq yo\'q', 'c': False}, {'t': 'Heuristik ishlatadi (tezroq)', 'c': True}, {'t': 'Sekinroq', 'c': False}, {'t': 'Faqat oddiyroq', 'c': False}]},
        {'t': 'A* formulasi?', 'a': [{'t': 'f = g', 'c': False}, {'t': 'f = g + h (haqiqiy + taxminiy)', 'c': True}, {'t': 'f = h', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'A* qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'O\'yinlar, robotlar, xaritalar', 'c': True}, {'t': 'Faqat matnda', 'c': False}, {'t': 'Faqat raqamlarda', 'c': False}]},
        {'t': 'A* optimal yechimni topadimi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha (admissible heuristic bilan)', 'c': True}, {'t': 'Faqat ba\'zan', 'c': False}, {'t': 'Hech qachon', 'c': False}]},
    ]},
    {'n': 'Bellman-Ford algoritmi', 't': 20, 'o': 58, 'q': [
        {'t': 'Bellman-Ford nima?', 'a': [{'t': 'Saralash algoritmi', 'c': False}, {'t': 'Eng qisqa yo\'l algoritmi', 'c': True}, {'t': 'Qidiruv algoritmi', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Bellman-Ford Dijkstradan farqi?', 'a': [{'t': 'Hech qanday farq yo\'q', 'c': False}, {'t': 'Manfiy vaznli qirralarni qo\'llab-quvvatlaydi', 'c': True}, {'t': 'Tezroq', 'c': False}, {'t': 'Faqat oddiyroq', 'c': False}]},
        {'t': 'Bellman-Ford murakkabligi?', 'a': [{'t': 'O(log n)', 'c': False}, {'t': 'O(VE)', 'c': True}, {'t': 'O(1)', 'c': False}, {'t': 'O(V log V)', 'c': False}]},
        {'t': 'Bellman-Ford manfiy siklni aniqlay oladimi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha', 'c': True}, {'t': 'Faqat ba\'zan', 'c': False}, {'t': 'Hech qachon', 'c': False}]},
        {'t': 'Bellman-Ford qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Tarmoq routing, valyuta arbitraji', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat matnda', 'c': False}]},
    ]},
    {'n': 'Floyd-Warshall algoritmi', 't': 20, 'o': 59, 'q': [
        {'t': 'Floyd-Warshall nima?', 'a': [{'t': 'Bitta manbadan yo\'l', 'c': False}, {'t': 'Barcha juftliklar eng qisqa yo\'li', 'c': True}, {'t': 'Saralash algoritmi', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Floyd-Warshall murakkabligi?', 'a': [{'t': 'O(V)', 'c': False}, {'t': 'O(V³)', 'c': True}, {'t': 'O(V²)', 'c': False}, {'t': 'O(VE)', 'c': False}]},
        {'t': 'Floyd-Warshall manfiy vaznlarni qo\'llab-quvvatlaydimi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha (manfiy sikl bo\'lmasa)', 'c': True}, {'t': 'Faqat musbat', 'c': False}, {'t': 'Hech qachon', 'c': False}]},
        {'t': 'Floyd-Warshall qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Kichik graphlar, barcha yo\'llar kerak', 'c': True}, {'t': 'Faqat katta graphlar', 'c': False}, {'t': 'Faqat o\'yinlarda', 'c': False}]},
        {'t': 'Floyd-Warshall DP algoritmimi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha', 'c': True}, {'t': 'Faqat greedy', 'c': False}, {'t': 'Faqat backtracking', 'c': False}]},
    ]},
    {'n': 'Topologik saralash', 't': 20, 'o': 60, 'q': [
        {'t': 'Topologik saralash nima?', 'a': [{'t': 'Oddiy saralash', 'c': False}, {'t': 'DAG tugunlarini chiziqli tartibda joylashtirish', 'c': True}, {'t': 'Faqat sonlarni saralash', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'DAG nima?', 'a': [{'t': 'Sikllik graph', 'c': False}, {'t': 'Directed Acyclic Graph (yo\'nalishli sikl yo\'q)', 'c': True}, {'t': 'Oddiy graph', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Topologik saralash qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Vazifalar tartibi, kurs prerequisite', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat matnda', 'c': False}]},
        {'t': 'Topologik saralash qanday amalga oshiriladi?', 'a': [{'t': 'Faqat BFS', 'c': False}, {'t': 'DFS yoki Kahn algoritmi', 'c': True}, {'t': 'Faqat Dijkstra', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Sikllik graphda topologik saralash mumkinmi?', 'a': [{'t': 'Ha', 'c': False}, {'t': 'Yo\'q', 'c': True}, {'t': 'Faqat ba\'zan', 'c': False}, {'t': 'Doim', 'c': False}]},
    ]},
    {'n': 'Minimum Spanning Tree', 't': 20, 'o': 61, 'q': [
        {'t': 'MST nima?', 'a': [{'t': 'Maksimum tree', 'c': False}, {'t': 'Minimum Spanning Tree (eng kichik vaznli tree)', 'c': True}, {'t': 'Oddiy tree', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Kruskal algoritmi nima?', 'a': [{'t': 'Qidiruv algoritmi', 'c': False}, {'t': 'MST topish algoritmi', 'c': True}, {'t': 'Saralash algoritmi', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Prim algoritmi nima?', 'a': [{'t': 'Qidiruv algoritmi', 'c': False}, {'t': 'MST topish algoritmi', 'c': True}, {'t': 'Saralash algoritmi', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'MST qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Tarmoq dizayni, klasterlash', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat matnda', 'c': False}]},
        {'t': 'Kruskal qaysi strategiya?', 'a': [{'t': 'DP', 'c': False}, {'t': 'Greedy', 'c': True}, {'t': 'Backtracking', 'c': False}, {'t': 'Divide and Conquer', 'c': False}]},
    ]},
    {'n': 'Union-Find ma\'lumot tuzilmasi', 't': 20, 'o': 62, 'q': [
        {'t': 'Union-Find nima?', 'a': [{'t': 'Oddiy array', 'c': False}, {'t': 'Disjoint Set ma\'lumot tuzilmasi', 'c': True}, {'t': 'Faqat tree', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Find operatsiyasi nima qiladi?', 'a': [{'t': 'Element qo\'shadi', 'c': False}, {'t': 'Elementning to\'plamini topadi', 'c': True}, {'t': 'Element o\'chiradi', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'Union operatsiyasi nima qiladi?', 'a': [{'t': 'To\'plamni ajratadi', 'c': False}, {'t': 'Ikki to\'plamni birlashtirad', 'c': True}, {'t': 'Element topadi', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'Union-Find qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Kruskal algoritmi, sikl aniqlash', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat matnda', 'c': False}]},
        {'t': 'Path compression nima?', 'a': [{'t': 'Hech narsa', 'c': False}, {'t': 'Union-Find optimizatsiyasi', 'c': True}, {'t': 'Saralash usuli', 'c': False}, {'t': 'Qidiruv usuli', 'c': False}]},
    ]},
    {'n': 'Bit manipulyatsiya', 't': 20, 'o': 63, 'q': [
        {'t': 'Bit nima?', 'a': [{'t': 'Bayt', 'c': False}, {'t': '0 yoki 1', 'c': True}, {'t': 'Raqam', 'c': False}, {'t': 'Harf', 'c': False}]},
        {'t': 'AND operatori (&) nima qiladi?', 'a': [{'t': 'Yoki', 'c': False}, {'t': 'Ikkalasi ham 1 bo\'lsa 1', 'c': True}, {'t': 'Biri 1 bo\'lsa 1', 'c': False}, {'t': 'Inkor', 'c': False}]},
        {'t': 'OR operatori (|) nima qiladi?', 'a': [{'t': 'Ikkalasi ham 1', 'c': False}, {'t': 'Biri 1 bo\'lsa 1', 'c': True}, {'t': 'Inkor', 'c': False}, {'t': 'XOR', 'c': False}]},
        {'t': 'XOR operatori (^) nima qiladi?', 'a': [{'t': 'Ikkalasi ham 1', 'c': False}, {'t': 'Farqli bo\'lsa 1', 'c': True}, {'t': 'Bir xil bo\'lsa 1', 'c': False}, {'t': 'Inkor', 'c': False}]},
        {'t': 'Bit manipulyatsiya qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Optimizatsiya, kriptografiya, grafika', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat matnda', 'c': False}]},
    ]},
    {'n': 'String algoritmlari', 't': 20, 'o': 64, 'q': [
        {'t': 'Pattern matching nima?', 'a': [{'t': 'Faqat saralash', 'c': False}, {'t': 'Matnda naqsh qidirish', 'c': True}, {'t': 'Faqat hisoblash', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'KMP algoritmi nima?', 'a': [{'t': 'Saralash algoritmi', 'c': False}, {'t': 'Knuth-Morris-Pratt (string qidiruv)', 'c': True}, {'t': 'Qidiruv algoritmi', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Rabin-Karp algoritmi nima?', 'a': [{'t': 'Saralash', 'c': False}, {'t': 'Hash asosida string qidiruv', 'c': True}, {'t': 'Faqat hisoblash', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Longest Common Subsequence nima?', 'a': [{'t': 'Eng qisqa', 'c': False}, {'t': 'Eng uzun umumiy ketma-ketlik', 'c': True}, {'t': 'Faqat birinchi', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'String algoritmlari qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Matn muharrirlari, DNA tahlili, plagiat aniqlash', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat raqamlarda', 'c': False}]},
    ]},
    {'n': 'Regex (Regular Expressions)', 't': 20, 'o': 65, 'q': [
        {'t': 'Regex nima?', 'a': [{'t': 'Dasturlash tili', 'c': False}, {'t': 'Matn naqshlarini qidirish tili', 'c': True}, {'t': 'Operatsion tizim', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': '. belgisi regex da nima?', 'a': [{'t': 'Faqat nuqta', 'c': False}, {'t': 'Har qanday bitta belgi', 'c': True}, {'t': 'Faqat harf', 'c': False}, {'t': 'Faqat raqam', 'c': False}]},
        {'t': '* belgisi regex da nima?', 'a': [{'t': 'Faqat bitta', 'c': False}, {'t': '0 yoki ko\'p marta', 'c': True}, {'t': 'Faqat bir marta', 'c': False}, {'t': 'Hech qachon', 'c': False}]},
        {'t': '+ belgisi regex da nima?', 'a': [{'t': '0 yoki ko\'p', 'c': False}, {'t': '1 yoki ko\'p marta', 'c': True}, {'t': 'Faqat bir marta', 'c': False}, {'t': 'Hech qachon', 'c': False}]},
        {'t': 'Regex qayerda ishlatiladi?', 'a': [{'t': 'Hech qayerda', 'c': False}, {'t': 'Validatsiya, qidiruv, matn qayta ishlash', 'c': True}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat raqamlarda', 'c': False}]},
    ]},
    {'n': 'Kompilatorlar asoslari', 't': 20, 'o': 66, 'q': [
        {'t': 'Kompilyator nima?', 'a': [{'t': 'Faqat dastur', 'c': False}, {'t': 'Yuqori darajali tilni mashina tiliga o\'giruvchi', 'c': True}, {'t': 'Faqat interpretator', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Interpretator nima?', 'a': [{'t': 'Faqat kompilyator', 'c': False}, {'t': 'Kodni qator-qator bajaruvchi', 'c': True}, {'t': 'Faqat tarjimon', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Leksik tahlil nima?', 'a': [{'t': 'Faqat sintaksis', 'c': False}, {'t': 'Kodni tokenlarga ajratish', 'c': True}, {'t': 'Faqat semantika', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Sintaksis tahlil nima?', 'a': [{'t': 'Faqat leksika', 'c': False}, {'t': 'Grammatika to\'g\'riligini tekshirish', 'c': True}, {'t': 'Faqat semantika', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Semantik tahlil nima?', 'a': [{'t': 'Faqat sintaksis', 'c': False}, {'t': 'Ma\'no to\'g\'riligini tekshirish', 'c': True}, {'t': 'Faqat leksika', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
    ]},
    {'n': 'Parallel dasturlash', 't': 20, 'o': 67, 'q': [
        {'t': 'Parallel dasturlash nima?', 'a': [{'t': 'Ketma-ket bajarish', 'c': False}, {'t': 'Bir vaqtda ko\'p vazifalarni bajarish', 'c': True}, {'t': 'Faqat bitta vazifa', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Thread nima?', 'a': [{'t': 'Faqat jarayon', 'c': False}, {'t': 'Yengil bajarilish oqimi', 'c': True}, {'t': 'Faqat dastur', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Process nima?', 'a': [{'t': 'Faqat thread', 'c': False}, {'t': 'Mustaqil bajarilayotgan dastur', 'c': True}, {'t': 'Faqat funksiya', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Race condition nima?', 'a': [{'t': 'Hech qanday muammo yo\'q', 'c': False}, {'t': 'Ko\'p threadlar bir resursga murojaat qilishi', 'c': True}, {'t': 'Faqat tezlik', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Mutex nima?', 'a': [{'t': 'Faqat thread', 'c': False}, {'t': 'Mutual Exclusion (qulflash mexanizmi)', 'c': True}, {'t': 'Faqat jarayon', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
    ]},
    {'n': 'Konkurrent dasturlash', 't': 20, 'o': 68, 'q': [
        {'t': 'Concurrency nima?', 'a': [{'t': 'Faqat parallel', 'c': False}, {'t': 'Ko\'p vazifalarni boshqarish', 'c': True}, {'t': 'Faqat ketma-ket', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Parallelism va Concurrency farqi?', 'a': [{'t': 'Bir xil', 'c': False}, {'t': 'Parallelism - bir vaqtda, Concurrency - boshqarish', 'c': True}, {'t': 'Hech qanday farq yo\'q', 'c': False}, {'t': 'Faqat nom', 'c': False}]},
        {'t': 'Deadlock nima?', 'a': [{'t': 'Hech qanday muammo yo\'q', 'c': False}, {'t': 'Threadlar bir-birini kutib qolishi', 'c': True}, {'t': 'Faqat tezlik', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Semaphore nima?', 'a': [{'t': 'Faqat mutex', 'c': False}, {'t': 'Resursga kirish nazorati', 'c': True}, {'t': 'Faqat thread', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Async/Await nima?', 'a': [{'t': 'Faqat sinxron', 'c': False}, {'t': 'Asinxron dasturlash sintaksisi', 'c': True}, {'t': 'Faqat parallel', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
    ]},
    {'n': 'Mikroservislar arxitekturasi', 't': 20, 'o': 69, 'q': [
        {'t': 'Mikroservis nima?', 'a': [{'t': 'Katta monolit', 'c': False}, {'t': 'Kichik mustaqil xizmat', 'c': True}, {'t': 'Faqat API', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Monolit arxitektura nima?', 'a': [{'t': 'Ko\'p kichik xizmatlar', 'c': False}, {'t': 'Bitta katta dastur', 'c': True}, {'t': 'Faqat mikroservis', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Mikroservislar afzalligi?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Mustaqil deploy, miqyoslash, texnologiya tanlash', 'c': True}, {'t': 'Faqat oddiy', 'c': False}, {'t': 'Faqat kichik', 'c': False}]},
        {'t': 'Mikroservislar kamchiligi?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Murakkab boshqarish, tarmoq overhead', 'c': True}, {'t': 'Faqat oddiy', 'c': False}, {'t': 'Faqat kichik', 'c': False}]},
        {'t': 'Docker nima?', 'a': [{'t': 'Dasturlash tili', 'c': False}, {'t': 'Konteynerizatsiya platformasi', 'c': True}, {'t': 'Operatsion tizim', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
    ]},
    {'n': 'DevOps asoslari', 't': 20, 'o': 70, 'q': [
        {'t': 'DevOps nima?', 'a': [{'t': 'Faqat dasturlash', 'c': False}, {'t': 'Development + Operations (hamkorlik)', 'c': True}, {'t': 'Faqat operatsiya', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'CI/CD nima?', 'a': [{'t': 'Faqat dasturlash', 'c': False}, {'t': 'Continuous Integration/Deployment', 'c': True}, {'t': 'Faqat test', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Jenkins nima?', 'a': [{'t': 'Dasturlash tili', 'c': False}, {'t': 'CI/CD vositasi', 'c': True}, {'t': 'Operatsion tizim', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Kubernetes nima?', 'a': [{'t': 'Dasturlash tili', 'c': False}, {'t': 'Konteyner orkestrlash platformasi', 'c': True}, {'t': 'Operatsion tizim', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Infrastructure as Code nima?', 'a': [{'t': 'Faqat qo\'lda', 'c': False}, {'t': 'Infratuzilmani kod orqali boshqarish', 'c': True}, {'t': 'Faqat GUI', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
    ]},
]

if __name__ == '__main__':
    subj = get_or_create_informatics()
    add_topics(subj, T)
    print(f"\n✅ Jami {len(T)} ta mavzu qo\'shildi!")
