# Generated by Django 5.2.8 on 2025-12-01 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sertifikat nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CertificateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cert_questions/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Sertifikat savoli',
                'verbose_name_plural': 'Sertifikat savollari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Test nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('time_limit', models.PositiveIntegerField(default=30, verbose_name='Vaqt limiti (daqiqa)')),
                ('passing_score', models.PositiveIntegerField(default=60, verbose_name="O'tish balli (%)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sertifikat testi',
                'verbose_name_plural': 'Sertifikat testlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('institution_type', models.CharField(choices=[('training', "O'quv markazi"), ('state_school', 'Davlat maktabi'), ('private_school', 'Xususiy maktab'), ('state_uni', "Davlat oliy ta'lim"), ('foreign_branch', 'Xorijiy filial'), ('private_uni', "Xususiy oliy ta'lim")], max_length=20, verbose_name='Turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutions/', verbose_name='Logo')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Reklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Ta'lim muassasasi",
                'verbose_name_plural': "Ta'lim muassasalari",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Imtihon nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mock_exams/', verbose_name='Rasm')),
                ('time_limit', models.PositiveIntegerField(default=120, verbose_name='Vaqt limiti (daqiqa)')),
                ('passing_score', models.PositiveIntegerField(default=60, verbose_name="O'tish balli (%)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mock imtihon',
                'verbose_name_plural': 'Mock imtihonlar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='EduSelf', max_length=100)),
                ('site_description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('about_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('value', models.CharField(max_length=50, verbose_name='Qiymat')),
                ('icon', models.CharField(default='bi-graph-up', max_length=50, verbose_name='Icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fan nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('icon', models.CharField(default='bi-book', max_length=50, verbose_name='Icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subjects/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Test nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('time_limit', models.PositiveIntegerField(default=30, verbose_name='Vaqt limiti (daqiqa)')),
                ('passing_score', models.PositiveIntegerField(default=60, verbose_name="O'tish balli (%)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Javob matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_answers', to='core.certificatequestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Sertifikat javobi',
                'verbose_name_plural': 'Sertifikat javoblari',
            },
        ),
        migrations.CreateModel(
            name='CertificateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('time_taken', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_results', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_results', to='core.certificatetest')),
            ],
            options={
                'verbose_name': 'Sertifikat natijasi',
                'verbose_name_plural': 'Sertifikat natijalari',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddField(
            model_name='certificatequestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_questions', to='core.certificatetest', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='CertificateTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mavzu nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_topics', to='core.certificate', verbose_name='Sertifikat')),
            ],
            options={
                'verbose_name': 'Sertifikat mavzusi',
                'verbose_name_plural': 'Sertifikat mavzulari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='certificatetest',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_tests', to='core.certificatetopic', verbose_name='Mavzu'),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='Rasm')),
                ('link', models.URLField(blank=True, verbose_name='Havola')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.institution', verbose_name="Ta'lim muassasasi")),
            ],
            options={
                'verbose_name': 'Reklama',
                'verbose_name_plural': 'Reklamalar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mock_questions/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_questions', to='core.mockexam', verbose_name='Imtihon')),
            ],
            options={
                'verbose_name': 'Mock savol',
                'verbose_name_plural': 'Mock savollar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MockExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Javob matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_answers', to='core.mockexamquestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Mock javob',
                'verbose_name_plural': 'Mock javoblar',
            },
        ),
        migrations.CreateModel(
            name='MockExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('time_taken', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_results', to='core.mockexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mock natija',
                'verbose_name_plural': 'Mock natijalar',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Javob matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.test', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('time_taken', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mavzu nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.topic', verbose_name='Mavzu'),
        ),
    ]
