# Generated by Django 6.0 on 2025-12-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_answers_to_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='user_answers',
            field=models.JSONField(blank=True, default=dict, verbose_name='Foydalanuvchi javoblari'),
        ),
    ]
