# Generated by Django 6.0 on 2025-12-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testresult_user_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(choices=[('training', "O'quv markazi"), ('state_school', 'Davlat maktabi'), ('private_school', 'Xususiy maktab'), ('state_uni', "Davlat oliy ta'lim"), ('foreign_branch', 'Xorijiy filial'), ('private_uni', "Xususiy oliy ta'lim"), ('consulting', 'Konsalting')], max_length=20, verbose_name='Turi'),
        ),
    ]
