# Generated by Django 6.0 on 2025-12-06 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_coursecategory_course_lesson_courseenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('news', 'Yangilik'), ('test', 'Yangi test'), ('certificate', 'Yangi sertifikat'), ('mock_exam', 'Yangi mock exam'), ('course', 'Yangi kurs'), ('system', 'Tizim xabari')], max_length=20, verbose_name='Turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Havola')),
                ('icon', models.CharField(default='bi-bell', max_length=50, verbose_name='Icon')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('is_global', models.BooleanField(default=False, verbose_name='Barcha foydalanuvchilar uchun')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
