# Generated by Django 5.2.8 on 2025-12-11 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mockexamcategory_mockexam_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('icon', models.CharField(default='bi-building', max_length=50, verbose_name='Icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='institution_categories/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Muassasa kategoriyasi',
                'verbose_name_plural': 'Muassasa kategoriyalari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='institution',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='core.institutioncategory', verbose_name='Kategoriya'),
        ),
    ]
