# Generated by Django 5.2.8 on 2025-12-12 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_subjectcategory_subject_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='logo',
        ),
        migrations.AddField(
            model_name='institution',
            name='address_iframe',
            field=models.TextField(blank=True, verbose_name='Manzil iframe kodi'),
        ),
        migrations.AddField(
            model_name='institution',
            name='contract_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kontrakt summasi (max)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='contract_price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kontrakt summasi (min)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/', verbose_name='Asosiy rasm'),
        ),
        migrations.AddField(
            model_name='institution',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Qisqa tavsif'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, verbose_name="To'liq tavsif"),
        ),
        migrations.CreateModel(
            name='InstitutionDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name="Yo'nalish nomi")),
                ('description', models.TextField(blank=True, verbose_name="Yo'nalish tavsifi")),
                ('contract_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kontrakt summasi (min)')),
                ('contract_price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kontrakt summasi (max)')),
                ('exam_url', models.URLField(blank=True, verbose_name='Imtihon URL manzili')),
                ('website_url', models.URLField(blank=True, verbose_name="Yo'nalish veb-sayti")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='core.institution', verbose_name='Muassasa')),
            ],
            options={
                'verbose_name': "Muassasa yo'nalishi",
                'verbose_name_plural': "Muassasa yo'nalishlari",
                'ordering': ['order', 'name'],
            },
        ),
    ]
