# Generated by Django 5.2.8 on 2025-12-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_institution_logo_institution_address_iframe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutiondirection',
            name='contract_price_max',
        ),
        migrations.RemoveField(
            model_name='institutiondirection',
            name='contract_price_min',
        ),
        migrations.RemoveField(
            model_name='institutiondirection',
            name='website_url',
        ),
        migrations.AddField(
            model_name='institutiondirection',
            name='contract_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kontrakt summasi'),
        ),
    ]
