# Generated by Django 5.2.8 on 2025-12-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_institutiondirection_contract_price_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='admission_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qabul tugash sanasi'),
        ),
        migrations.AddField(
            model_name='institution',
            name='admission_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qabul boshlanish sanasi'),
        ),
        migrations.AddField(
            model_name='institution',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='institutions/licenses/', verbose_name='Litsenziya fayli'),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='institution',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Video URL (YouTube)'),
        ),
        migrations.AddField(
            model_name='institutiondirection',
            name='education_form',
            field=models.CharField(choices=[('full_time', 'Kunduzgi'), ('part_time', 'Sirtqi'), ('evening', 'Kechki'), ('distance', 'Masofaviy')], default='full_time', max_length=20, verbose_name="Ta'lim shakli"),
        ),
        migrations.AddField(
            model_name='institutiondirection',
            name='education_language',
            field=models.CharField(choices=[('uzbek', "O'zbek tili"), ('russian', 'Rus tili'), ('english', 'Ingliz tili'), ('mixed', 'Aralash')], default='uzbek', max_length=20, verbose_name="Ta'lim tili"),
        ),
        migrations.AddField(
            model_name='institutiondirection',
            name='passing_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="O'tish bali"),
        ),
    ]
