# Generated by Django 5.2.8 on 2025-12-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_institution_admission_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='payment_url',
            field=models.URLField(blank=True, verbose_name="To'lov URL manzili"),
        ),
    ]
