# Generated by Django 5.2.8 on 2025-12-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_course_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='payment_confirmed',
            field=models.BooleanField(default=False, verbose_name="To'lov tasdiqlangan"),
        ),
    ]
