# Generated by Django 5.2.8 on 2025-12-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_points_to_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='earned_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Olingan ball'),
        ),
    ]
