# Generated by Django 5.2.8 on 2025-12-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_earned_points_to_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='link_url',
            field=models.URLField(blank=True, null=True, verbose_name='Havola URL'),
        ),
    ]
