# Generated by Django 5.2.8 on 2025-12-15 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_link_url_to_advertisement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatetopic',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Sertifikat fani', 'verbose_name_plural': 'Sertifikat fanlari'},
        ),
        migrations.AlterField(
            model_name='certificatetest',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_tests', to='core.certificatetopic', verbose_name='Fan'),
        ),
        migrations.AlterField(
            model_name='certificatetopic',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Fan nomi'),
        ),
    ]
