# Generated by Django 5.2.8 on 2025-12-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_certificatetopic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatequestion',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='Ball'),
        ),
        migrations.AddField(
            model_name='certificateresult',
            name='earned_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Olingan ball'),
        ),
        migrations.AddField(
            model_name='mockexamquestion',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='Ball'),
        ),
        migrations.AddField(
            model_name='mockexamresult',
            name='earned_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Olingan ball'),
        ),
    ]
