# Generated by Django 5.2.8 on 2025-12-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_certificatequestion_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatetest',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Sertifikat testi', 'verbose_name_plural': 'Sertifikat testlari'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Test', 'verbose_name_plural': 'Testlar'},
        ),
        migrations.AddField(
            model_name='certificatetest',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='certificatetest',
            name='unlock_score',
            field=models.PositiveIntegerField(default=60, verbose_name='Ochish uchun kerakli ball (%)'),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='unlock_score',
            field=models.PositiveIntegerField(default=60, verbose_name='Ochish uchun kerakli ball (%)'),
        ),
        migrations.AddField(
            model_name='test',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='test',
            name='unlock_score',
            field=models.PositiveIntegerField(default=60, verbose_name='Ochish uchun kerakli ball (%)'),
        ),
    ]
