# Generated by Django 5.2.8 on 2025-12-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_certificatetest_options_alter_test_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Video URL (YouTube)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Video URL (YouTube, Vimeo)'),
        ),
    ]
