# Generated by Django 5.2.8 on 2025-12-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_institution_video_url_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='instagram',
            field=models.URLField(blank=True, max_length=300, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='institution',
            name='telegram',
            field=models.URLField(blank=True, max_length=300, verbose_name='Telegram'),
        ),
    ]
