# Generated by Django 5.2.8 on 2025-12-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_institution_video_url_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateresult',
            name='earned_points',
            field=models.FloatField(default=0, verbose_name='Olingan ball'),
        ),
        migrations.AlterField(
            model_name='certificateresult',
            name='score',
            field=models.FloatField(default=0, verbose_name='Ball (%)'),
        ),
        migrations.AlterField(
            model_name='mockexamresult',
            name='earned_points',
            field=models.FloatField(default=0, verbose_name='Olingan ball'),
        ),
        migrations.AlterField(
            model_name='mockexamresult',
            name='score',
            field=models.FloatField(default=0, verbose_name='Ball (%)'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='earned_points',
            field=models.FloatField(default=0, verbose_name='Olingan ball'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.FloatField(default=0, verbose_name='Ball (%)'),
        ),
    ]
