# Generated by Django 5.2.8 on 2025-12-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_institution_instagram_institution_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='facebook',
            field=models.URLField(blank=True, max_length=300, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='institution',
            name='youtube',
            field=models.URLField(blank=True, max_length=300, verbose_name='YouTube'),
        ),
    ]
