# Generated by Django 5.2.8 on 2025-12-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_certificateresult_earned_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatequestion',
            name='points',
            field=models.FloatField(default=1.0, verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='mockexamquestion',
            name='points',
            field=models.FloatField(default=1.0, verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.FloatField(default=1.0, verbose_name='Ball'),
        ),
    ]
