# Generated by Django 5.2.8 on 2025-12-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_certificatequestion_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatequestion',
            name='points',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='mockexamquestion',
            name='points',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='Ball'),
        ),
    ]
