# Generated by Django 5.2.8 on 2025-12-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_institution_facebook_institution_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatequestion',
            name='points',
            field=models.FloatField(default=1.0, verbose_name='Ball'),
        ),
    ]
