# Generated by Django 5.2.8 on 2025-12-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_certificate_question_float_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatequestion',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='mockexamquestion',
            name='points',
            field=models.FloatField(default=1.0, verbose_name='Ball'),
        ),
    ]
