# Generated by Django 5.2.8 on 2025-12-18 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_certificatequestion_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Qiyinlik nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('color', models.CharField(default='#6366f1', max_length=20, verbose_name='Rang (HEX)')),
                ('bg_color', models.CharField(default='rgba(99, 102, 241, 0.1)', max_length=20, verbose_name='Fon rangi')),
                ('icon', models.CharField(default='fas fa-signal', max_length=50, verbose_name='Icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Qiyinlik darajasi',
                'verbose_name_plural': 'Qiyinlik darajalari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='core.difficultylevel', verbose_name='Qiyinlik darajasi'),
        ),
    ]
