# Generated by Django 5.2.8 on 2025-12-20 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_difficultylevel_test_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Imtihon nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('subjects', models.CharField(max_length=500, verbose_name='Fanlar (vergul bilan ajratilgan)')),
                ('time_limit', models.PositiveIntegerField(default=120, verbose_name='Vaqt limiti (daqiqa)')),
                ('passing_score', models.FloatField(default=60.0, verbose_name="O'tish balli (%)")),
                ('application_url', models.URLField(blank=True, verbose_name='Ariza qoldirish URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.institutiondirection', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': "Yo'nalish imtihoni",
                'verbose_name_plural': "Yo'nalish imtihonlari",
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectionExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='direction_questions/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('points', models.FloatField(default=1.1, verbose_name='Ball')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_questions', to='core.directionexam', verbose_name='Imtihon')),
            ],
            options={
                'verbose_name': "Yo'nalish imtihon savoli",
                'verbose_name_plural': "Yo'nalish imtihon savollari",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DirectionExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Javob matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_answers', to='core.directionexamquestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': "Yo'nalish imtihon javobi",
                'verbose_name_plural': "Yo'nalish imtihon javoblari",
            },
        ),
        migrations.CreateModel(
            name='DirectionExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='Foiz (%)')),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('time_taken', models.PositiveIntegerField(default=0, verbose_name='Sarflangan vaqt (soniya)')),
                ('user_answers', models.JSONField(blank=True, default=dict, verbose_name='Foydalanuvchi javoblari')),
                ('earned_points', models.FloatField(default=0, verbose_name='Olingan ball')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_results', to='core.directionexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_exam_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Yo'nalish imtihon natijasi",
                'verbose_name_plural': "Yo'nalish imtihon natijalari",
                'ordering': ['-completed_at'],
            },
        ),
    ]
