# Generated by Django 5.2.8 on 2025-12-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_directionexam_directionexamquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutiondirection',
            name='exam_url',
        ),
    ]
