# Generated by Django 5.2.8 on 2025-12-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_exam_url_from_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatequestion',
            name='long_text',
            field=models.TextField(blank=True, help_text="Hikoya, she'r yoki uzun matn (ixtiyoriy)", null=True, verbose_name='Uzun matn'),
        ),
        migrations.AddField(
            model_name='directionexamquestion',
            name='long_text',
            field=models.TextField(blank=True, help_text="Hikoya, she'r yoki uzun matn (ixtiyoriy)", null=True, verbose_name='Uzun matn'),
        ),
        migrations.AddField(
            model_name='mockexamquestion',
            name='long_text',
            field=models.TextField(blank=True, help_text="Hikoya, she'r yoki uzun matn (ixtiyoriy)", null=True, verbose_name='Uzun matn'),
        ),
        migrations.AddField(
            model_name='question',
            name='long_text',
            field=models.TextField(blank=True, help_text="Hikoya, she'r yoki uzun matn (ixtiyoriy)", null=True, verbose_name='Uzun matn'),
        ),
        migrations.AlterField(
            model_name='directionexam',
            name='passing_score',
            field=models.FloatField(default=60.0, verbose_name="O'tish balli (ball)"),
        ),
    ]
