# Generated by Django 5.2.8 on 2025-12-29 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_long_text_to_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.topic', verbose_name='Mavzu'),
        ),
        migrations.AddField(
            model_name='topic',
            name='passing_score',
            field=models.PositiveIntegerField(default=60, verbose_name="O'tish balli (%)"),
        ),
        migrations.AddField(
            model_name='topic',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, verbose_name='Vaqt limiti (daqiqa)'),
        ),
        migrations.CreateModel(
            name='TopicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('time_taken', models.PositiveIntegerField(default=0)),
                ('user_answers', models.JSONField(blank=True, default=dict, verbose_name='Foydalanuvchi javoblari')),
                ('earned_points', models.PositiveIntegerField(default=0, verbose_name='Olingan ball')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mavzu natijasi',
                'verbose_name_plural': 'Mavzu natijalari',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
