# Generated by Django 5.2.8 on 2026-01-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_notificationread'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answers/', verbose_name='Javob rasmi'),
        ),
        migrations.AddField(
            model_name='certificateanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cert_answers/', verbose_name='Javob rasmi'),
        ),
        migrations.AddField(
            model_name='directionexamanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='direction_answers/', verbose_name='Javob rasmi'),
        ),
        migrations.AddField(
            model_name='mockexamanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mock_answers/', verbose_name='Javob rasmi'),
        ),
    ]
