# Generated by Django 5.2.8 on 2026-01-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_answer_image_certificateanswer_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Hamkor nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Logo')),
                ('website_url', models.URLField(blank=True, verbose_name='Veb-sayt havolasi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['order', 'name'],
            },
        ),
    ]
