# Generated by Django 5.1.5 on 2026-02-20 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='practice_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_lessons', to='core.topic', verbose_name='Amaliy mashq (Mavzu)'),
        ),
    ]
