# Generated by Django 5.1.5 on 2026-02-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_lesson_practice_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='external_link',
            field=models.URLField(blank=True, help_text="Yangilik uchun qo'shimcha havola (masalan: telegram kanal, website)", max_length=500, null=True, verbose_name='Tashqi havola'),
        ),
        migrations.AddField(
            model_name='news',
            name='external_link_text',
            field=models.CharField(blank=True, help_text="Havola tugmasida ko'rsatiladigan matn", max_length=100, null=True, verbose_name='Havola matni'),
        ),
    ]
