# Generated by Django 5.1.5 on 2026-02-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_news_external_link_news_external_link_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_hash', models.CharField(db_index=True, max_length=32, verbose_name='Matn hash')),
                ('source_lang', models.CharField(db_index=True, max_length=10, verbose_name='Manba til')),
                ('target_lang', models.CharField(db_index=True, max_length=10, verbose_name='Maqsad til')),
                ('original_text', models.TextField(verbose_name='Original matn')),
                ('translated_text', models.TextField(verbose_name='Tarjima qilingan matn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan soni')),
            ],
            options={
                'verbose_name': 'Tarjima cache',
                'verbose_name_plural': "Tarjima cache'lari",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['text_hash', 'source_lang', 'target_lang'], name='core_transl_text_ha_b24b19_idx')],
                'unique_together': {('text_hash', 'source_lang', 'target_lang')},
            },
        ),
    ]
