# Generated by Django 5.1.5 on 2026-02-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_translationcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='application_url',
            field=models.URLField(blank=True, verbose_name='Ariza qoldirish havolasi'),
        ),
    ]
