# Generated by Django 5.2.8 on 2025-12-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
