# Generated by Django 5.2.8 on 2025-12-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Umumiy XP'),
        ),
    ]
