# Generated by Django 5.2.8 on 2025-12-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_phone_alter_user_bio_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='user_certificates/', verbose_name='Sertifikat fayli'),
        ),
    ]
