# Generated by Django 5.2.8 on 2026-01-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_telegramlogintoken'),
    ]

    operations = [
    ]
