# Generated by Django 5.2.8 on 2026-01-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_expires_at_to_telegram_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
