# Generated by Django 5.1.5 on 2026-02-21 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_phone_verified_user_telegram_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP manzil')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='Qurilma turi')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Brauzer')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Operatsion tizim')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Joylashuv')),
                ('is_new_device', models.BooleanField(default=False, verbose_name='Yangi qurilma')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Kirish vaqti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kirish tarixi',
                'verbose_name_plural': 'Kirish tarixi',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', '-login_time'], name='accounts_lo_user_id_088230_idx'), models.Index(fields=['ip_address'], name='accounts_lo_ip_addr_142937_idx')],
            },
        ),
    ]
