# Generated by Django 5.1.5 on 2026-02-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('en', 'English'), ('ru', 'Русский'), ('kk', 'Қазақша'), ('kaa', 'Qaraqalpaqsha'), ('tg', 'Тоҷикӣ'), ('ky', 'Кыргызча')], default='uz', max_length=10, verbose_name='Til'),
        ),
    ]
