# Generated by Django 5.1.5 on 2026-02-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Avatar raqami'),
        ),
    ]
