# Generated by Django 5.2.8 on 2026-02-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_avatar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_date',
            field=models.DateField(blank=True, null=True, verbose_name='Oxirgi faol kun'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Kunlik streak'),
        ),
    ]
