# Generated by Django 5.2.8 on 2026-02-26 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_last_active_date_user_level_user_streak_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Level nomi')),
                ('level_number', models.PositiveIntegerField(unique=True, verbose_name='Level raqami')),
                ('required_xp', models.PositiveIntegerField(verbose_name='Kerakli XP')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='levels/', verbose_name='Level ikonkasi')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Rang (hex)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levellar',
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Badge nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('badge_type', models.CharField(choices=[('level', 'Level Badge'), ('streak', 'Streak Badge'), ('achievement', 'Achievement Badge'), ('special', 'Special Badge')], default='achievement', max_length=20, verbose_name='Badge turi')),
                ('image', models.ImageField(upload_to='badges/', verbose_name='Badge rasmi')),
                ('required_streak_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kerakli streak kunlari')),
                ('required_xp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kerakli XP')),
                ('required_tests_passed', models.PositiveIntegerField(blank=True, null=True, verbose_name="Kerakli o'tgan testlar")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.level', verbose_name='Kerakli level')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': "Badge'lar",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Ochilgan vaqt')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Foydalanuvchi Badge'i",
                'verbose_name_plural': "Foydalanuvchi Badge'lari",
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
