# Generated by Django 5.2.8 on 2026-02-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_level_badge_userbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='badges/', verbose_name='Badge rasmi'),
        ),
    ]
