# Generated by Django 5.2.8 on 2026-02-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_badge_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_lives', models.PositiveIntegerField(default=5, verbose_name='Kunlik yurakchalar soni')),
                ('max_lives', models.PositiveIntegerField(default=5, verbose_name='Maksimal yurakchalar')),
                ('refill_time_minutes', models.PositiveIntegerField(default=30, verbose_name='Tiklanish vaqti (daqiqa)')),
                ('lives_cost_on_fail', models.PositiveIntegerField(default=1, verbose_name="Muvaffaqiyatsizlikda yo'qotish")),
                ('passing_score', models.PositiveIntegerField(default=70, verbose_name="O'tish foizi (%)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Lives tizimi faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lives sozlamalari',
                'verbose_name_plural': 'Lives sozlamalari',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='current_lives',
            field=models.PositiveIntegerField(default=5, verbose_name='Hozirgi yurakchalar'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_daily_reset',
            field=models.DateField(blank=True, null=True, verbose_name='Oxirgi kunlik reset'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_life_lost_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Oxirgi yurakcha yo'qotilgan vaqt"),
        ),
    ]
