# Generated by Django 5.2.8 on 2026-03-06 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_livessettings_user_current_lives_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterestPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('abiturient', 'Abiturient'), ('student', 'Talaba'), ('teacher', "O'qituvchi"), ('other', 'Boshqa')], max_length=20, verbose_name='Rol')),
                ('selected_categories', models.JSONField(blank=True, default=dict, help_text="Format: {'subjects': [ids], 'certificates': [ids], 'courses': [ids], 'mock_exams': [ids]}", verbose_name='Tanlangan kategoriyalar')),
                ('onboarding_completed', models.BooleanField(default=False, verbose_name='Onboarding tugallangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interest_preference', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi qiziqishi',
                'verbose_name_plural': 'Foydalanuvchi qiziqishlari',
            },
        ),
    ]
