# Generated by Django 5.2.8 on 2026-03-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userinterestpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterestpreference',
            name='source',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('tanishimdan', 'Tanishimdan'), ('google', 'Google'), ('youtube', 'YouTube'), ('boshqa', 'Boshqa')], max_length=20, verbose_name='Manba'),
        ),
    ]
