# Generated by Django 5.2.8 on 2026-03-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_userinterestpreference_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterestpreference',
            name='saved_categories',
            field=models.JSONField(blank=True, default=dict, help_text="Avvalgi tanlangan kategoriyalar (to'liq platformaga o'tganda saqlanadi)", verbose_name='Saqlangan kategoriyalar'),
        ),
        migrations.AlterField(
            model_name='userinterestpreference',
            name='source',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('tanishimdan', 'Tanishimdan'), ('boshqa', 'Boshqa')], max_length=20, verbose_name='Manba'),
        ),
    ]
