# Generated by Django 5.2.8 on 2025-12-13 19:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_courseenrollment_payment_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Shablon nomi')),
                ('category', models.CharField(choices=[('subject_help', "Fan bo'yicha yordam"), ('institution_advice', 'Muassasa tanlash'), ('certificate_guide', "Sertifikat yo'riqnomasi"), ('general', 'Umumiy')], max_length=50, verbose_name='Kategoriya')),
                ('prompt_text', models.TextField(verbose_name='Prompt matni')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Prompt shabloni',
                'verbose_name_plural': 'AI Prompt shablonlari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Suhbat nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat sessiyasi',
                'verbose_name_plural': 'Chat sessiyalari',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'Foydalanuvchi'), ('assistant', 'AI Hamroh'), ('system', 'Tizim')], default='user', max_length=10)),
                ('content', models.TextField(verbose_name='Xabar matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan tokenlar')),
                ('response_time', models.FloatField(default=0.0, verbose_name='Javob vaqti (soniya)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.chatsession')),
            ],
            options={
                'verbose_name': 'Chat xabari',
                'verbose_name_plural': 'Chat xabarlari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Qoida nomi')),
                ('criteria', models.JSONField(verbose_name='Tanlov mezonlari')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Ustuvorlik')),
                ('is_active', models.BooleanField(default=True)),
                ('recommended_institutions', models.ManyToManyField(to='core.institution', verbose_name='Tavsiya etiladigan muassasalar')),
            ],
            options={
                'verbose_name': 'Muassasa tavsiyasi',
                'verbose_name_plural': 'Muassasa tavsiylari',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200, verbose_name='Mavzu nomi')),
                ('content', models.TextField(verbose_name='Mazmun')),
                ('keywords', models.TextField(blank=True, verbose_name="Kalit so'zlar (vergul bilan ajratilgan)")),
                ('difficulty_level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], default='beginner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='core.subject')),
            ],
            options={
                'verbose_name': 'Fan bilimlar bazasi',
                'verbose_name_plural': 'Fan bilimlar bazasi',
                'ordering': ['subject', 'topic_name'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('sessions_created', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI ishlatish statistikasi',
                'verbose_name_plural': 'AI ishlatish statistikalari',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
