# Generated by Django 5.1.5 on 2026-02-28 10:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dastur nomi')),
                ('required_referrals', models.PositiveIntegerField(verbose_name='Kerakli taklif soni')),
                ('referral_deadline_days', models.PositiveIntegerField(verbose_name='Taklif muddati (kunlar)')),
                ('reward_duration_days', models.PositiveIntegerField(verbose_name='Mukofot muddati (kunlar)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referal dasturi',
                'verbose_name_plural': 'Referal dasturlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ta'rif nomi")),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narx (so'm)")),
                ('duration_days', models.PositiveIntegerField(verbose_name='Muddat (kunlar)')),
                ('unlimited_lives', models.BooleanField(default=False, verbose_name='Cheksiz yurakchalar')),
                ('ai_analysis_limit', models.IntegerField(default=-1, verbose_name='AI tahlil limiti (-1 = cheksiz)')),
                ('ai_companion_limit', models.IntegerField(default=-1, verbose_name='AI hamroh limiti (-1 = cheksiz)')),
                ('university_exam_limit', models.IntegerField(default=-1, verbose_name='Universitet imtihoni limiti (-1 = cheksiz)')),
                ('mock_exam_limit', models.IntegerField(default=-1, verbose_name='Mock exam limiti (-1 = cheksiz)')),
                ('certificate_test_limit', models.IntegerField(default=-1, verbose_name='Sertifikat test limiti (-1 = cheksiz)')),
                ('icon', models.CharField(default='bi-star', max_length=50, verbose_name='Icon')),
                ('color', models.CharField(default='#6366f1', max_length=20, verbose_name='Rang')),
                ('badge_text', models.CharField(blank=True, max_length=50, verbose_name='Badge matni')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Mashhur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Ta'rif",
                'verbose_name_plural': "Ta'riflar",
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summa')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('payment_method', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme')], max_length=20, verbose_name="To'lov usuli")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarilgan'), ('failed', 'Muvaffaqiyatsiz')], default='pending', max_length=20, verbose_name='Holat')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='Tranzaksiya ID')),
                ('payment_data', models.JSONField(blank=True, default=dict, verbose_name="To'lov ma'lumotlari")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donat',
                'verbose_name_plural': 'Donatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_count', models.PositiveIntegerField(default=0, verbose_name='Taklif soni')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlangan vaqt')),
                ('deadline', models.DateTimeField(verbose_name='Muddat')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Bajarilgan')),
                ('reward_given', models.BooleanField(default=False, verbose_name='Mukofot berilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.referralprogram', verbose_name='Dastur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referal jarayoni',
                'verbose_name_plural': 'Referal jarayonlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan', verbose_name="Ta'rif"),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Promokod')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Chegirma (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Chegirma (so'm)")),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Amal qilish boshlanishi')),
                ('valid_until', models.DateTimeField(verbose_name='Amal qilish tugashi')),
                ('max_uses', models.PositiveIntegerField(default=0, verbose_name='Maksimal foydalanish (0 = cheksiz)')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Hozirgi foydalanish')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan', verbose_name="Ta'rif")),
            ],
            options={
                'verbose_name': 'Promokod',
                'verbose_name_plural': 'Promokodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Bajarilgan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.referralprogram', verbose_name='Dastur')),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL, verbose_name='Taklif qilingan')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='Taklif qiluvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi referali',
                'verbose_name_plural': 'Foydalanuvchi referallari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateTimeField(verbose_name='Tugash sanasi')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=20, verbose_name='Holat')),
                ('is_trial', models.BooleanField(default=False, verbose_name='Sinov muddati')),
                ('acquired_via', models.CharField(default='payment', max_length=50, verbose_name='Qanday olingan')),
                ('ai_analysis_used', models.IntegerField(default=0, verbose_name='AI tahlil ishlatilgan')),
                ('ai_companion_used', models.IntegerField(default=0, verbose_name='AI hamroh ishlatilgan')),
                ('university_exam_used', models.IntegerField(default=0, verbose_name='Universitet imtihoni ishlatilgan')),
                ('mock_exam_used', models.IntegerField(default=0, verbose_name='Mock exam ishlatilgan')),
                ('certificate_test_used', models.IntegerField(default=0, verbose_name='Sertifikat test ishlatilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan', verbose_name="Ta'rif")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi obunasi',
                'verbose_name_plural': 'Foydalanuvchi obunalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('admin', 'Admin')], max_length=20, verbose_name="To'lov usuli")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summa')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chegirma summasi')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yakuniy summa')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Bajarilgan'), ('failed', 'Muvaffaqiyatsiz'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='Tranzaksiya ID')),
                ('payment_data', models.JSONField(blank=True, default=dict, verbose_name="To'lov ma'lumotlari")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.promocode', verbose_name='Promokod')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan', verbose_name="Ta'rif")),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.usersubscription')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
