"""
ASTRONOMIYA - 100 TA TO'LIQ MAVZU (har birida 5-10 test, to'g'ri javoblar har xil o'rinda)
"""
import os, django, sys
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'eduself.settings')
django.setup()
from core.models import Subject, SubjectCategory, Topic, Question, Answer

def get_or_create_astronomy():
    cat, _ = SubjectCategory.objects.get_or_create(slug='aniq-fanlar', defaults={'name': 'Aniq fanlar', 'icon': 'bi-calculator', 'order': 2, 'is_active': True})
    subj, _ = Subject.objects.get_or_create(name='Astronomiya', defaults={'category': cat, 'description': 'Astronomiya fani - koinot sirlari', 'icon': 'bi-stars', 'order': 5, 'is_active': True})
    return subj

def add_topics(subject, topics_data):
    for td in topics_data:
        topic, created = Topic.objects.get_or_create(subject=subject, name=td['n'], defaults={'time_limit': td['t'], 'passing_score': 60, 'order': td['o'], 'is_active': True})
        print(f"{'✅' if created else 'ℹ️'} §{td['o']}: {td['n']} ({len(td['q'])} test)")
        for i, qd in enumerate(td['q']):
            q, qc = Question.objects.get_or_create(topic=topic, text=qd['t'], defaults={'points': 10, 'order': i + 1})
            if qc:
                for ad in qd['a']:
                    Answer.objects.create(question=q, text=ad['t'], is_correct=ad['c'])

# 100 TA TO'LIQ MAVZU
T = [
    {'n': 'Astronomiya faniga kirish', 't': 25, 'o': 1, 'q': [
        {'t': 'Astronomiya nima?', 'a': [{'t': 'Faqat yulduzlarni o\'rganadi', 'c': False}, {'t': 'Koinot va osmon jismlarini o\'rganuvchi fan', 'c': True}, {'t': 'Faqat Quyoshni o\'rganadi', 'c': False}, {'t': 'Faqat Yerni o\'rganadi', 'c': False}]},
        {'t': 'Astronomiya so\'zi qaysi tildan kelib chiqqan?', 'a': [{'t': 'Lotin tilidan', 'c': False}, {'t': 'Arab tilidan', 'c': False}, {'t': 'Yunon tilidan (astron - yulduz, nomos - qonun)', 'c': True}, {'t': 'Ingliz tilidan', 'c': False}]},
        {'t': 'Qadimgi astronomiya qayerda rivojlangan?', 'a': [{'t': 'Misr, Bobil, Xitoy, Hindiston', 'c': True}, {'t': 'Faqat Yevropa', 'c': False}, {'t': 'Faqat Amerika', 'c': False}, {'t': 'Faqat Afrika', 'c': False}]},
        {'t': 'Zamonaviy astronomiyada qanday qurilmalar ishlatiladi?', 'a': [{'t': 'Faqat ko\'z bilan kuzatish', 'c': False}, {'t': 'Teleskoplar, radioteleskoplar, sun\'iy yo\'ldoshlar', 'c': True}, {'t': 'Faqat kitoblar', 'c': False}, {'t': 'Faqat kompyuter', 'c': False}]},
        {'t': 'Astronomiya qanday fanlarga bo\'linadi?', 'a': [{'t': 'Faqat bitta yo\'nalish', 'c': False}, {'t': 'Faqat ikki yo\'nalish', 'c': False}, {'t': 'Astrofizika, astrometriya, kosmologiya, planetologiya', 'c': True}, {'t': 'Hech qanday bo\'linmaydi', 'c': False}]},
        {'t': 'Birinchi teleskopni kim ixtiro qilgan?', 'a': [{'t': 'Isaak Nyuton', 'c': False}, {'t': 'Albert Eynshteyn', 'c': False}, {'t': 'Galileo Galiley', 'c': True}, {'t': 'Kopernik', 'c': False}]},
        {'t': 'Astronomiya amaliy hayotda qanday qo\'llaniladi?', 'a': [{'t': 'Navigatsiya, kalendar, vaqtni aniqlash', 'c': True}, {'t': 'Hech qayerda qo\'llanilmaydi', 'c': False}, {'t': 'Faqat o\'yinlarda', 'c': False}, {'t': 'Faqat kinofilmlarda', 'c': False}]},
    ]},
    {'n': 'Quyosh tizimi tuzilishi', 't': 25, 'o': 2, 'q': [
        {'t': 'Quyosh tizimida nechta sayyora bor?', 'a': [{'t': '5 ta', 'c': False}, {'t': '8 ta', 'c': True}, {'t': '10 ta', 'c': False}, {'t': '12 ta', 'c': False}]},
        {'t': 'Quyosh tizimining markazida nima joylashgan?', 'a': [{'t': 'Yer', 'c': False}, {'t': 'Quyosh', 'c': True}, {'t': 'Oy', 'c': False}, {'t': 'Yupiter', 'c': False}]},
        {'t': 'Quyoshga eng yaqin sayyora?', 'a': [{'t': 'Venera', 'c': False}, {'t': 'Yer', 'c': False}, {'t': 'Merkuriy', 'c': True}, {'t': 'Mars', 'c': False}]},
        {'t': 'Eng katta sayyora qaysi?', 'a': [{'t': 'Yupiter', 'c': True}, {'t': 'Saturn', 'c': False}, {'t': 'Yer', 'c': False}, {'t': 'Neptun', 'c': False}]},
        {'t': 'Quyosh tizimida nechta mitti sayyora bor?', 'a': [{'t': '2 ta', 'c': False}, {'t': '4 ta (Merkuriy, Venera, Yer, Mars)', 'c': True}, {'t': '6 ta', 'c': False}, {'t': '8 ta', 'c': False}]},
        {'t': 'Ulkan gazli sayyoralar qaysilar?', 'a': [{'t': 'Merkuriy va Venera', 'c': False}, {'t': 'Yer va Mars', 'c': False}, {'t': 'Yupiter, Saturn, Uran, Neptun', 'c': True}, {'t': 'Faqat Yupiter', 'c': False}]},
        {'t': 'Asteroid kamari qayerda joylashgan?', 'a': [{'t': 'Yer va Oy orasida', 'c': False}, {'t': 'Mars va Yupiter orasida', 'c': True}, {'t': 'Quyoshdan tashqarida', 'c': False}, {'t': 'Neptundan keyin', 'c': False}]},
        {'t': 'Pluton nima hisoblanadi?', 'a': [{'t': 'Sayyora', 'c': False}, {'t': 'Yulduz', 'c': False}, {'t': 'Mitti sayyora', 'c': True}, {'t': 'Yo\'ldosh', 'c': False}]},
    ]},
    {'n': 'Quyosh - bizning yulduzimiz', 't': 25, 'o': 3, 'q': [
        {'t': 'Quyosh nima?', 'a': [{'t': 'Sayyora', 'c': False}, {'t': 'Yo\'ldosh', 'c': False}, {'t': 'Yulduz', 'c': True}, {'t': 'Asteroid', 'c': False}]},
        {'t': 'Quyosh qanday energiya chiqaradi?', 'a': [{'t': 'Issiqlik va yorug\'lik', 'c': True}, {'t': 'Faqat issiqlik', 'c': False}, {'t': 'Faqat yorug\'lik', 'c': False}, {'t': 'Hech qanday energiya yo\'q', 'c': False}]},
        {'t': 'Quyoshning asosiy tarkibi?', 'a': [{'t': 'Temir va nikel', 'c': False}, {'t': 'Vodorod va geliy', 'c': True}, {'t': 'Kislorod va azot', 'c': False}, {'t': 'Uglerod va kremniy', 'c': False}]},
        {'t': 'Quyosh diametri Yer diametridan necha marta katta?', 'a': [{'t': '10 marta', 'c': False}, {'t': '50 marta', 'c': False}, {'t': '109 marta', 'c': True}, {'t': '200 marta', 'c': False}]},
        {'t': 'Quyosh yuzasidagi harorat qancha?', 'a': [{'t': '1000°C', 'c': False}, {'t': '3000°C', 'c': False}, {'t': '5500°C', 'c': True}, {'t': '10000°C', 'c': False}]},
        {'t': 'Quyosh markazidagi harorat?', 'a': [{'t': '1 million daraja', 'c': False}, {'t': '15 million daraja', 'c': True}, {'t': '100 ming daraja', 'c': False}, {'t': '50 million daraja', 'c': False}]},
        {'t': 'Quyosh dog\'lari nima?', 'a': [{'t': 'Yuzadagi sovuqroq joylar', 'c': True}, {'t': 'Issiqroq joylar', 'c': False}, {'t': 'Teshiklar', 'c': False}, {'t': 'Bulutlar', 'c': False}]},
        {'t': 'Quyosh necha yoshda?', 'a': [{'t': '1 milliard yil', 'c': False}, {'t': '4.6 milliard yil', 'c': True}, {'t': '10 milliard yil', 'c': False}, {'t': '100 million yil', 'c': False}]},
    ]},
    {'n': 'Merkuriy sayyorasi', 't': 25, 'o': 4, 'q': [
        {'t': 'Merkuriy Quyoshga eng yaqin sayyorami?', 'a': [{'t': 'Ha', 'c': True}, {'t': 'Yo\'q', 'c': False}, {'t': 'Ikkinchi o\'rinda', 'c': False}, {'t': 'Uchinchi o\'rinda', 'c': False}]},
        {'t': 'Merkuriy atmosferasi qanday?', 'a': [{'t': 'Qalin atmosfera', 'c': False}, {'t': 'Deyarli yo\'q', 'c': True}, {'t': 'Yer kabi', 'c': False}, {'t': 'Juda qalin', 'c': False}]},
        {'t': 'Merkuriydagi harorat farqi?', 'a': [{'t': 'Kichik', 'c': False}, {'t': 'Juda katta (-180°C dan +430°C gacha)', 'c': True}, {'t': 'Yo\'q', 'c': False}, {'t': 'O\'rtacha', 'c': False}]},
        {'t': 'Merkuriy yuzasi qanday?', 'a': [{'t': 'Silliq', 'c': False}, {'t': 'Kraterlar bilan qoplangan', 'c': True}, {'t': 'Suv bilan qoplangan', 'c': False}, {'t': 'Yashil o\'simliklar bor', 'c': False}]},
        {'t': 'Merkuriy Quyosh atrofida necha kunda aylanadi?', 'a': [{'t': '365 kun', 'c': False}, {'t': '88 kun', 'c': True}, {'t': '30 kun', 'c': False}, {'t': '687 kun', 'c': False}]},
        {'t': 'Merkuriyning yo\'ldoshi bormi?', 'a': [{'t': 'Ha, 1 ta', 'c': False}, {'t': 'Ha, 2 ta', 'c': False}, {'t': 'Yo\'q', 'c': True}, {'t': 'Ha, 5 ta', 'c': False}]},
    ]},
    {'n': 'Venera sayyorasi', 't': 25, 'o': 5, 'q': [
        {'t': 'Venera qaysi sayyoraga o\'xshaydi?', 'a': [{'t': 'Yupiterga', 'c': False}, {'t': 'Yerga (o\'lcham jihatidan)', 'c': True}, {'t': 'Marsga', 'c': False}, {'t': 'Merkuriyga', 'c': False}]},
        {'t': 'Venera atmosferasi nimadan iborat?', 'a': [{'t': 'Kisloroddan', 'c': False}, {'t': 'Uglerod dioksididan', 'c': True}, {'t': 'Azotdan', 'c': False}, {'t': 'Vodoroddan', 'c': False}]},
        {'t': 'Veneradagi harorat qancha?', 'a': [{'t': '100°C', 'c': False}, {'t': '200°C', 'c': False}, {'t': '465°C', 'c': True}, {'t': '50°C', 'c': False}]},
        {'t': 'Venera qanday aylanadi?', 'a': [{'t': 'Boshqa sayyoralar kabi', 'c': False}, {'t': 'Teskari yo\'nalishda', 'c': True}, {'t': 'Aylanmaydi', 'c': False}, {'t': 'Juda tez', 'c': False}]},
        {'t': 'Venera yuzasida nima bor?', 'a': [{'t': 'Suv okeanlari', 'c': False}, {'t': 'Vulkanlar va tog\'lar', 'c': True}, {'t': 'Muzliklar', 'c': False}, {'t': 'O\'rmonlar', 'c': False}]},
        {'t': 'Venerani qanday ko\'rish mumkin?', 'a': [{'t': 'Faqat teleskop bilan', 'c': False}, {'t': 'Yalang\'och ko\'z bilan, eng yorqin sayyora', 'c': True}, {'t': 'Hech qachon ko\'rinmaydi', 'c': False}, {'t': 'Faqat kunduzi', 'c': False}]},
        {'t': 'Venera bulutlari nimadan iborat?', 'a': [{'t': 'Suv bug\'idan', 'c': False}, {'t': 'Oltingugurt kislotasidan', 'c': True}, {'t': 'Muz kristallaridan', 'c': False}, {'t': 'Chang zarralaridan', 'c': False}]},
    ]},
    {'n': 'Yer sayyorasi', 't': 25, 'o': 6, 'q': [
        {'t': 'Yer Quyoshdan nechinchi sayyora?', 'a': [{'t': 'Birinchi', 'c': False}, {'t': 'Ikkinchi', 'c': False}, {'t': 'Uchinchi', 'c': True}, {'t': 'To\'rtinchi', 'c': False}]},
        {'t': 'Yer atmosferasining asosiy gazi?', 'a': [{'t': 'Kislorod', 'c': False}, {'t': 'Azot (78%)', 'c': True}, {'t': 'Uglerod dioksidi', 'c': False}, {'t': 'Vodorod', 'c': False}]},
        {'t': 'Yer o\'z o\'qi atrofida necha soatda aylanadi?', 'a': [{'t': '12 soat', 'c': False}, {'t': '24 soat', 'c': True}, {'t': '48 soat', 'c': False}, {'t': '6 soat', 'c': False}]},
        {'t': 'Yer Quyosh atrofida necha kunda aylanadi?', 'a': [{'t': '365.25 kun', 'c': True}, {'t': '300 kun', 'c': False}, {'t': '400 kun', 'c': False}, {'t': '200 kun', 'c': False}]},
        {'t': 'Yer yuzasining necha foizi suv bilan qoplangan?', 'a': [{'t': '50%', 'c': False}, {'t': '71%', 'c': True}, {'t': '30%', 'c': False}, {'t': '90%', 'c': False}]},
        {'t': 'Yer necha yoshda?', 'a': [{'t': '1 milliard yil', 'c': False}, {'t': '4.5 milliard yil', 'c': True}, {'t': '10 milliard yil', 'c': False}, {'t': '100 million yil', 'c': False}]},
        {'t': 'Yer magnit maydonini nima hosil qiladi?', 'a': [{'t': 'Atmosfera', 'c': False}, {'t': 'Suyuq tashqi yadro', 'c': True}, {'t': 'Okeanlar', 'c': False}, {'t': 'Quyosh', 'c': False}]},
        {'t': 'Yer qatlamlari qanday joylashgan?', 'a': [{'t': 'Yadro, mantiya, qobiq', 'c': True}, {'t': 'Faqat yadro', 'c': False}, {'t': 'Faqat qobiq', 'c': False}, {'t': 'Bir xil tuzilish', 'c': False}]},
    ]},
    {'n': 'Oy - Yerning yo\'ldoshi', 't': 25, 'o': 7, 'q': [
        {'t': 'Oy Yerdan qancha masofada?', 'a': [{'t': '100 ming km', 'c': False}, {'t': '384 ming km', 'c': True}, {'t': '1 million km', 'c': False}, {'t': '10 million km', 'c': False}]},
        {'t': 'Oy o\'z o\'qi atrofida necha kunda aylanadi?', 'a': [{'t': '1 kun', 'c': False}, {'t': '27.3 kun', 'c': True}, {'t': '30 kun', 'c': False}, {'t': '365 kun', 'c': False}]},
        {'t': 'Oy Yer atrofida necha kunda aylanadi?', 'a': [{'t': '10 kun', 'c': False}, {'t': '27.3 kun', 'c': True}, {'t': '50 kun', 'c': False}, {'t': '100 kun', 'c': False}]},
        {'t': 'Nima uchun Oyning bir tomoni doim Yerga qaragan?', 'a': [{'t': 'Tasodif', 'c': False}, {'t': 'Sinxron aylanish', 'c': True}, {'t': 'Magnit maydon', 'c': False}, {'t': 'Gravitatsiya yo\'q', 'c': False}]},
        {'t': 'Oy yuzasidagi kraterlar qanday paydo bo\'lgan?', 'a': [{'t': 'Vulkanlar', 'c': False}, {'t': 'Meteorit urilishi', 'c': True}, {'t': 'Shamol', 'c': False}, {'t': 'Suv eroziyasi', 'c': False}]},
        {'t': 'Oyda atmosfera bormi?', 'a': [{'t': 'Ha, qalin', 'c': False}, {'t': 'Deyarli yo\'q', 'c': True}, {'t': 'Yer kabi', 'c': False}, {'t': 'Juda qalin', 'c': False}]},
        {'t': 'Birinchi odam Oyga qachon qo\'ngan?', 'a': [{'t': '1959 yil', 'c': False}, {'t': '1969 yil (Apollo 11)', 'c': True}, {'t': '1980 yil', 'c': False}, {'t': '2000 yil', 'c': False}]},
        {'t': 'Oy fazalari nima?', 'a': [{'t': 'Yangi oy, o\'suvchi oy, to\'lin oy, kamayuvchi oy', 'c': True}, {'t': 'Faqat to\'lin oy', 'c': False}, {'t': 'Faqat yangi oy', 'c': False}, {'t': 'Hech qanday faza yo\'q', 'c': False}]},
    ]},
    {'n': 'Mars - qizil sayyora', 't': 25, 'o': 8, 'q': [
        {'t': 'Mars nima uchun qizil?', 'a': [{'t': 'Issiq bo\'lgani uchun', 'c': False}, {'t': 'Temir oksidi (zang) tufayli', 'c': True}, {'t': 'Quyosh nuri tufayli', 'c': False}, {'t': 'Atmosfera tufayli', 'c': False}]},
        {'t': 'Marsda nechta yo\'ldosh bor?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': '2 ta (Fobos va Deymos)', 'c': True}, {'t': '1 ta', 'c': False}, {'t': '5 ta', 'c': False}]},
        {'t': 'Mars atmosferasi nimadan iborat?', 'a': [{'t': 'Kislorod', 'c': False}, {'t': 'Uglerod dioksidi', 'c': True}, {'t': 'Azot', 'c': False}, {'t': 'Vodorod', 'c': False}]},
        {'t': 'Marsda eng baland tog\' qaysi?', 'a': [{'t': 'Everest', 'c': False}, {'t': 'Olimp tog\'i (27 km)', 'c': True}, {'t': 'Kilimanjaro', 'c': False}, {'t': 'Elbrus', 'c': False}]},
        {'t': 'Marsda suv bormi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha, muz holida qutblarda', 'c': True}, {'t': 'Faqat suyuq holda', 'c': False}, {'t': 'Faqat bug\' holida', 'c': False}]},
        {'t': 'Mars Quyosh atrofida necha kunda aylanadi?', 'a': [{'t': '365 kun', 'c': False}, {'t': '687 kun', 'c': True}, {'t': '200 kun', 'c': False}, {'t': '1000 kun', 'c': False}]},
        {'t': 'Marsda hayot bormi?', 'a': [{'t': 'Ha, aniq', 'c': False}, {'t': 'Hozircha topilmagan, izlanishlar davom etmoqda', 'c': True}, {'t': 'Yo\'q, umuman bo\'lmagan', 'c': False}, {'t': 'Faqat o\'simliklar', 'c': False}]},
    ]},
    {'n': 'Yupiter - ulkan sayyora', 't': 25, 'o': 9, 'q': [
        {'t': 'Yupiter Quyosh tizimidagi eng katta sayyorami?', 'a': [{'t': 'Ha', 'c': True}, {'t': 'Yo\'q', 'c': False}, {'t': 'Ikkinchi o\'rinda', 'c': False}, {'t': 'Uchinchi o\'rinda', 'c': False}]},
        {'t': 'Yupiter asosan nimadan iborat?', 'a': [{'t': 'Tosh va metall', 'c': False}, {'t': 'Vodorod va geliy', 'c': True}, {'t': 'Suv va muz', 'c': False}, {'t': 'Uglerod dioksidi', 'c': False}]},
        {'t': 'Yupiterda nechta yo\'ldosh bor?', 'a': [{'t': '10 ta', 'c': False}, {'t': '79 tadan ortiq', 'c': True}, {'t': '5 ta', 'c': False}, {'t': 'Yo\'q', 'c': False}]},
        {'t': 'Yupiterdagi Katta Qizil Dog\' nima?', 'a': [{'t': 'Vulkan', 'c': False}, {'t': 'Ulkan bo\'ron (300 yildan beri)', 'c': True}, {'t': 'Okean', 'c': False}, {'t': 'Tog\'', 'c': False}]},
        {'t': 'Yupiterning eng katta yo\'ldoshlari?', 'a': [{'t': 'Io, Yevropa, Ganimed, Kallisto', 'c': True}, {'t': 'Faqat Io', 'c': False}, {'t': 'Faqat Ganimed', 'c': False}, {'t': 'Hech biri', 'c': False}]},
        {'t': 'Yupiter o\'z o\'qi atrofida necha soatda aylanadi?', 'a': [{'t': '24 soat', 'c': False}, {'t': '10 soat', 'c': True}, {'t': '48 soat', 'c': False}, {'t': '5 soat', 'c': False}]},
        {'t': 'Yupiterda halqalar bormi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha, lekin zaif', 'c': True}, {'t': 'Faqat Saturn halqalari bor', 'c': False}, {'t': 'Juda qalin halqalar', 'c': False}]},
    ]},
    {'n': 'Saturn - halqali sayyora', 't': 25, 'o': 10, 'q': [
        {'t': 'Saturn nima bilan mashhur?', 'a': [{'t': 'Rangi bilan', 'c': False}, {'t': 'Go\'zal halqalari bilan', 'c': True}, {'t': 'Katta hajmi bilan', 'c': False}, {'t': 'Yo\'ldoshlari bilan', 'c': False}]},
        {'t': 'Saturn halqalari nimadan iborat?', 'a': [{'t': 'Tosh va chang', 'c': False}, {'t': 'Muz va tosh zarralar', 'c': True}, {'t': 'Gaz', 'c': False}, {'t': 'Metall', 'c': False}]},
        {'t': 'Saturnda nechta yo\'ldosh bor?', 'a': [{'t': '10 ta', 'c': False}, {'t': '82 tadan ortiq', 'c': True}, {'t': '5 ta', 'c': False}, {'t': 'Yo\'q', 'c': False}]},
        {'t': 'Saturnning eng katta yo\'ldoshi?', 'a': [{'t': 'Oy', 'c': False}, {'t': 'Titan', 'c': True}, {'t': 'Yevropa', 'c': False}, {'t': 'Io', 'c': False}]},
        {'t': 'Saturn zichligi qanday?', 'a': [{'t': 'Juda katta', 'c': False}, {'t': 'Suvdan ham kichik', 'c': True}, {'t': 'Temirday', 'c': False}, {'t': 'Yerday', 'c': False}]},
        {'t': 'Saturn asosan nimadan iborat?', 'a': [{'t': 'Tosh', 'c': False}, {'t': 'Vodorod va geliy', 'c': True}, {'t': 'Suv', 'c': False}, {'t': 'Metall', 'c': False}]},
        {'t': 'Titanda atmosfera bormi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha, qalin azot atmosferasi', 'c': True}, {'t': 'Juda yupqa', 'c': False}, {'t': 'Faqat kislorod', 'c': False}]},
    ]},
    {'n': 'Uran va Neptun', 't': 25, 'o': 11, 'q': [
        {'t': 'Uran qanday sayyora?', 'a': [{'t': 'Mitti sayyora', 'c': False}, {'t': 'Muz giganti', 'c': True}, {'t': 'Gazli gigant', 'c': False}, {'t': 'Toshli sayyora', 'c': False}]},
        {'t': 'Uran qanday aylanadi?', 'a': [{'t': 'Oddiy', 'c': False}, {'t': 'Yonboshlab (98° qiyalik)', 'c': True}, {'t': 'Teskari', 'c': False}, {'t': 'Aylanmaydi', 'c': False}]},
        {'t': 'Uran rangi qanday?', 'a': [{'t': 'Qizil', 'c': False}, {'t': 'Moviy-yashil (metan gazi tufayli)', 'c': True}, {'t': 'Sariq', 'c': False}, {'t': 'Qora', 'c': False}]},
        {'t': 'Neptun Quyoshdan nechinchi sayyora?', 'a': [{'t': '6-chi', 'c': False}, {'t': '8-chi', 'c': True}, {'t': '7-chi', 'c': False}, {'t': '5-chi', 'c': False}]},
        {'t': 'Neptunda shamol tezligi qanday?', 'a': [{'t': 'Sekin', 'c': False}, {'t': 'Eng tez (2000 km/soat)', 'c': True}, {'t': 'O\'rtacha', 'c': False}, {'t': 'Shamol yo\'q', 'c': False}]},
        {'t': 'Neptunning eng katta yo\'ldoshi?', 'a': [{'t': 'Titan', 'c': False}, {'t': 'Triton', 'c': True}, {'t': 'Oy', 'c': False}, {'t': 'Yevropa', 'c': False}]},
        {'t': 'Uran va Neptun nima bilan o\'xshash?', 'a': [{'t': 'Ikkalasi ham muz gigantlari', 'c': True}, {'t': 'Hech narsa bilan', 'c': False}, {'t': 'Faqat rangi', 'c': False}, {'t': 'Faqat hajmi', 'c': False}]},
    ]},
    {'n': 'Kichik osmon jismlari', 't': 25, 'o': 12, 'q': [
        {'t': 'Asteroid nima?', 'a': [{'t': 'Yulduz', 'c': False}, {'t': 'Kichik toshli jism', 'c': True}, {'t': 'Sayyora', 'c': False}, {'t': 'Yo\'ldosh', 'c': False}]},
        {'t': 'Asteroid kamari qayerda?', 'a': [{'t': 'Yer va Mars orasida', 'c': False}, {'t': 'Mars va Yupiter orasida', 'c': True}, {'t': 'Neptundan keyin', 'c': False}, {'t': 'Quyosh yaqinida', 'c': False}]},
        {'t': 'Kometa nima?', 'a': [{'t': 'Sayyora', 'c': False}, {'t': 'Muz va chang to\'pi', 'c': True}, {'t': 'Yulduz', 'c': False}, {'t': 'Yo\'ldosh', 'c': False}]},
        {'t': 'Kometa dumi qachon paydo bo\'ladi?', 'a': [{'t': 'Doim bor', 'c': False}, {'t': 'Quyoshga yaqinlashganda', 'c': True}, {'t': 'Hech qachon', 'c': False}, {'t': 'Faqat kechasi', 'c': False}]},
        {'t': 'Meteorit nima?', 'a': [{'t': 'Yulduz', 'c': False}, {'t': 'Yerga tushgan osmon jismi', 'c': True}, {'t': 'Sayyora', 'c': False}, {'t': 'Sun\'iy yo\'ldosh', 'c': False}]},
        {'t': 'Meteor nima?', 'a': [{'t': 'Sayyora', 'c': False}, {'t': 'Atmosferada yonayotgan jism (yulduz yomg\'iri)', 'c': True}, {'t': 'Kometa', 'c': False}, {'t': 'Asteroid', 'c': False}]},
        {'t': 'Eng mashhur kometa?', 'a': [{'t': 'Galley kometasi', 'c': True}, {'t': 'Hech qanday', 'c': False}, {'t': 'Mars kometasi', 'c': False}, {'t': 'Yer kometasi', 'c': False}]},
        {'t': 'Galley kometasi necha yilda bir marta ko\'rinadi?', 'a': [{'t': '10 yilda', 'c': False}, {'t': '76 yilda', 'c': True}, {'t': '100 yilda', 'c': False}, {'t': '5 yilda', 'c': False}]},
    ]},
    {'n': 'Quyosh va Oy tutilishi', 't': 25, 'o': 13, 'q': [
        {'t': 'Quyosh tutilishi qachon sodir bo\'ladi?', 'a': [{'t': 'Oy Yer va Quyosh orasida bo\'lganda', 'c': True}, {'t': 'Yer Oy va Quyosh orasida', 'c': False}, {'t': 'Har doim', 'c': False}, {'t': 'Hech qachon', 'c': False}]},
        {'t': 'Oy tutilishi qachon sodir bo\'ladi?', 'a': [{'t': 'Oy Yer va Quyosh orasida', 'c': False}, {'t': 'Yer Oy va Quyosh orasida', 'c': True}, {'t': 'Har doim', 'c': False}, {'t': 'Hech qachon', 'c': False}]},
        {'t': 'To\'liq Quyosh tutilishi necha daqiqa davom etadi?', 'a': [{'t': '1 soat', 'c': False}, {'t': '7-8 daqiqa', 'c': True}, {'t': '1 kun', 'c': False}, {'t': '1 sekund', 'c': False}]},
        {'t': 'Quyosh tutilishini qanday kuzatish kerak?', 'a': [{'t': 'Yalang\'och ko\'z bilan', 'c': False}, {'t': 'Maxsus filtrlar bilan', 'c': True}, {'t': 'Oddiy ko\'zoynak bilan', 'c': False}, {'t': 'Kuzatmaslik kerak', 'c': False}]},
        {'t': 'Oy tutilishi qanday rangda bo\'ladi?', 'a': [{'t': 'Oq', 'c': False}, {'t': 'Qizil-jigarrang', 'c': True}, {'t': 'Yashil', 'c': False}, {'t': 'Ko\'k', 'c': False}]},
        {'t': 'Tutilishlar necha yilda bir marta sodir bo\'ladi?', 'a': [{'t': 'Har oy', 'c': False}, {'t': 'Yiliga bir necha marta', 'c': True}, {'t': 'Har 100 yilda', 'c': False}, {'t': 'Hech qachon', 'c': False}]},
    ]},
    {'n': 'Yulduzlar va yulduz turkumlari', 't': 25, 'o': 14, 'q': [
        {'t': 'Yulduz nima?', 'a': [{'t': 'Sayyora', 'c': False}, {'t': 'O\'z nurini chiqaruvchi osmon jismi', 'c': True}, {'t': 'Yo\'ldosh', 'c': False}, {'t': 'Asteroid', 'c': False}]},
        {'t': 'Yulduzlar nimadan energiya oladi?', 'a': [{'t': 'Quyoshdan', 'c': False}, {'t': 'Yadro sintezi (vodorod geliyga aylanadi)', 'c': True}, {'t': 'Elektr energiyasidan', 'c': False}, {'t': 'Hech qayerdan', 'c': False}]},
        {'t': 'Eng yaqin yulduz qaysi?', 'a': [{'t': 'Sirius', 'c': False}, {'t': 'Quyosh', 'c': True}, {'t': 'Alfa Kentavr', 'c': False}, {'t': 'Vega', 'c': False}]},
        {'t': 'Quyoshdan keyin eng yaqin yulduz?', 'a': [{'t': 'Sirius', 'c': False}, {'t': 'Proksima Kentavr (4.2 yorug\'lik yili)', 'c': True}, {'t': 'Vega', 'c': False}, {'t': 'Betelgeyze', 'c': False}]},
        {'t': 'Yulduz turkumi nima?', 'a': [{'t': 'Tasodifiy yulduzlar', 'c': False}, {'t': 'Osmondan ko\'rinadigan yulduzlar guruhi', 'c': True}, {'t': 'Faqat bitta yulduz', 'c': False}, {'t': 'Sayyoralar guruhi', 'c': False}]},
        {'t': 'Katta Ayiq turkumi nima bilan mashhur?', 'a': [{'t': 'Rangi bilan', 'c': False}, {'t': 'Katta Chelak shakli bilan', 'c': True}, {'t': 'Hajmi bilan', 'c': False}, {'t': 'Hech narsa bilan', 'c': False}]},
        {'t': 'Shimoliy yulduz qaysi turkumda?', 'a': [{'t': 'Katta Ayiq', 'c': False}, {'t': 'Kichik Ayiq', 'c': True}, {'t': 'Orion', 'c': False}, {'t': 'Kassiopeya', 'c': False}]},
        {'t': 'Orion turkumida qanday yulduzlar bor?', 'a': [{'t': 'Betelgeyze, Rigel, Bellatrix', 'c': True}, {'t': 'Faqat Quyosh', 'c': False}, {'t': 'Hech qanday', 'c': False}, {'t': 'Faqat Sirius', 'c': False}]},
    ]},
    {'n': 'Yulduzlarning hayot sikli', 't': 25, 'o': 15, 'q': [
        {'t': 'Yulduz qanday tug\'iladi?', 'a': [{'t': 'Tasodifan', 'c': False}, {'t': 'Gaz va chang bulutidan', 'c': True}, {'t': 'Boshqa yulduzdan', 'c': False}, {'t': 'Sayyoradan', 'c': False}]},
        {'t': 'Yulduzning asosiy hayot davri nima?', 'a': [{'t': 'Tug\'ilish', 'c': False}, {'t': 'Asosiy ketma-ketlik (vodorod yonadi)', 'c': True}, {'t': 'O\'lim', 'c': False}, {'t': 'Portlash', 'c': False}]},
        {'t': 'Quyosh qaysi bosqichda?', 'a': [{'t': 'Tug\'ilmoqda', 'c': False}, {'t': 'Asosiy ketma-ketlikda', 'c': True}, {'t': 'O\'lmoqda', 'c': False}, {'t': 'Portlamoqda', 'c': False}]},
        {'t': 'Qizil gigant nima?', 'a': [{'t': 'Yosh yulduz', 'c': False}, {'t': 'Keksa kengaygan yulduz', 'c': True}, {'t': 'O\'lgan yulduz', 'c': False}, {'t': 'Sayyora', 'c': False}]},
        {'t': 'Oq mitti nima?', 'a': [{'t': 'Yosh yulduz', 'c': False}, {'t': 'Kichik yulduzning qoldig\'i', 'c': True}, {'t': 'Sayyora', 'c': False}, {'t': 'Yo\'ldosh', 'c': False}]},
        {'t': 'Supernova nima?', 'a': [{'t': 'Yangi yulduz', 'c': False}, {'t': 'Katta yulduzning portlashi', 'c': True}, {'t': 'Sayyora', 'c': False}, {'t': 'Kometa', 'c': False}]},
        {'t': 'Neytron yulduz nima?', 'a': [{'t': 'Oddiy yulduz', 'c': False}, {'t': 'Juda zich yulduz qoldig\'i', 'c': True}, {'t': 'Sayyora', 'c': False}, {'t': 'Asteroid', 'c': False}]},
        {'t': 'Qora tuynuk nima?', 'a': [{'t': 'Oddiy yulduz', 'c': False}, {'t': 'Hamma narsani o\'ziga tortadigan jism', 'c': True}, {'t': 'Sayyora', 'c': False}, {'t': 'Kometa', 'c': False}]},
    ]},
    {'n': 'Galaktikalar', 't': 25, 'o': 16, 'q': [
        {'t': 'Galaktika nima?', 'a': [{'t': 'Bitta yulduz', 'c': False}, {'t': 'Milliardlab yulduzlar tizimi', 'c': True}, {'t': 'Sayyora', 'c': False}, {'t': 'Yo\'ldosh', 'c': False}]},
        {'t': 'Bizning galaktikamiz nomi?', 'a': [{'t': 'Andromeda', 'c': False}, {'t': 'Somon yo\'li', 'c': True}, {'t': 'Uchburchak', 'c': False}, {'t': 'Katta Bulut', 'c': False}]},
        {'t': 'Somon yo\'li qanday shaklda?', 'a': [{'t': 'Shar', 'c': False}, {'t': 'Spiral', 'c': True}, {'t': 'Ellips', 'c': False}, {'t': 'Tartibsiz', 'c': False}]},
        {'t': 'Somon yo\'lida nechta yulduz bor?', 'a': [{'t': '1 million', 'c': False}, {'t': '100-400 milliard', 'c': True}, {'t': '1000', 'c': False}, {'t': '10 million', 'c': False}]},
        {'t': 'Eng yaqin galaktika?', 'a': [{'t': 'Somon yo\'li', 'c': False}, {'t': 'Andromeda (2.5 million yorug\'lik yili)', 'c': True}, {'t': 'Uchburchak', 'c': False}, {'t': 'Katta Bulut', 'c': False}]},
        {'t': 'Galaktikalar qanday turlarga bo\'linadi?', 'a': [{'t': 'Spiral, elliptik, tartibsiz', 'c': True}, {'t': 'Faqat spiral', 'c': False}, {'t': 'Faqat doira', 'c': False}, {'t': 'Hech qanday tur yo\'q', 'c': False}]},
        {'t': 'Galaktika markazida nima bor?', 'a': [{'t': 'Hech narsa', 'c': False}, {'t': 'Supermassiv qora tuynuk', 'c': True}, {'t': 'Sayyora', 'c': False}, {'t': 'Quyosh', 'c': False}]},
    ]},
    {'n': 'Koinot va Katta portlash', 't': 25, 'o': 17, 'q': [
        {'t': 'Koinot necha yoshda?', 'a': [{'t': '1 milliard yil', 'c': False}, {'t': '13.8 milliard yil', 'c': True}, {'t': '100 million yil', 'c': False}, {'t': '1 million yil', 'c': False}]},
        {'t': 'Katta portlash nazariyasi nimani tushuntiradi?', 'a': [{'t': 'Faqat Yerni', 'c': False}, {'t': 'Koinotning paydo bo\'lishini', 'c': True}, {'t': 'Faqat Quyoshni', 'c': False}, {'t': 'Hech narsani', 'c': False}]},
        {'t': 'Koinot qanday kengaymoqda?', 'a': [{'t': 'Kengaymaydi', 'c': False}, {'t': 'Tezlashib kengaymoqda', 'c': True}, {'t': 'Qisqarmoqda', 'c': False}, {'t': 'O\'zgarmaydi', 'c': False}]},
        {'t': 'Qorong\'u materiya nima?', 'a': [{'t': 'Oddiy materiya', 'c': False}, {'t': 'Ko\'rinmaydigan, lekin gravitatsiyasi bor materiya', 'c': True}, {'t': 'Yorug\'lik', 'c': False}, {'t': 'Energiya', 'c': False}]},
        {'t': 'Qorong\'u energiya nima?', 'a': [{'t': 'Oddiy energiya', 'c': False}, {'t': 'Koinotni kengaytiruvchi sirli kuch', 'c': True}, {'t': 'Elektr energiyasi', 'c': False}, {'t': 'Issiqlik energiyasi', 'c': False}]},
        {'t': 'Koinotda nima ko\'p?', 'a': [{'t': 'Qorong\'u materiya va qorong\'u energiya (95%)', 'c': True}, {'t': 'Faqat yulduzlar', 'c': False}, {'t': 'Faqat sayyoralar', 'c': False}, {'t': 'Faqat galaktikalar', 'c': False}]},
    ]},
    {'n': 'Teleskoplar va kuzatish', 't': 25, 'o': 18, 'q': [
        {'t': 'Teleskop nima uchun kerak?', 'a': [{'t': 'Faqat bezash uchun', 'c': False}, {'t': 'Osmon jismlarini kattalashtirish uchun', 'c': True}, {'t': 'Faqat o\'yin uchun', 'c': False}, {'t': 'Hech narsa uchun', 'c': False}]},
        {'t': 'Teleskopning asosiy turlari?', 'a': [{'t': 'Refraktor va reflektor', 'c': True}, {'t': 'Faqat refraktor', 'c': False}, {'t': 'Faqat reflektor', 'c': False}, {'t': 'Hech qanday tur yo\'q', 'c': False}]},
        {'t': 'Refraktor teleskop nima ishlatadi?', 'a': [{'t': 'Oynalar', 'c': False}, {'t': 'Linzalar', 'c': True}, {'t': 'Prizmalar', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'Reflektor teleskop nima ishlatadi?', 'a': [{'t': 'Linzalar', 'c': False}, {'t': 'Oynalar', 'c': True}, {'t': 'Prizmalar', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'Eng katta optik teleskop qayerda?', 'a': [{'t': 'Rossiyada', 'c': False}, {'t': 'Gavayida, Kanariyadda', 'c': True}, {'t': 'O\'zbekistonda', 'c': False}, {'t': 'Yaponiyada', 'c': False}]},
        {'t': 'Hubble teleskopi qayerda?', 'a': [{'t': 'Yerda', 'c': False}, {'t': 'Kosmosda (Yer orbitasida)', 'c': True}, {'t': 'Oyda', 'c': False}, {'t': 'Marsda', 'c': False}]},
        {'t': 'Radioteleskop nima qiladi?', 'a': [{'t': 'Faqat ko\'radi', 'c': False}, {'t': 'Radio to\'lqinlarni qabul qiladi', 'c': True}, {'t': 'Faqat eshitadi', 'c': False}, {'t': 'Hech narsa qilmaydi', 'c': False}]},
    ]},
    {'n': 'Kosmik tadqiqotlar tarixi', 't': 20, 'o': 19, 'q': [
        {'t': 'Birinchi sun\'iy yo\'ldosh?', 'a': [{'t': 'Apollo', 'c': False}, {'t': 'Sputnik-1 (1957)', 'c': True}, {'t': 'Voyager', 'c': False}, {'t': 'Hubble', 'c': False}]},
        {'t': 'Birinchi kosmonavt?', 'a': [{'t': 'Nil Armstrong', 'c': False}, {'t': 'Yuriy Gagarin (1961)', 'c': True}, {'t': 'Buzz Oldrin', 'c': False}, {'t': 'Alan Shepard', 'c': False}]},
        {'t': 'Birinchi Oyga qo\'ngan odam?', 'a': [{'t': 'Yuriy Gagarin', 'c': False}, {'t': 'Nil Armstrong (1969)', 'c': True}, {'t': 'Buzz Oldrin', 'c': False}, {'t': 'Alan Shepard', 'c': False}]},
        {'t': 'Apollo dasturi nima edi?', 'a': [{'t': 'Marsga parvoz', 'c': False}, {'t': 'Oyga odam yuborish dasturi', 'c': True}, {'t': 'Yupiterga parvoz', 'c': False}, {'t': 'Faqat sun\'iy yo\'ldosh', 'c': False}]},
        {'t': 'Voyager zondlari qayerga uchgan?', 'a': [{'t': 'Faqat Marsga', 'c': False}, {'t': 'Tashqi sayyoralarga', 'c': True}, {'t': 'Faqat Oyga', 'c': False}, {'t': 'Hech qayerga', 'c': False}]},
    ]},
    {'n': 'Xalqaro kosmik stansiya', 't': 20, 'o': 20, 'q': [
        {'t': 'XKS nima?', 'a': [{'t': 'Sayyora', 'c': False}, {'t': 'Xalqaro kosmik stansiya', 'c': True}, {'t': 'Teleskop', 'c': False}, {'t': 'Raketa', 'c': False}]},
        {'t': 'XKS qayerda joylashgan?', 'a': [{'t': 'Oyda', 'c': False}, {'t': 'Yer orbitasida (400 km balandlikda)', 'c': True}, {'t': 'Marsda', 'c': False}, {'t': 'Yerda', 'c': False}]},
        {'t': 'XKSda odamlar yashaydimi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha, doimiy ekipaj', 'c': True}, {'t': 'Faqat robotlar', 'c': False}, {'t': 'Hech kim yo\'q', 'c': False}]},
        {'t': 'XKS qachon qurilgan?', 'a': [{'t': '1990 yilda', 'c': False}, {'t': '1998-2011 yillarda', 'c': True}, {'t': '2020 yilda', 'c': False}, {'t': '1980 yilda', 'c': False}]},
        {'t': 'XKSda qanday tadqiqotlar olib boriladi?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Fizika, biologiya, astronomiya', 'c': True}, {'t': 'Faqat o\'yinlar', 'c': False}, {'t': 'Faqat dam olish', 'c': False}]},
    ]},
    {'n': 'Mars tadqiqotlari', 't': 20, 'o': 21, 'q': [
        {'t': 'Marsga birinchi zond qachon uchgan?', 'a': [{'t': '1950 yilda', 'c': False}, {'t': '1960-1970 yillarda', 'c': True}, {'t': '2000 yilda', 'c': False}, {'t': '2020 yilda', 'c': False}]},
        {'t': 'Marsdagi roverlar nima?', 'a': [{'t': 'Odamlar', 'c': False}, {'t': 'Avtomatik tadqiqot mashinalari', 'c': True}, {'t': 'Sayyoralar', 'c': False}, {'t': 'Yulduzlar', 'c': False}]},
        {'t': 'Mashhur Mars roverlari?', 'a': [{'t': 'Faqat bitta', 'c': False}, {'t': 'Spirit, Opportunity, Curiosity, Perseverance', 'c': True}, {'t': 'Hech qanday', 'c': False}, {'t': 'Faqat Curiosity', 'c': False}]},
        {'t': 'Perseverance roveri qachon qo\'ngan?', 'a': [{'t': '2010 yilda', 'c': False}, {'t': '2021 yil fevralda', 'c': True}, {'t': '2000 yilda', 'c': False}, {'t': '2025 yilda', 'c': False}]},
        {'t': 'Marsda nima qidirilmoqda?', 'a': [{'t': 'Oltin', 'c': False}, {'t': 'Hayot izlari, suv', 'c': True}, {'t': 'Faqat toshlar', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
    ]},
    {'n': 'Ekzoplanetalar', 't': 20, 'o': 22, 'q': [
        {'t': 'Ekzoplaneta nima?', 'a': [{'t': 'Quyosh tizimidagi sayyora', 'c': False}, {'t': 'Boshqa yulduzlar atrofidagi sayyora', 'c': True}, {'t': 'Yo\'ldosh', 'c': False}, {'t': 'Asteroid', 'c': False}]},
        {'t': 'Birinchi ekzoplaneta qachon topilgan?', 'a': [{'t': '1980 yilda', 'c': False}, {'t': '1992-1995 yillarda', 'c': True}, {'t': '2020 yilda', 'c': False}, {'t': '1950 yilda', 'c': False}]},
        {'t': 'Nechta ekzoplaneta topilgan?', 'a': [{'t': '10 ta', 'c': False}, {'t': '5000 dan ortiq', 'c': True}, {'t': '100 ta', 'c': False}, {'t': 'Hech biri', 'c': False}]},
        {'t': 'Yashash zonasi nima?', 'a': [{'t': 'Har qanday joy', 'c': False}, {'t': 'Suyuq suv bo\'lishi mumkin bo\'lgan zona', 'c': True}, {'t': 'Faqat issiq zona', 'c': False}, {'t': 'Faqat sovuq zona', 'c': False}]},
        {'t': 'Kepler teleskopi nima qildi?', 'a': [{'t': 'Hech narsa', 'c': False}, {'t': 'Minglab ekzoplanetalarni topdi', 'c': True}, {'t': 'Faqat Yerni kuzatdi', 'c': False}, {'t': 'Faqat Quyoshni o\'rgandi', 'c': False}]},
    ]},
    {'n': 'Hayot qidirish', 't': 20, 'o': 23, 'q': [
        {'t': 'Kosmosda hayot bormi?', 'a': [{'t': 'Yo\'q, aniq', 'c': False}, {'t': 'Noma\'lum, qidirilmoqda', 'c': True}, {'t': 'Ha, topilgan', 'c': False}, {'t': 'Hech qachon bo\'lmaydi', 'c': False}]},
        {'t': 'SETI dasturi nima?', 'a': [{'t': 'Sayyora dasturi', 'c': False}, {'t': 'Aqlli hayot signallarini qidirish', 'c': True}, {'t': 'Raketa dasturi', 'c': False}, {'t': 'Teleskop dasturi', 'c': False}]},
        {'t': 'Qayerda hayot qidirilmoqda?', 'a': [{'t': 'Faqat Yerda', 'c': False}, {'t': 'Mars, Yevropa, Enseladus, ekzoplanetalar', 'c': True}, {'t': 'Faqat Quyoshda', 'c': False}, {'t': 'Hech qayerda', 'c': False}]},
        {'t': 'Yevropa (Yupiter yo\'ldoshi) nima bilan qiziq?', 'a': [{'t': 'Hech narsa bilan', 'c': False}, {'t': 'Muz ostida okean bo\'lishi mumkin', 'c': True}, {'t': 'Faqat rangi bilan', 'c': False}, {'t': 'Faqat hajmi bilan', 'c': False}]},
        {'t': 'Hayot uchun nima kerak?', 'a': [{'t': 'Faqat havo', 'c': False}, {'t': 'Suv, energiya, organik moddalar', 'c': True}, {'t': 'Faqat yorug\'lik', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
    ]},
    {'n': 'Quyosh shamoli', 't': 20, 'o': 24, 'q': [
        {'t': 'Quyosh shamoli nima?', 'a': [{'t': 'Oddiy shamol', 'c': False}, {'t': 'Quyoshdan chiqadigan zaryadlangan zarralar oqimi', 'c': True}, {'t': 'Faqat issiqlik', 'c': False}, {'t': 'Faqat yorug\'lik', 'c': False}]},
        {'t': 'Quyosh shamoli Yerga ta\'sir qiladimi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha, magnit bo\'ronlar keltirib chiqaradi', 'c': True}, {'t': 'Faqat issitadi', 'c': False}, {'t': 'Hech qanday ta\'sir yo\'q', 'c': False}]},
        {'t': 'Qutb chiroqlari qanday paydo bo\'ladi?', 'a': [{'t': 'Tasodifan', 'c': False}, {'t': 'Quyosh shamoli Yer atmosferasi bilan ta\'sirlashadi', 'c': True}, {'t': 'Faqat muzdan', 'c': False}, {'t': 'Faqat bulutlardan', 'c': False}]},
        {'t': 'Qutb chiroqlari qayerda ko\'rinadi?', 'a': [{'t': 'Hamma joyda', 'c': False}, {'t': 'Shimoliy va janubiy qutblarda', 'c': True}, {'t': 'Faqat ekvatorда', 'c': False}, {'t': 'Hech qayerda', 'c': False}]},
        {'t': 'Yer magnit maydoni nima qiladi?', 'a': [{'t': 'Hech narsa', 'c': False}, {'t': 'Quyosh shamolidan himoya qiladi', 'c': True}, {'t': 'Faqat yo\'nalish ko\'rsatadi', 'c': False}, {'t': 'Faqat bezaydi', 'c': False}]},
    ]},
    {'n': 'Kosmik nurlanish', 't': 20, 'o': 25, 'q': [
        {'t': 'Kosmik nurlar nima?', 'a': [{'t': 'Oddiy yorug\'lik', 'c': False}, {'t': 'Yuqori energiyali zarralar', 'c': True}, {'t': 'Faqat issiqlik', 'c': False}, {'t': 'Faqat shamol', 'c': False}]},
        {'t': 'Kosmik nurlar qayerdan keladi?', 'a': [{'t': 'Faqat Quyoshdan', 'c': False}, {'t': 'Supernova portlashlari, qora tuynuklar', 'c': True}, {'t': 'Faqat Yerdan', 'c': False}, {'t': 'Hech qayerdan', 'c': False}]},
        {'t': 'Kosmik nurlar xavflimi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha, yuqori dozada', 'c': True}, {'t': 'Faqat foydali', 'c': False}, {'t': 'Hech qanday ta\'sir yo\'q', 'c': False}]},
        {'t': 'Yer atmosferasi kosmik nurlardan himoya qiladimi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha, ko\'p qismini to\'sadi', 'c': True}, {'t': 'Faqat kuchaytirad', 'c': False}, {'t': 'Hech qanday ta\'sir yo\'q', 'c': False}]},
        {'t': 'Kosmonavtlar kosmik nurlardan qanday himoyalanadi?', 'a': [{'t': 'Hech qanday himoya yo\'q', 'c': False}, {'t': 'Maxsus kostyum va kema qobig\'i', 'c': True}, {'t': 'Faqat ko\'zoynak', 'c': False}, {'t': 'Faqat dori', 'c': False}]},
    ]},
    {'n': 'Gravitatsiya', 't': 20, 'o': 26, 'q': [
        {'t': 'Gravitatsiya nima?', 'a': [{'t': 'Itarish kuchi', 'c': False}, {'t': 'Tortishish kuchi', 'c': True}, {'t': 'Magnit kuchi', 'c': False}, {'t': 'Elektr kuchi', 'c': False}]},
        {'t': 'Gravitatsiya qonunini kim kashf etgan?', 'a': [{'t': 'Galiley', 'c': False}, {'t': 'Isaak Nyuton', 'c': True}, {'t': 'Eynshteyn', 'c': False}, {'t': 'Kopernik', 'c': False}]},
        {'t': 'Gravitatsiya kuchi nimaga bog\'liq?', 'a': [{'t': 'Faqat massaga', 'c': False}, {'t': 'Massa va masofaga', 'c': True}, {'t': 'Faqat masofaga', 'c': False}, {'t': 'Hech narsaga', 'c': False}]},
        {'t': 'Vaznsizlik nima?', 'a': [{'t': 'Gravitatsiya yo\'q', 'c': False}, {'t': 'Erkin tushish holati', 'c': True}, {'t': 'Faqat kosmosda', 'c': False}, {'t': 'Faqat Oyda', 'c': False}]},
        {'t': 'Oydagi gravitatsiya Yerdagidan qanday?', 'a': [{'t': 'Bir xil', 'c': False}, {'t': '6 marta kichik', 'c': True}, {'t': 'Katta', 'c': False}, {'t': 'Yo\'q', 'c': False}]},
    ]},
    {'n': 'Yorug\'lik tezligi', 't': 20, 'o': 27, 'q': [
        {'t': 'Yorug\'lik tezligi qancha?', 'a': [{'t': '100 km/s', 'c': False}, {'t': '300 000 km/s', 'c': True}, {'t': '1000 km/s', 'c': False}, {'t': '10 000 km/s', 'c': False}]},
        {'t': 'Yorug\'lik yili nima?', 'a': [{'t': 'Vaqt birligi', 'c': False}, {'t': 'Masofa birligi (yorug\'lik 1 yilda bosib o\'tadigan masofa)', 'c': True}, {'t': 'Tezlik birligi', 'c': False}, {'t': 'Massa birligi', 'c': False}]},
        {'t': '1 yorug\'lik yili qancha?', 'a': [{'t': '1 million km', 'c': False}, {'t': '9.46 trillion km', 'c': True}, {'t': '1000 km', 'c': False}, {'t': '100 million km', 'c': False}]},
        {'t': 'Quyosh nuri Yerga necha daqiqada yetadi?', 'a': [{'t': '1 daqiqa', 'c': False}, {'t': '8 daqiqa', 'c': True}, {'t': '1 soat', 'c': False}, {'t': '1 sekund', 'c': False}]},
        {'t': 'Eng yaqin yulduz (Proksima Kentavr) qancha uzoqda?', 'a': [{'t': '1 yorug\'lik yili', 'c': False}, {'t': '4.2 yorug\'lik yili', 'c': True}, {'t': '10 yorug\'lik yili', 'c': False}, {'t': '100 yorug\'lik yili', 'c': False}]},
    ]},
    {'n': 'Spektr va ranglar', 't': 20, 'o': 28, 'q': [
        {'t': 'Spektr nima?', 'a': [{'t': 'Faqat bitta rang', 'c': False}, {'t': 'Yorug\'likning ranglarga ajralishi', 'c': True}, {'t': 'Faqat qora rang', 'c': False}, {'t': 'Faqat oq rang', 'c': False}]},
        {'t': 'Ko\'rinadigan spektr qanday ranglardan iborat?', 'a': [{'t': 'Faqat qizil', 'c': False}, {'t': 'Qizil, to\'q sariq, sariq, yashil, ko\'k, indigo, binafsha', 'c': True}, {'t': 'Faqat qora va oq', 'c': False}, {'t': 'Hech qanday rang yo\'q', 'c': False}]},
        {'t': 'Yulduz spektri nimani ko\'rsatadi?', 'a': [{'t': 'Faqat rangini', 'c': False}, {'t': 'Harorati, tarkibi, tezligini', 'c': True}, {'t': 'Faqat hajmini', 'c': False}, {'t': 'Hech narsani', 'c': False}]},
        {'t': 'Qizil yulduzlar qanday?', 'a': [{'t': 'Eng issiq', 'c': False}, {'t': 'Eng sovuq (3000K)', 'c': True}, {'t': 'O\'rtacha', 'c': False}, {'t': 'Harorati yo\'q', 'c': False}]},
        {'t': 'Ko\'k yulduzlar qanday?', 'a': [{'t': 'Sovuq', 'c': False}, {'t': 'Eng issiq (30000K+)', 'c': True}, {'t': 'O\'rtacha', 'c': False}, {'t': 'Harorati yo\'q', 'c': False}]},
    ]},
    {'n': 'Doppler effekti', 't': 20, 'o': 29, 'q': [
        {'t': 'Doppler effekti nima?', 'a': [{'t': 'Faqat tovush', 'c': False}, {'t': 'Harakat tufayli to\'lqin uzunligining o\'zgarishi', 'c': True}, {'t': 'Faqat yorug\'lik', 'c': False}, {'t': 'Hech qanday o\'zgarish yo\'q', 'c': False}]},
        {'t': 'Qizil siljish nima?', 'a': [{'t': 'Yaqinlashish', 'c': False}, {'t': 'Uzoqlashish (to\'lqin uzunligi ortadi)', 'c': True}, {'t': 'Harakatsizlik', 'c': False}, {'t': 'Faqat rang o\'zgarishi', 'c': False}]},
        {'t': 'Ko\'k siljish nima?', 'a': [{'t': 'Uzoqlashish', 'c': False}, {'t': 'Yaqinlashish (to\'lqin uzunligi qisqaradi)', 'c': True}, {'t': 'Harakatsizlik', 'c': False}, {'t': 'Faqat rang o\'zgarishi', 'c': False}]},
        {'t': 'Doppler effekti astronomiyada nima uchun ishlatiladi?', 'a': [{'t': 'Faqat rangni aniqlash', 'c': False}, {'t': 'Yulduzlar tezligini o\'lchash', 'c': True}, {'t': 'Faqat hajmni o\'lchash', 'c': False}, {'t': 'Hech narsa uchun', 'c': False}]},
        {'t': 'Galaktikalar qizil siljish ko\'rsatsa, bu nima degani?', 'a': [{'t': 'Yaqinlashmoqda', 'c': False}, {'t': 'Uzoqlashmoqda', 'c': True}, {'t': 'Harakatsiz', 'c': False}, {'t': 'Yo\'q bo\'lib ketmoqda', 'c': False}]},
    ]},
    {'n': 'Parallaks usuli', 't': 20, 'o': 30, 'q': [
        {'t': 'Parallaks nima?', 'a': [{'t': 'Yulduz rangi', 'c': False}, {'t': 'Yulduzning ko\'rinma siljishi', 'c': True}, {'t': 'Yulduz hajmi', 'c': False}, {'t': 'Yulduz harorati', 'c': False}]},
        {'t': 'Parallaks usuli nima uchun ishlatiladi?', 'a': [{'t': 'Rangni aniqlash', 'c': False}, {'t': 'Yulduzgacha masofani o\'lchash', 'c': True}, {'t': 'Hajmni o\'lchash', 'c': False}, {'t': 'Haroratni o\'lchash', 'c': False}]},
        {'t': 'Parsek nima?', 'a': [{'t': 'Vaqt birligi', 'c': False}, {'t': 'Masofa birligi (3.26 yorug\'lik yili)', 'c': True}, {'t': 'Tezlik birligi', 'c': False}, {'t': 'Massa birligi', 'c': False}]},
        {'t': 'Parallaks usuli qaysi yulduzlar uchun ishlatiladi?', 'a': [{'t': 'Barcha yulduzlar', 'c': False}, {'t': 'Yaqin yulduzlar', 'c': True}, {'t': 'Faqat uzoq yulduzlar', 'c': False}, {'t': 'Hech qanday yulduz uchun', 'c': False}]},
        {'t': 'Parallaks qanday o\'lchanadi?', 'a': [{'t': 'Faqat ko\'z bilan', 'c': False}, {'t': 'Yer orbitasining turli nuqtalaridan kuzatish', 'c': True}, {'t': 'Faqat teleskop bilan', 'c': False}, {'t': 'O\'lchanmaydi', 'c': False}]},
    ]},
    {'n': 'Yulduz kattaligi', 't': 20, 'o': 31, 'q': [
        {'t': 'Ko\'rinma yulduz kattaligi nima?', 'a': [{'t': 'Haqiqiy hajmi', 'c': False}, {'t': 'Yerdan qanday yorqin ko\'rinishi', 'c': True}, {'t': 'Massasi', 'c': False}, {'t': 'Harorati', 'c': False}]},
        {'t': 'Absolyut yulduz kattaligi nima?', 'a': [{'t': 'Ko\'rinma kattaligi', 'c': False}, {'t': '10 parsek masofadan yorqinligi', 'c': True}, {'t': 'Massasi', 'c': False}, {'t': 'Hajmi', 'c': False}]},
        {'t': 'Eng yorqin yulduz (Yerdan)?', 'a': [{'t': 'Quyosh', 'c': True}, {'t': 'Sirius', 'c': False}, {'t': 'Vega', 'c': False}, {'t': 'Betelgeyze', 'c': False}]},
        {'t': 'Quyoshdan keyin eng yorqin yulduz?', 'a': [{'t': 'Vega', 'c': False}, {'t': 'Sirius', 'c': True}, {'t': 'Betelgeyze', 'c': False}, {'t': 'Rigel', 'c': False}]},
        {'t': 'Yulduz kattaligi shkalasi qanday?', 'a': [{'t': 'Katta son - yorqin', 'c': False}, {'t': 'Kichik son - yorqin', 'c': True}, {'t': 'Hech qanday shkala yo\'q', 'c': False}, {'t': 'Faqat rang', 'c': False}]},
    ]},
    {'n': 'Ikkilik yulduzlar', 't': 20, 'o': 32, 'q': [
        {'t': 'Ikkilik yulduz tizimi nima?', 'a': [{'t': 'Bitta yulduz', 'c': False}, {'t': 'Ikki yulduz bir-biri atrofida aylanadi', 'c': True}, {'t': 'Uch yulduz', 'c': False}, {'t': 'Sayyora va yulduz', 'c': False}]},
        {'t': 'Ikkilik yulduzlar qancha?', 'a': [{'t': 'Kam', 'c': False}, {'t': 'Yulduzlarning yarmidan ko\'pi', 'c': True}, {'t': 'Yo\'q', 'c': False}, {'t': 'Faqat bitta', 'c': False}]},
        {'t': 'Ko\'rinadigan ikkilik yulduzlar nima?', 'a': [{'t': 'Ko\'rinmaydi', 'c': False}, {'t': 'Teleskop bilan ikkita yulduz ko\'rinadi', 'c': True}, {'t': 'Faqat bitta ko\'rinadi', 'c': False}, {'t': 'Hech qachon ko\'rinmaydi', 'c': False}]},
        {'t': 'Spektrli ikkilik yulduzlar qanday aniqlanadi?', 'a': [{'t': 'Ko\'z bilan', 'c': False}, {'t': 'Spektr chizig\'ining siljishi orqali', 'c': True}, {'t': 'Faqat teleskop bilan', 'c': False}, {'t': 'Aniqlanmaydi', 'c': False}]},
        {'t': 'Tutiluvchi ikkilik yulduzlar nima?', 'a': [{'t': 'Hech qachon tutilmaydi', 'c': False}, {'t': 'Bir-birini yashiradi, yorqinlik o\'zgaradi', 'c': True}, {'t': 'Faqat bitta yulduz', 'c': False}, {'t': 'Sayyoralar', 'c': False}]},
    ]},
    {'n': 'Yulduz to\'plamlari', 't': 20, 'o': 33, 'q': [
        {'t': 'Yulduz to\'plami nima?', 'a': [{'t': 'Bitta yulduz', 'c': False}, {'t': 'Bir vaqtda tug\'ilgan yulduzlar guruhi', 'c': True}, {'t': 'Tasodifiy yulduzlar', 'c': False}, {'t': 'Sayyoralar', 'c': False}]},
        {'t': 'Ochiq yulduz to\'plami qanday?', 'a': [{'t': 'Juda zich', 'c': False}, {'t': 'Nisbatan kam yulduzli, yosh', 'c': True}, {'t': 'Juda qadimiy', 'c': False}, {'t': 'Yo\'q', 'c': False}]},
        {'t': 'Sharsimon to\'plam qanday?', 'a': [{'t': 'Kam yulduzli', 'c': False}, {'t': 'Juda ko\'p yulduzli, qadimiy, shar shakli', 'c': True}, {'t': 'Yosh', 'c': False}, {'t': 'Yo\'q', 'c': False}]},
        {'t': 'Pleyadalar nima?', 'a': [{'t': 'Sayyora', 'c': False}, {'t': 'Mashhur ochiq yulduz to\'plami', 'c': True}, {'t': 'Galaktika', 'c': False}, {'t': 'Kometa', 'c': False}]},
        {'t': 'Sharsimon to\'plamlarda nechta yulduz bo\'ladi?', 'a': [{'t': '10 ta', 'c': False}, {'t': 'Mingdan milliongacha', 'c': True}, {'t': '5 ta', 'c': False}, {'t': 'Yo\'q', 'c': False}]},
    ]},
    {'n': 'Tumanliklar', 't': 20, 'o': 34, 'q': [
        {'t': 'Tumanlik nima?', 'a': [{'t': 'Yulduz', 'c': False}, {'t': 'Gaz va chang buluti', 'c': True}, {'t': 'Sayyora', 'c': False}, {'t': 'Galaktika', 'c': False}]},
        {'t': 'Emissiya tumanlik nima?', 'a': [{'t': 'Qorong\'i', 'c': False}, {'t': 'O\'z nurini chiqaradi', 'c': True}, {'t': 'Faqat aks ettiradi', 'c': False}, {'t': 'Ko\'rinmaydi', 'c': False}]},
        {'t': 'Aks ettiruvchi tumanlik nima?', 'a': [{'t': 'O\'z nurini chiqaradi', 'c': False}, {'t': 'Yulduz nurini aks ettiradi', 'c': True}, {'t': 'Qorong\'i', 'c': False}, {'t': 'Ko\'rinmaydi', 'c': False}]},
        {'t': 'Qorong\'i tumanlik nima?', 'a': [{'t': 'Yorqin', 'c': False}, {'t': 'Orqadagi yulduzlarni yashiradi', 'c': True}, {'t': 'O\'z nurini chiqaradi', 'c': False}, {'t': 'Aks ettiradi', 'c': False}]},
        {'t': 'Orion tumanlig\'i qanday?', 'a': [{'t': 'Qorong\'i', 'c': False}, {'t': 'Yulduz tug\'ilish joyi, emissiya tumanlik', 'c': True}, {'t': 'Faqat aks ettiradi', 'c': False}, {'t': 'Ko\'rinmaydi', 'c': False}]},
    ]},
    {'n': 'Planetar tumanliklar', 't': 20, 'o': 35, 'q': [
        {'t': 'Planetar tumanlik nima?', 'a': [{'t': 'Sayyora', 'c': False}, {'t': 'O\'layotgan yulduzning tashqi qatlamlari', 'c': True}, {'t': 'Yosh yulduz', 'c': False}, {'t': 'Galaktika', 'c': False}]},
        {'t': 'Planetar tumanlik nima uchun shunday atalgan?', 'a': [{'t': 'Sayyora bo\'lgani uchun', 'c': False}, {'t': 'Sayyoraga o\'xshab ko\'ringani uchun', 'c': True}, {'t': 'Sayyora atrofida bo\'lgani uchun', 'c': False}, {'t': 'Hech qanday sabab yo\'q', 'c': False}]},
        {'t': 'Planetar tumanlik markazida nima bor?', 'a': [{'t': 'Hech narsa', 'c': False}, {'t': 'Oq mitti', 'c': True}, {'t': 'Qora tuynuk', 'c': False}, {'t': 'Sayyora', 'c': False}]},
        {'t': 'Quyosh kelajakda nima bo\'ladi?', 'a': [{'t': 'Qora tuynuk', 'c': False}, {'t': 'Qizil gigant, keyin planetar tumanlik va oq mitti', 'c': True}, {'t': 'Supernova', 'c': False}, {'t': 'Sayyora', 'c': False}]},
        {'t': 'Halqa tumanlik qanday?', 'a': [{'t': 'Kvadrat shakli', 'c': False}, {'t': 'Mashhur planetar tumanlik, halqa shakli', 'c': True}, {'t': 'Uchburchak', 'c': False}, {'t': 'Yo\'q', 'c': False}]},
    ]},
    {'n': 'Pulsarlar', 't': 20, 'o': 36, 'q': [
        {'t': 'Pulsar nima?', 'a': [{'t': 'Oddiy yulduz', 'c': False}, {'t': 'Aylanuvchi neytron yulduz', 'c': True}, {'t': 'Sayyora', 'c': False}, {'t': 'Galaktika', 'c': False}]},
        {'t': 'Pulsar qanday signal beradi?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Muntazam radio impulslar', 'c': True}, {'t': 'Faqat yorug\'lik', 'c': False}, {'t': 'Faqat issiqlik', 'c': False}]},
        {'t': 'Birinchi pulsar qachon topilgan?', 'a': [{'t': '1950 yilda', 'c': False}, {'t': '1967 yilda', 'c': True}, {'t': '2000 yilda', 'c': False}, {'t': '1900 yilda', 'c': False}]},
        {'t': 'Pulsar qanday paydo bo\'ladi?', 'a': [{'t': 'Oddiy yulduzdan', 'c': False}, {'t': 'Supernova portlashidan', 'c': True}, {'t': 'Sayyoradan', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Pulsar necha marta aylanadi?', 'a': [{'t': 'Sekin', 'c': False}, {'t': 'Juda tez (sekundiga minglab marta)', 'c': True}, {'t': 'Aylanmaydi', 'c': False}, {'t': 'Yiliga bir marta', 'c': False}]},
    ]},
    {'n': 'Kvazarlar', 't': 20, 'o': 37, 'q': [
        {'t': 'Kvazar nima?', 'a': [{'t': 'Oddiy yulduz', 'c': False}, {'t': 'Juda yorqin galaktika yadrosi', 'c': True}, {'t': 'Sayyora', 'c': False}, {'t': 'Asteroid', 'c': False}]},
        {'t': 'Kvazar energiyasi qayerdan?', 'a': [{'t': 'Oddiy yulduzlardan', 'c': False}, {'t': 'Supermassiv qora tuynukdan', 'c': True}, {'t': 'Sayyoralardan', 'c': False}, {'t': 'Hech qayerdan', 'c': False}]},
        {'t': 'Kvazarlar qancha uzoqda?', 'a': [{'t': 'Yaqin', 'c': False}, {'t': 'Juda uzoq (milliardlab yorug\'lik yili)', 'c': True}, {'t': '100 km', 'c': False}, {'t': '1000 km', 'c': False}]},
        {'t': 'Kvazarlar qachon ko\'p bo\'lgan?', 'a': [{'t': 'Hozir', 'c': False}, {'t': 'Koinotning yoshligida', 'c': True}, {'t': 'Kelajakda', 'c': False}, {'t': 'Hech qachon', 'c': False}]},
        {'t': 'Kvazar nima uchun yorqin?', 'a': [{'t': 'Kichik bo\'lgani uchun', 'c': False}, {'t': 'Qora tuynukka tushayotgan materiya', 'c': True}, {'t': 'Faqat yulduzlar', 'c': False}, {'t': 'Hech qanday sabab yo\'q', 'c': False}]},
    ]},
    {'n': 'Qora tuynuklar', 't': 20, 'o': 38, 'q': [
        {'t': 'Qora tuynuk nima?', 'a': [{'t': 'Oddiy yulduz', 'c': False}, {'t': 'Juda zich jism, hamma narsani o\'ziga tortadi', 'c': True}, {'t': 'Sayyora', 'c': False}, {'t': 'Galaktika', 'c': False}]},
        {'t': 'Qora tuynukdan nima chiqmaydi?', 'a': [{'t': 'Faqat materiya', 'c': False}, {'t': 'Hatto yorug\'lik ham', 'c': True}, {'t': 'Faqat tovush', 'c': False}, {'t': 'Hamma narsa chiqadi', 'c': False}]},
        {'t': 'Qora tuynuk qanday paydo bo\'ladi?', 'a': [{'t': 'Oddiy yulduzdan', 'c': False}, {'t': 'Juda katta yulduzning qulashidan', 'c': True}, {'t': 'Sayyoradan', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Hodisa gorizonti nima?', 'a': [{'t': 'Oddiy chegara', 'c': False}, {'t': 'Qora tuynuk chegarasi, undan qaytish mumkin emas', 'c': True}, {'t': 'Sayyora chegarasi', 'c': False}, {'t': 'Galaktika chegarasi', 'c': False}]},
        {'t': 'Supermassiv qora tuynuk qayerda?', 'a': [{'t': 'Hamma joyda', 'c': False}, {'t': 'Galaktikalar markazida', 'c': True}, {'t': 'Faqat Yerda', 'c': False}, {'t': 'Hech qayerda', 'c': False}]},
        {'t': 'Birinchi qora tuynuk rasmi qachon olingan?', 'a': [{'t': '1990 yilda', 'c': False}, {'t': '2019 yilda (M87 galaktikasi)', 'c': True}, {'t': '2025 yilda', 'c': False}, {'t': 'Hech qachon', 'c': False}]},
    ]},
    {'n': 'Nisbiylik nazariyasi', 't': 20, 'o': 39, 'q': [
        {'t': 'Nisbiylik nazariyasini kim yaratgan?', 'a': [{'t': 'Nyuton', 'c': False}, {'t': 'Albert Eynshteyn', 'c': True}, {'t': 'Galiley', 'c': False}, {'t': 'Kopernik', 'c': False}]},
        {'t': 'Maxsus nisbiylik nazariyasi nimani aytadi?', 'a': [{'t': 'Vaqt mutlaq', 'c': False}, {'t': 'Vaqt va makon nisbiy', 'c': True}, {'t': 'Hamma narsa bir xil', 'c': False}, {'t': 'Hech narsa o\'zgarmaydi', 'c': False}]},
        {'t': 'Umumiy nisbiylik nazariyasi nimani tushuntiradi?', 'a': [{'t': 'Faqat harakat', 'c': False}, {'t': 'Gravitatsiya - fazo-vaqt egriligi', 'c': True}, {'t': 'Faqat yorug\'lik', 'c': False}, {'t': 'Hech narsani', 'c': False}]},
        {'t': 'E=mc² formulasi nimani bildiradi?', 'a': [{'t': 'Hech narsani', 'c': False}, {'t': 'Energiya va massa ekvivalent', 'c': True}, {'t': 'Faqat tezlik', 'c': False}, {'t': 'Faqat vaqt', 'c': False}]},
        {'t': 'Gravitatsion to\'lqinlar nima?', 'a': [{'t': 'Oddiy to\'lqinlar', 'c': False}, {'t': 'Fazo-vaqt to\'lqinlari', 'c': True}, {'t': 'Suv to\'lqinlari', 'c': False}, {'t': 'Tovush to\'lqinlari', 'c': False}]},
    ]},
    {'n': 'Kvant mexanikasi va astronomiya', 't': 20, 'o': 40, 'q': [
        {'t': 'Kvant mexanikasi nima o\'rganadi?', 'a': [{'t': 'Faqat katta jismlar', 'c': False}, {'t': 'Mikrodunyoni', 'c': True}, {'t': 'Faqat yulduzlar', 'c': False}, {'t': 'Hech narsani', 'c': False}]},
        {'t': 'Foton nima?', 'a': [{'t': 'Atom', 'c': False}, {'t': 'Yorug\'lik zarrasi', 'c': True}, {'t': 'Elektron', 'c': False}, {'t': 'Proton', 'c': False}]},
        {'t': 'Kvant mexanikasi astronomiyada qanday ishlatiladi?', 'a': [{'t': 'Ishlatilmaydi', 'c': False}, {'t': 'Yulduz spektrini, yadro sintezini tushuntiradi', 'c': True}, {'t': 'Faqat sayyoralar uchun', 'c': False}, {'t': 'Hech qayerda', 'c': False}]},
        {'t': 'Yadro sintezi nima?', 'a': [{'t': 'Atomlarning parchalanishi', 'c': False}, {'t': 'Yengil atomlarning birlashishi', 'c': True}, {'t': 'Faqat kimyoviy reaktsiya', 'c': False}, {'t': 'Hech qanday jarayon emas', 'c': False}]},
        {'t': 'Yulduzlarda qanday yadro sintezi boradi?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Vodorod geliyga aylanadi', 'c': True}, {'t': 'Faqat kislorod', 'c': False}, {'t': 'Faqat temir', 'c': False}]},
    ]},
    {'n': 'Kosmik parvozlar', 't': 20, 'o': 41, 'q': [
        {'t': 'Birinchi kosmik tezlik nima?', 'a': [{'t': '1 km/s', 'c': False}, {'t': '7.9 km/s (Yer orbitasiga chiqish)', 'c': True}, {'t': '100 km/s', 'c': False}, {'t': '1000 km/s', 'c': False}]},
        {'t': 'Ikkinchi kosmik tezlik nima?', 'a': [{'t': '1 km/s', 'c': False}, {'t': '11.2 km/s (Yerdan qochish)', 'c': True}, {'t': '5 km/s', 'c': False}, {'t': '100 km/s', 'c': False}]},
        {'t': 'Uchinchi kosmik tezlik nima?', 'a': [{'t': '10 km/s', 'c': False}, {'t': '16.7 km/s (Quyosh tizimidan chiqish)', 'c': True}, {'t': '5 km/s', 'c': False}, {'t': '100 km/s', 'c': False}]},
        {'t': 'Raketa qanday ishlaydi?', 'a': [{'t': 'Shamol bilan', 'c': False}, {'t': 'Reaktiv kuch (gaz chiqarish)', 'c': True}, {'t': 'Magnit bilan', 'c': False}, {'t': 'Ishlamaydi', 'c': False}]},
        {'t': 'Kosmosda raketa qanday harakatlanadi?', 'a': [{'t': 'Havo bilan', 'c': False}, {'t': 'Nyutonning 3-qonuni (ta\'sir-qarshi ta\'sir)', 'c': True}, {'t': 'Magnit bilan', 'c': False}, {'t': 'Harakatlanmaydi', 'c': False}]},
    ]},
    {'n': 'Sun\'iy yo\'ldoshlar', 't': 20, 'o': 42, 'q': [
        {'t': 'Sun\'iy yo\'ldosh nima?', 'a': [{'t': 'Tabiiy yo\'ldosh', 'c': False}, {'t': 'Odam yasagan kosmik apparat', 'c': True}, {'t': 'Sayyora', 'c': False}, {'t': 'Yulduz', 'c': False}]},
        {'t': 'Sun\'iy yo\'ldoshlar nima uchun ishlatiladi?', 'a': [{'t': 'Faqat bezash', 'c': False}, {'t': 'Aloqa, navigatsiya, ob-havo, tadqiqot', 'c': True}, {'t': 'Hech narsa uchun', 'c': False}, {'t': 'Faqat o\'yin', 'c': False}]},
        {'t': 'GPS nima?', 'a': [{'t': 'Sayyora', 'c': False}, {'t': 'Global joylashuvni aniqlash tizimi', 'c': True}, {'t': 'Yulduz', 'c': False}, {'t': 'Galaktika', 'c': False}]},
        {'t': 'Geostatsionar orbita nima?', 'a': [{'t': 'Yer yuzasida', 'c': False}, {'t': 'Yo\'ldosh Yer bilan bir xil tezlikda aylanadi', 'c': True}, {'t': 'Juda past orbita', 'c': False}, {'t': 'Oyda', 'c': False}]},
        {'t': 'Hozir nechta sun\'iy yo\'ldosh bor?', 'a': [{'t': '10 ta', 'c': False}, {'t': 'Minglab', 'c': True}, {'t': '5 ta', 'c': False}, {'t': 'Yo\'q', 'c': False}]},
    ]},
    {'n': 'Kosmik axlat muammosi', 't': 20, 'o': 43, 'q': [
        {'t': 'Kosmik axlat nima?', 'a': [{'t': 'Yerda axlat', 'c': False}, {'t': 'Orbitadagi ishlamay qolgan ob\'ektlar', 'c': True}, {'t': 'Sayyoralar', 'c': False}, {'t': 'Yulduzlar', 'c': False}]},
        {'t': 'Kosmik axlat qanday paydo bo\'ladi?', 'a': [{'t': 'Tabiiy ravishda', 'c': False}, {'t': 'Eski sun\'iy yo\'ldoshlar, raketa qoldiqlari', 'c': True}, {'t': 'Yulduzlardan', 'c': False}, {'t': 'Hech qanday', 'c': False}]},
        {'t': 'Kosmik axlat xavflimi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha, to\'qnashuv xavfi', 'c': True}, {'t': 'Faqat foydali', 'c': False}, {'t': 'Hech qanday ta\'sir yo\'q', 'c': False}]},
        {'t': 'Kosmik axlatni qanday tozalash mumkin?', 'a': [{'t': 'Hech qanday yo\'l yo\'q', 'c': False}, {'t': 'Maxsus zondlar, to\'rlar, lazerlar', 'c': True}, {'t': 'Faqat kutish', 'c': False}, {'t': 'O\'z-o\'zidan yo\'qoladi', 'c': False}]},
        {'t': 'Kessler sindromi nima?', 'a': [{'t': 'Kasallik', 'c': False}, {'t': 'Kosmik axlat zanjir to\'qnashuvi', 'c': True}, {'t': 'Sayyora nomi', 'c': False}, {'t': 'Yulduz nomi', 'c': False}]},
    ]},
    {'n': 'Marsga sayohat', 't': 20, 'o': 44, 'q': [
        {'t': 'Marsga parvoz qancha vaqt oladi?', 'a': [{'t': '1 hafta', 'c': False}, {'t': '6-9 oy', 'c': True}, {'t': '1 kun', 'c': False}, {'t': '10 yil', 'c': False}]},
        {'t': 'Marsga sayohatning asosiy muammolari?', 'a': [{'t': 'Hech qanday muammo yo\'q', 'c': False}, {'t': 'Radiatsiya, uzoq vaqt, psixologik', 'c': True}, {'t': 'Faqat pul', 'c': False}, {'t': 'Faqat vaqt', 'c': False}]},
        {'t': 'Marsda koloniya qurish mumkinmi?', 'a': [{'t': 'Yo\'q, mumkin emas', 'c': False}, {'t': 'Ha, rejalar bor', 'c': True}, {'t': 'Allaqachon qurilgan', 'c': False}, {'t': 'Hech qachon', 'c': False}]},
        {'t': 'SpaceX kompaniyasi nima rejalashtirmoqda?', 'a': [{'t': 'Hech narsa', 'c': False}, {'t': 'Marsga odam yuborish', 'c': True}, {'t': 'Faqat Yerda qolish', 'c': False}, {'t': 'Faqat sun\'iy yo\'ldosh', 'c': False}]},
        {'t': 'Marsda suv topish nima uchun muhim?', 'a': [{'t': 'Muhim emas', 'c': False}, {'t': 'Ichish, kislorod, raketa yoqilg\'isi uchun', 'c': True}, {'t': 'Faqat bezash uchun', 'c': False}, {'t': 'Hech narsa uchun', 'c': False}]},
    ]},
    {'n': 'Oy bazasi', 't': 20, 'o': 45, 'q': [
        {'t': 'Oyda baza qurish mumkinmi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha, rejalar bor', 'c': True}, {'t': 'Allaqachon qurilgan', 'c': False}, {'t': 'Hech qachon', 'c': False}]},
        {'t': 'Oy bazasining afzalliklari?', 'a': [{'t': 'Hech qanday', 'c': False}, {'t': 'Yerga yaqin, past gravitatsiya, resurslar', 'c': True}, {'t': 'Faqat go\'zallik', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'Oyda qanday resurslar bor?', 'a': [{'t': 'Hech narsa yo\'q', 'c': False}, {'t': 'Geliy-3, suv muzi, minerallar', 'c': True}, {'t': 'Faqat tosh', 'c': False}, {'t': 'Faqat chang', 'c': False}]},
        {'t': 'Artemis dasturi nima?', 'a': [{'t': 'Mars dasturi', 'c': False}, {'t': 'Oyga qaytish dasturi (NASA)', 'c': True}, {'t': 'Yupiter dasturi', 'c': False}, {'t': 'Hech qanday dastur emas', 'c': False}]},
        {'t': 'Oydan raketa uchirish nima uchun oson?', 'a': [{'t': 'Oson emas', 'c': False}, {'t': 'Past gravitatsiya, atmosfera yo\'q', 'c': True}, {'t': 'Faqat kichik', 'c': False}, {'t': 'Hech qanday sabab yo\'q', 'c': False}]},
    ]},
    {'n': 'Asteroid xavfi', 't': 20, 'o': 46, 'q': [
        {'t': 'Asteroid Yerga urilishi mumkinmi?', 'a': [{'t': 'Yo\'q, hech qachon', 'c': False}, {'t': 'Ha, mumkin', 'c': True}, {'t': 'Allaqachon tugadi', 'c': False}, {'t': 'Faqat kino', 'c': False}]},
        {'t': 'Dinozavrlar qanday yo\'q bo\'lgan?', 'a': [{'t': 'Kasallikdan', 'c': False}, {'t': 'Katta asteroid urilishi (66 mln yil oldin)', 'c': True}, {'t': 'Ochlikdan', 'c': False}, {'t': 'Hech qachon yo\'q bo\'lmagan', 'c': False}]},
        {'t': 'Xavfli asteroidlar kuzatilmoqdami?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ha, maxsus dasturlar bor', 'c': True}, {'t': 'Hech kim kuzatmaydi', 'c': False}, {'t': 'Kerak emas', 'c': False}]},
        {'t': 'Asteroidni qanday to\'xtatish mumkin?', 'a': [{'t': 'Hech qanday yo\'l yo\'q', 'c': False}, {'t': 'Yo\'nalishini o\'zgartirish (zond urish)', 'c': True}, {'t': 'Faqat portlatish', 'c': False}, {'t': 'Kutish', 'c': False}]},
        {'t': 'DART missiyasi nima edi?', 'a': [{'t': 'Mars missiyasi', 'c': False}, {'t': 'Asteroidga zond urib yo\'nalishini o\'zgartirish (2022)', 'c': True}, {'t': 'Oy missiyasi', 'c': False}, {'t': 'Hech qanday missiya emas', 'c': False}]},
    ]},
    {'n': 'Yulduzlararo sayohat', 't': 20, 'o': 47, 'q': [
        {'t': 'Yulduzlararo sayohat mumkinmi?', 'a': [{'t': 'Yo\'q, hech qachon', 'c': False}, {'t': 'Nazariy jihatdan mumkin, lekin juda qiyin', 'c': True}, {'t': 'Oson', 'c': False}, {'t': 'Allaqachon amalga oshirilgan', 'c': False}]},
        {'t': 'Asosiy muammo nima?', 'a': [{'t': 'Pul', 'c': False}, {'t': 'Juda katta masofalar va vaqt', 'c': True}, {'t': 'Faqat texnologiya', 'c': False}, {'t': 'Hech qanday muammo yo\'q', 'c': False}]},
        {'t': 'Eng yaqin yulduzga qancha vaqt kerak (hozirgi texnologiya)?', 'a': [{'t': '1 yil', 'c': False}, {'t': 'Minglab yillar', 'c': True}, {'t': '10 yil', 'c': False}, {'t': '1 oy', 'c': False}]},
        {'t': 'Avlod kemasi nima?', 'a': [{'t': 'Oddiy kema', 'c': False}, {'t': 'Ko\'p avlod yashaydigan kema', 'c': True}, {'t': 'Tez kema', 'c': False}, {'t': 'Kichik kema', 'c': False}]},
        {'t': 'Kriogen uyqu nima?', 'a': [{'t': 'Oddiy uyqu', 'c': False}, {'t': 'Muzlatilgan holda saqlash', 'c': True}, {'t': 'Tez uyqu', 'c': False}, {'t': 'Hech qanday uyqu emas', 'c': False}]},
    ]},
    {'n': 'Varpdrayv va fantastika', 't': 20, 'o': 48, 'q': [
        {'t': 'Varpdrayv nima?', 'a': [{'t': 'Haqiqiy texnologiya', 'c': False}, {'t': 'Fantastik yorug\'likdan tez harakat', 'c': True}, {'t': 'Oddiy dvigatel', 'c': False}, {'t': 'Avtomobil dvigateli', 'c': False}]},
        {'t': 'Yorug\'likdan tez harakat mumkinmi?', 'a': [{'t': 'Ha, oson', 'c': False}, {'t': 'Maxsus nisbiylikka ko\'ra yo\'q', 'c': True}, {'t': 'Allaqachon bor', 'c': False}, {'t': 'Faqat kinoda', 'c': False}]},
        {'t': 'Qurt teshigi nima?', 'a': [{'t': 'Oddiy teshik', 'c': False}, {'t': 'Nazariy fazo-vaqt tunneli', 'c': True}, {'t': 'Yerda teshik', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'Qurt teshigi mavjudmi?', 'a': [{'t': 'Ha, ko\'p', 'c': False}, {'t': 'Noma\'lum, faqat nazariya', 'c': True}, {'t': 'Yo\'q, umuman', 'c': False}, {'t': 'Faqat kinoda', 'c': False}]},
        {'t': 'Vaqt sayohati mumkinmi?', 'a': [{'t': 'Ha, oson', 'c': False}, {'t': 'Nazariy jihatdan kelajakka mumkin', 'c': True}, {'t': 'Allaqachon bor', 'c': False}, {'t': 'Yo\'q, umuman', 'c': False}]},
    ]},
    {'n': 'Fermi paradoksi', 't': 20, 'o': 49, 'q': [
        {'t': 'Fermi paradoksi nima?', 'a': [{'t': 'Oddiy savol', 'c': False}, {'t': 'Nega boshqa sivilizatsiyalar topilmayapti?', 'c': True}, {'t': 'Matematika muammosi', 'c': False}, {'t': 'Fizika qonuni', 'c': False}]},
        {'t': 'Koinotda hayot ko\'pmi?', 'a': [{'t': 'Yo\'q', 'c': False}, {'t': 'Ehtimol ko\'p, lekin topilmagan', 'c': True}, {'t': 'Faqat Yerda', 'c': False}, {'t': 'Hamma joyda', 'c': False}]},
        {'t': 'Nima uchun boshqa sivilizatsiyalar topilmayapti?', 'a': [{'t': 'Faqat bitta sabab', 'c': False}, {'t': 'Ko\'p nazariyalar: uzoq, qisqa umr, yashirinish', 'c': True}, {'t': 'Ular yo\'q', 'c': False}, {'t': 'Biz qidirmayapmiz', 'c': False}]},
        {'t': 'Buyuk filtr nazariyasi nima?', 'a': [{'t': 'Suv filtri', 'c': False}, {'t': 'Sivilizatsiyalar rivojlanishida to\'siq', 'c': True}, {'t': 'Havo filtri', 'c': False}, {'t': 'Hech narsa', 'c': False}]},
        {'t': 'Kardashev shkalasi nima?', 'a': [{'t': 'Harorat shkalasi', 'c': False}, {'t': 'Sivilizatsiya rivojlanish darajasi', 'c': True}, {'t': 'Masofa shkalasi', 'c': False}, {'t': 'Vaqt shkalasi', 'c': False}]},
    ]},
    {'n': 'Multiverse nazariyasi', 't': 20, 'o': 50, 'q': [
        {'t': 'Multiverse nima?', 'a': [{'t': 'Bitta koinot', 'c': False}, {'t': 'Ko\'p koinotlar nazariyasi', 'c': True}, {'t': 'Galaktika', 'c': False}, {'t': 'Sayyora', 'c': False}]},
        {'t': 'Multiverse mavjudmi?', 'a': [{'t': 'Ha, isbotlangan', 'c': False}, {'t': 'Noma\'lum, faqat nazariya', 'c': True}, {'t': 'Yo\'q, umuman', 'c': False}, {'t': 'Faqat kinoda', 'c': False}]},
        {'t': 'Parallel koinotlar nima?', 'a': [{'t': 'Bir xil koinotlar', 'c': False}, {'t': 'Boshqa qonunlar bilan koinotlar', 'c': True}, {'t': 'Faqat bizniki', 'c': False}, {'t': 'Yo\'q', 'c': False}]},
        {'t': 'Multiverse nazariyasi qayerdan kelib chiqqan?', 'a': [{'t': 'Fantastikadan', 'c': False}, {'t': 'Kvant mexanikasi va kosmologiyadan', 'c': True}, {'t': 'Faqat tasavvurdan', 'c': False}, {'t': 'Hech qayerdan', 'c': False}]},
        {'t': 'Boshqa koinotlarni kuzatish mumkinmi?', 'a': [{'t': 'Ha, oson', 'c': False}, {'t': 'Yo\'q, nazariy jihatdan mumkin emas', 'c': True}, {'t': 'Allaqachon kuzatilgan', 'c': False}, {'t': 'Faqat teleskop bilan', 'c': False}]},
    ]},
